/*
AliExpress Parser API

Real-time AliExpress data parser covering products, product reviews, sellers, store coupons, a seller's product catalog, and product search by text or image. Products: pricing, stock status, shipping options, seller information, product configurations (SKUs), and more - scoped to a specific country and currency. Reviews: customer ratings and feedback for a product. Sellers: full store profile with ratings, feedback, and categories. Coupons: active seller coupon codes with discounts, thresholds, budgets, and expiry. Seller products: a store's product catalog, paginated and best-selling first. Search: find products by keyword or by uploading an image, returning paginated product results with their categories. 

API version: 2.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aligate

import (
	"encoding/json"
)

// checks if the SearchParseResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SearchParseResponse{}

// SearchParseResponse Top-level response envelope returned by the gateway for keyword-search requests
type SearchParseResponse struct {
	Meta *SearchMeta `json:"meta,omitempty"`
	Settings *SearchSettings `json:"settings,omitempty"`
	Item *SearchResult `json:"item,omitempty"`
}

// NewSearchParseResponse instantiates a new SearchParseResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSearchParseResponse() *SearchParseResponse {
	this := SearchParseResponse{}
	return &this
}

// NewSearchParseResponseWithDefaults instantiates a new SearchParseResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSearchParseResponseWithDefaults() *SearchParseResponse {
	this := SearchParseResponse{}
	return &this
}

// GetMeta returns the Meta field value if set, zero value otherwise.
func (o *SearchParseResponse) GetMeta() SearchMeta {
	if o == nil || IsNil(o.Meta) {
		var ret SearchMeta
		return ret
	}
	return *o.Meta
}

// GetMetaOk returns a tuple with the Meta field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchParseResponse) GetMetaOk() (*SearchMeta, bool) {
	if o == nil || IsNil(o.Meta) {
		return nil, false
	}
	return o.Meta, true
}

// HasMeta returns a boolean if a field has been set.
func (o *SearchParseResponse) HasMeta() bool {
	if o != nil && !IsNil(o.Meta) {
		return true
	}

	return false
}

// SetMeta gets a reference to the given SearchMeta and assigns it to the Meta field.
func (o *SearchParseResponse) SetMeta(v SearchMeta) {
	o.Meta = &v
}

// GetSettings returns the Settings field value if set, zero value otherwise.
func (o *SearchParseResponse) GetSettings() SearchSettings {
	if o == nil || IsNil(o.Settings) {
		var ret SearchSettings
		return ret
	}
	return *o.Settings
}

// GetSettingsOk returns a tuple with the Settings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchParseResponse) GetSettingsOk() (*SearchSettings, bool) {
	if o == nil || IsNil(o.Settings) {
		return nil, false
	}
	return o.Settings, true
}

// HasSettings returns a boolean if a field has been set.
func (o *SearchParseResponse) HasSettings() bool {
	if o != nil && !IsNil(o.Settings) {
		return true
	}

	return false
}

// SetSettings gets a reference to the given SearchSettings and assigns it to the Settings field.
func (o *SearchParseResponse) SetSettings(v SearchSettings) {
	o.Settings = &v
}

// GetItem returns the Item field value if set, zero value otherwise.
func (o *SearchParseResponse) GetItem() SearchResult {
	if o == nil || IsNil(o.Item) {
		var ret SearchResult
		return ret
	}
	return *o.Item
}

// GetItemOk returns a tuple with the Item field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchParseResponse) GetItemOk() (*SearchResult, bool) {
	if o == nil || IsNil(o.Item) {
		return nil, false
	}
	return o.Item, true
}

// HasItem returns a boolean if a field has been set.
func (o *SearchParseResponse) HasItem() bool {
	if o != nil && !IsNil(o.Item) {
		return true
	}

	return false
}

// SetItem gets a reference to the given SearchResult and assigns it to the Item field.
func (o *SearchParseResponse) SetItem(v SearchResult) {
	o.Item = &v
}

func (o SearchParseResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SearchParseResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Meta) {
		toSerialize["meta"] = o.Meta
	}
	if !IsNil(o.Settings) {
		toSerialize["settings"] = o.Settings
	}
	if !IsNil(o.Item) {
		toSerialize["item"] = o.Item
	}
	return toSerialize, nil
}

type NullableSearchParseResponse struct {
	value *SearchParseResponse
	isSet bool
}

func (v NullableSearchParseResponse) Get() *SearchParseResponse {
	return v.value
}

func (v *NullableSearchParseResponse) Set(val *SearchParseResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableSearchParseResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableSearchParseResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSearchParseResponse(val *SearchParseResponse) *NullableSearchParseResponse {
	return &NullableSearchParseResponse{value: val, isSet: true}
}

func (v NullableSearchParseResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSearchParseResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


