/*
AliExpress Parser API

Real-time AliExpress data parser covering products, product reviews, sellers, store coupons, a seller's product catalog, and product search by text or image. Products: pricing, stock status, shipping options, seller information, product configurations (SKUs), and more - scoped to a specific country and currency. Reviews: customer ratings and feedback for a product. Sellers: full store profile with ratings, feedback, and categories. Coupons: active seller coupon codes with discounts, thresholds, budgets, and expiry. Seller products: a store's product catalog, paginated and best-selling first. Search: find products by keyword or by uploading an image, returning paginated product results with their categories. 

API version: 2.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aligate

import (
	"encoding/json"
)

// checks if the SellerProductsParseResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SellerProductsParseResponse{}

// SellerProductsParseResponse Top-level response envelope returned by the gateway for seller-catalog requests
type SellerProductsParseResponse struct {
	Meta *SellerProductsMeta `json:"meta,omitempty"`
	Settings *SellerProductsSettings `json:"settings,omitempty"`
	Item *SellerProductsResult `json:"item,omitempty"`
}

// NewSellerProductsParseResponse instantiates a new SellerProductsParseResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSellerProductsParseResponse() *SellerProductsParseResponse {
	this := SellerProductsParseResponse{}
	return &this
}

// NewSellerProductsParseResponseWithDefaults instantiates a new SellerProductsParseResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSellerProductsParseResponseWithDefaults() *SellerProductsParseResponse {
	this := SellerProductsParseResponse{}
	return &this
}

// GetMeta returns the Meta field value if set, zero value otherwise.
func (o *SellerProductsParseResponse) GetMeta() SellerProductsMeta {
	if o == nil || IsNil(o.Meta) {
		var ret SellerProductsMeta
		return ret
	}
	return *o.Meta
}

// GetMetaOk returns a tuple with the Meta field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SellerProductsParseResponse) GetMetaOk() (*SellerProductsMeta, bool) {
	if o == nil || IsNil(o.Meta) {
		return nil, false
	}
	return o.Meta, true
}

// HasMeta returns a boolean if a field has been set.
func (o *SellerProductsParseResponse) HasMeta() bool {
	if o != nil && !IsNil(o.Meta) {
		return true
	}

	return false
}

// SetMeta gets a reference to the given SellerProductsMeta and assigns it to the Meta field.
func (o *SellerProductsParseResponse) SetMeta(v SellerProductsMeta) {
	o.Meta = &v
}

// GetSettings returns the Settings field value if set, zero value otherwise.
func (o *SellerProductsParseResponse) GetSettings() SellerProductsSettings {
	if o == nil || IsNil(o.Settings) {
		var ret SellerProductsSettings
		return ret
	}
	return *o.Settings
}

// GetSettingsOk returns a tuple with the Settings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SellerProductsParseResponse) GetSettingsOk() (*SellerProductsSettings, bool) {
	if o == nil || IsNil(o.Settings) {
		return nil, false
	}
	return o.Settings, true
}

// HasSettings returns a boolean if a field has been set.
func (o *SellerProductsParseResponse) HasSettings() bool {
	if o != nil && !IsNil(o.Settings) {
		return true
	}

	return false
}

// SetSettings gets a reference to the given SellerProductsSettings and assigns it to the Settings field.
func (o *SellerProductsParseResponse) SetSettings(v SellerProductsSettings) {
	o.Settings = &v
}

// GetItem returns the Item field value if set, zero value otherwise.
func (o *SellerProductsParseResponse) GetItem() SellerProductsResult {
	if o == nil || IsNil(o.Item) {
		var ret SellerProductsResult
		return ret
	}
	return *o.Item
}

// GetItemOk returns a tuple with the Item field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SellerProductsParseResponse) GetItemOk() (*SellerProductsResult, bool) {
	if o == nil || IsNil(o.Item) {
		return nil, false
	}
	return o.Item, true
}

// HasItem returns a boolean if a field has been set.
func (o *SellerProductsParseResponse) HasItem() bool {
	if o != nil && !IsNil(o.Item) {
		return true
	}

	return false
}

// SetItem gets a reference to the given SellerProductsResult and assigns it to the Item field.
func (o *SellerProductsParseResponse) SetItem(v SellerProductsResult) {
	o.Item = &v
}

func (o SellerProductsParseResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SellerProductsParseResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Meta) {
		toSerialize["meta"] = o.Meta
	}
	if !IsNil(o.Settings) {
		toSerialize["settings"] = o.Settings
	}
	if !IsNil(o.Item) {
		toSerialize["item"] = o.Item
	}
	return toSerialize, nil
}

type NullableSellerProductsParseResponse struct {
	value *SellerProductsParseResponse
	isSet bool
}

func (v NullableSellerProductsParseResponse) Get() *SellerProductsParseResponse {
	return v.value
}

func (v *NullableSellerProductsParseResponse) Set(val *SellerProductsParseResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableSellerProductsParseResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableSellerProductsParseResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSellerProductsParseResponse(val *SellerProductsParseResponse) *NullableSellerProductsParseResponse {
	return &NullableSellerProductsParseResponse{value: val, isSet: true}
}

func (v NullableSellerProductsParseResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSellerProductsParseResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


