/*
AliExpress Parser API

Real-time AliExpress data parser covering products, product reviews, sellers, store coupons, a seller's product catalog, and product search by text or image. Products: pricing, stock status, shipping options, seller information, product configurations (SKUs), and more - scoped to a specific country and currency. Reviews: customer ratings and feedback for a product. Sellers: full store profile with ratings, feedback, and categories. Coupons: active seller coupon codes with discounts, thresholds, budgets, and expiry. Seller products: a store's product catalog, paginated and best-selling first. Search: find products by keyword or by uploading an image, returning paginated product results with their categories. 

API version: 2.1.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aligate

import (
	"encoding/json"
)

// checks if the Price type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Price{}

// Price Price data for the product scoped to the requested country and currency
type Price struct {
	// SKU identifier string
	SkuId *string `json:"sku_id,omitempty"`
	// SKU identifier as integer
	SkuIdInt *int64 `json:"sku_id_int,omitempty"`
	// Price per unit when buying in bulk
	BulkValue *float64 `json:"bulk_value,omitempty"`
	// Minimum quantity for bulk pricing
	BulkOrder *int64 `json:"bulk_order,omitempty"`
	// Minimum price (lowest SKU variant)
	MinValue *float64 `json:"min_value,omitempty"`
	// Maximum price (highest SKU variant)
	MaxValue *float64 `json:"max_value,omitempty"`
	// Original (pre-discount) minimum price
	OriginalMinValue *float64 `json:"original_min_value,omitempty"`
	// Original (pre-discount) maximum price
	OriginalMaxValue *float64 `json:"original_max_value,omitempty"`
	Currency *string `json:"currency,omitempty"`
	Country *string `json:"country,omitempty"`
}

// NewPrice instantiates a new Price object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPrice() *Price {
	this := Price{}
	return &this
}

// NewPriceWithDefaults instantiates a new Price object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPriceWithDefaults() *Price {
	this := Price{}
	return &this
}

// GetSkuId returns the SkuId field value if set, zero value otherwise.
func (o *Price) GetSkuId() string {
	if o == nil || IsNil(o.SkuId) {
		var ret string
		return ret
	}
	return *o.SkuId
}

// GetSkuIdOk returns a tuple with the SkuId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Price) GetSkuIdOk() (*string, bool) {
	if o == nil || IsNil(o.SkuId) {
		return nil, false
	}
	return o.SkuId, true
}

// HasSkuId returns a boolean if a field has been set.
func (o *Price) HasSkuId() bool {
	if o != nil && !IsNil(o.SkuId) {
		return true
	}

	return false
}

// SetSkuId gets a reference to the given string and assigns it to the SkuId field.
func (o *Price) SetSkuId(v string) {
	o.SkuId = &v
}

// GetSkuIdInt returns the SkuIdInt field value if set, zero value otherwise.
func (o *Price) GetSkuIdInt() int64 {
	if o == nil || IsNil(o.SkuIdInt) {
		var ret int64
		return ret
	}
	return *o.SkuIdInt
}

// GetSkuIdIntOk returns a tuple with the SkuIdInt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Price) GetSkuIdIntOk() (*int64, bool) {
	if o == nil || IsNil(o.SkuIdInt) {
		return nil, false
	}
	return o.SkuIdInt, true
}

// HasSkuIdInt returns a boolean if a field has been set.
func (o *Price) HasSkuIdInt() bool {
	if o != nil && !IsNil(o.SkuIdInt) {
		return true
	}

	return false
}

// SetSkuIdInt gets a reference to the given int64 and assigns it to the SkuIdInt field.
func (o *Price) SetSkuIdInt(v int64) {
	o.SkuIdInt = &v
}

// GetBulkValue returns the BulkValue field value if set, zero value otherwise.
func (o *Price) GetBulkValue() float64 {
	if o == nil || IsNil(o.BulkValue) {
		var ret float64
		return ret
	}
	return *o.BulkValue
}

// GetBulkValueOk returns a tuple with the BulkValue field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Price) GetBulkValueOk() (*float64, bool) {
	if o == nil || IsNil(o.BulkValue) {
		return nil, false
	}
	return o.BulkValue, true
}

// HasBulkValue returns a boolean if a field has been set.
func (o *Price) HasBulkValue() bool {
	if o != nil && !IsNil(o.BulkValue) {
		return true
	}

	return false
}

// SetBulkValue gets a reference to the given float64 and assigns it to the BulkValue field.
func (o *Price) SetBulkValue(v float64) {
	o.BulkValue = &v
}

// GetBulkOrder returns the BulkOrder field value if set, zero value otherwise.
func (o *Price) GetBulkOrder() int64 {
	if o == nil || IsNil(o.BulkOrder) {
		var ret int64
		return ret
	}
	return *o.BulkOrder
}

// GetBulkOrderOk returns a tuple with the BulkOrder field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Price) GetBulkOrderOk() (*int64, bool) {
	if o == nil || IsNil(o.BulkOrder) {
		return nil, false
	}
	return o.BulkOrder, true
}

// HasBulkOrder returns a boolean if a field has been set.
func (o *Price) HasBulkOrder() bool {
	if o != nil && !IsNil(o.BulkOrder) {
		return true
	}

	return false
}

// SetBulkOrder gets a reference to the given int64 and assigns it to the BulkOrder field.
func (o *Price) SetBulkOrder(v int64) {
	o.BulkOrder = &v
}

// GetMinValue returns the MinValue field value if set, zero value otherwise.
func (o *Price) GetMinValue() float64 {
	if o == nil || IsNil(o.MinValue) {
		var ret float64
		return ret
	}
	return *o.MinValue
}

// GetMinValueOk returns a tuple with the MinValue field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Price) GetMinValueOk() (*float64, bool) {
	if o == nil || IsNil(o.MinValue) {
		return nil, false
	}
	return o.MinValue, true
}

// HasMinValue returns a boolean if a field has been set.
func (o *Price) HasMinValue() bool {
	if o != nil && !IsNil(o.MinValue) {
		return true
	}

	return false
}

// SetMinValue gets a reference to the given float64 and assigns it to the MinValue field.
func (o *Price) SetMinValue(v float64) {
	o.MinValue = &v
}

// GetMaxValue returns the MaxValue field value if set, zero value otherwise.
func (o *Price) GetMaxValue() float64 {
	if o == nil || IsNil(o.MaxValue) {
		var ret float64
		return ret
	}
	return *o.MaxValue
}

// GetMaxValueOk returns a tuple with the MaxValue field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Price) GetMaxValueOk() (*float64, bool) {
	if o == nil || IsNil(o.MaxValue) {
		return nil, false
	}
	return o.MaxValue, true
}

// HasMaxValue returns a boolean if a field has been set.
func (o *Price) HasMaxValue() bool {
	if o != nil && !IsNil(o.MaxValue) {
		return true
	}

	return false
}

// SetMaxValue gets a reference to the given float64 and assigns it to the MaxValue field.
func (o *Price) SetMaxValue(v float64) {
	o.MaxValue = &v
}

// GetOriginalMinValue returns the OriginalMinValue field value if set, zero value otherwise.
func (o *Price) GetOriginalMinValue() float64 {
	if o == nil || IsNil(o.OriginalMinValue) {
		var ret float64
		return ret
	}
	return *o.OriginalMinValue
}

// GetOriginalMinValueOk returns a tuple with the OriginalMinValue field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Price) GetOriginalMinValueOk() (*float64, bool) {
	if o == nil || IsNil(o.OriginalMinValue) {
		return nil, false
	}
	return o.OriginalMinValue, true
}

// HasOriginalMinValue returns a boolean if a field has been set.
func (o *Price) HasOriginalMinValue() bool {
	if o != nil && !IsNil(o.OriginalMinValue) {
		return true
	}

	return false
}

// SetOriginalMinValue gets a reference to the given float64 and assigns it to the OriginalMinValue field.
func (o *Price) SetOriginalMinValue(v float64) {
	o.OriginalMinValue = &v
}

// GetOriginalMaxValue returns the OriginalMaxValue field value if set, zero value otherwise.
func (o *Price) GetOriginalMaxValue() float64 {
	if o == nil || IsNil(o.OriginalMaxValue) {
		var ret float64
		return ret
	}
	return *o.OriginalMaxValue
}

// GetOriginalMaxValueOk returns a tuple with the OriginalMaxValue field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Price) GetOriginalMaxValueOk() (*float64, bool) {
	if o == nil || IsNil(o.OriginalMaxValue) {
		return nil, false
	}
	return o.OriginalMaxValue, true
}

// HasOriginalMaxValue returns a boolean if a field has been set.
func (o *Price) HasOriginalMaxValue() bool {
	if o != nil && !IsNil(o.OriginalMaxValue) {
		return true
	}

	return false
}

// SetOriginalMaxValue gets a reference to the given float64 and assigns it to the OriginalMaxValue field.
func (o *Price) SetOriginalMaxValue(v float64) {
	o.OriginalMaxValue = &v
}

// GetCurrency returns the Currency field value if set, zero value otherwise.
func (o *Price) GetCurrency() string {
	if o == nil || IsNil(o.Currency) {
		var ret string
		return ret
	}
	return *o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Price) GetCurrencyOk() (*string, bool) {
	if o == nil || IsNil(o.Currency) {
		return nil, false
	}
	return o.Currency, true
}

// HasCurrency returns a boolean if a field has been set.
func (o *Price) HasCurrency() bool {
	if o != nil && !IsNil(o.Currency) {
		return true
	}

	return false
}

// SetCurrency gets a reference to the given string and assigns it to the Currency field.
func (o *Price) SetCurrency(v string) {
	o.Currency = &v
}

// GetCountry returns the Country field value if set, zero value otherwise.
func (o *Price) GetCountry() string {
	if o == nil || IsNil(o.Country) {
		var ret string
		return ret
	}
	return *o.Country
}

// GetCountryOk returns a tuple with the Country field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Price) GetCountryOk() (*string, bool) {
	if o == nil || IsNil(o.Country) {
		return nil, false
	}
	return o.Country, true
}

// HasCountry returns a boolean if a field has been set.
func (o *Price) HasCountry() bool {
	if o != nil && !IsNil(o.Country) {
		return true
	}

	return false
}

// SetCountry gets a reference to the given string and assigns it to the Country field.
func (o *Price) SetCountry(v string) {
	o.Country = &v
}

func (o Price) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Price) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.SkuId) {
		toSerialize["sku_id"] = o.SkuId
	}
	if !IsNil(o.SkuIdInt) {
		toSerialize["sku_id_int"] = o.SkuIdInt
	}
	if !IsNil(o.BulkValue) {
		toSerialize["bulk_value"] = o.BulkValue
	}
	if !IsNil(o.BulkOrder) {
		toSerialize["bulk_order"] = o.BulkOrder
	}
	if !IsNil(o.MinValue) {
		toSerialize["min_value"] = o.MinValue
	}
	if !IsNil(o.MaxValue) {
		toSerialize["max_value"] = o.MaxValue
	}
	if !IsNil(o.OriginalMinValue) {
		toSerialize["original_min_value"] = o.OriginalMinValue
	}
	if !IsNil(o.OriginalMaxValue) {
		toSerialize["original_max_value"] = o.OriginalMaxValue
	}
	if !IsNil(o.Currency) {
		toSerialize["currency"] = o.Currency
	}
	if !IsNil(o.Country) {
		toSerialize["country"] = o.Country
	}
	return toSerialize, nil
}

type NullablePrice struct {
	value *Price
	isSet bool
}

func (v NullablePrice) Get() *Price {
	return v.value
}

func (v *NullablePrice) Set(val *Price) {
	v.value = val
	v.isSet = true
}

func (v NullablePrice) IsSet() bool {
	return v.isSet
}

func (v *NullablePrice) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePrice(val *Price) *NullablePrice {
	return &NullablePrice{value: val, isSet: true}
}

func (v NullablePrice) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePrice) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


