/*
AliExpress Parser API

Real-time AliExpress data parser covering products, product reviews, sellers, store coupons, a seller's product catalog, and product search by text or image. Products: pricing, stock status, shipping options, seller information, product configurations (SKUs), and more - scoped to a specific country and currency. Reviews: customer ratings and feedback for a product. Sellers: full store profile with ratings, feedback, and categories. Coupons: active seller coupon codes with discounts, thresholds, budgets, and expiry. Seller products: a store's product catalog, paginated and best-selling first. Search: find products by keyword or by uploading an image, returning paginated product results with their categories. 

API version: 2.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aligate

import (
	"encoding/json"
)

// checks if the CouponSettings type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CouponSettings{}

// CouponSettings Echo of the request parameters
type CouponSettings struct {
	// Seller admin seq (resolved from store_num when not provided)
	SellerId *int32 `json:"seller_id,omitempty"`
	StoreNum *int32 `json:"store_num,omitempty"`
	Country *string `json:"country,omitempty"`
	Currency *string `json:"currency,omitempty"`
}

// NewCouponSettings instantiates a new CouponSettings object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCouponSettings() *CouponSettings {
	this := CouponSettings{}
	return &this
}

// NewCouponSettingsWithDefaults instantiates a new CouponSettings object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCouponSettingsWithDefaults() *CouponSettings {
	this := CouponSettings{}
	return &this
}

// GetSellerId returns the SellerId field value if set, zero value otherwise.
func (o *CouponSettings) GetSellerId() int32 {
	if o == nil || IsNil(o.SellerId) {
		var ret int32
		return ret
	}
	return *o.SellerId
}

// GetSellerIdOk returns a tuple with the SellerId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CouponSettings) GetSellerIdOk() (*int32, bool) {
	if o == nil || IsNil(o.SellerId) {
		return nil, false
	}
	return o.SellerId, true
}

// HasSellerId returns a boolean if a field has been set.
func (o *CouponSettings) HasSellerId() bool {
	if o != nil && !IsNil(o.SellerId) {
		return true
	}

	return false
}

// SetSellerId gets a reference to the given int32 and assigns it to the SellerId field.
func (o *CouponSettings) SetSellerId(v int32) {
	o.SellerId = &v
}

// GetStoreNum returns the StoreNum field value if set, zero value otherwise.
func (o *CouponSettings) GetStoreNum() int32 {
	if o == nil || IsNil(o.StoreNum) {
		var ret int32
		return ret
	}
	return *o.StoreNum
}

// GetStoreNumOk returns a tuple with the StoreNum field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CouponSettings) GetStoreNumOk() (*int32, bool) {
	if o == nil || IsNil(o.StoreNum) {
		return nil, false
	}
	return o.StoreNum, true
}

// HasStoreNum returns a boolean if a field has been set.
func (o *CouponSettings) HasStoreNum() bool {
	if o != nil && !IsNil(o.StoreNum) {
		return true
	}

	return false
}

// SetStoreNum gets a reference to the given int32 and assigns it to the StoreNum field.
func (o *CouponSettings) SetStoreNum(v int32) {
	o.StoreNum = &v
}

// GetCountry returns the Country field value if set, zero value otherwise.
func (o *CouponSettings) GetCountry() string {
	if o == nil || IsNil(o.Country) {
		var ret string
		return ret
	}
	return *o.Country
}

// GetCountryOk returns a tuple with the Country field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CouponSettings) GetCountryOk() (*string, bool) {
	if o == nil || IsNil(o.Country) {
		return nil, false
	}
	return o.Country, true
}

// HasCountry returns a boolean if a field has been set.
func (o *CouponSettings) HasCountry() bool {
	if o != nil && !IsNil(o.Country) {
		return true
	}

	return false
}

// SetCountry gets a reference to the given string and assigns it to the Country field.
func (o *CouponSettings) SetCountry(v string) {
	o.Country = &v
}

// GetCurrency returns the Currency field value if set, zero value otherwise.
func (o *CouponSettings) GetCurrency() string {
	if o == nil || IsNil(o.Currency) {
		var ret string
		return ret
	}
	return *o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CouponSettings) GetCurrencyOk() (*string, bool) {
	if o == nil || IsNil(o.Currency) {
		return nil, false
	}
	return o.Currency, true
}

// HasCurrency returns a boolean if a field has been set.
func (o *CouponSettings) HasCurrency() bool {
	if o != nil && !IsNil(o.Currency) {
		return true
	}

	return false
}

// SetCurrency gets a reference to the given string and assigns it to the Currency field.
func (o *CouponSettings) SetCurrency(v string) {
	o.Currency = &v
}

func (o CouponSettings) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CouponSettings) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.SellerId) {
		toSerialize["seller_id"] = o.SellerId
	}
	if !IsNil(o.StoreNum) {
		toSerialize["store_num"] = o.StoreNum
	}
	if !IsNil(o.Country) {
		toSerialize["country"] = o.Country
	}
	if !IsNil(o.Currency) {
		toSerialize["currency"] = o.Currency
	}
	return toSerialize, nil
}

type NullableCouponSettings struct {
	value *CouponSettings
	isSet bool
}

func (v NullableCouponSettings) Get() *CouponSettings {
	return v.value
}

func (v *NullableCouponSettings) Set(val *CouponSettings) {
	v.value = val
	v.isSet = true
}

func (v NullableCouponSettings) IsSet() bool {
	return v.isSet
}

func (v *NullableCouponSettings) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCouponSettings(val *CouponSettings) *NullableCouponSettings {
	return &NullableCouponSettings{value: val, isSet: true}
}

func (v NullableCouponSettings) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCouponSettings) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


