/*
AliExpress Parser API

Real-time AliExpress data parser covering products, product reviews, sellers, store coupons, a seller's product catalog, and product search by text or image. Products: pricing, stock status, shipping options, seller information, product configurations (SKUs), and more - scoped to a specific country and currency. Reviews: customer ratings and feedback for a product. Sellers: full store profile with ratings, feedback, and categories. Coupons: active seller coupon codes with discounts, thresholds, budgets, and expiry. Seller products: a store's product catalog, paginated and best-selling first. Search: find products by keyword or by uploading an image, returning paginated product results with their categories. 

API version: 2.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aligate

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ImageSearchRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ImageSearchRequest{}

// ImageSearchRequest Image-search request body
type ImageSearchRequest struct {
	// Base64-encoded image bytes to search by.
	Image64 string `json:"image64"`
	// Country code (ISO 3166-1 alpha-2) used for pricing and shipping eligibility.
	Country string `json:"country"`
	// Currency code (ISO 4217) for the returned prices.
	Currency string `json:"currency"`
	// Response language locale.
	Locale *string `json:"locale,omitempty"`
	// Page number of results to return (starts at 1).
	Page *int32 `json:"page,omitempty"`
}

type _ImageSearchRequest ImageSearchRequest

// NewImageSearchRequest instantiates a new ImageSearchRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewImageSearchRequest(image64 string, country string, currency string) *ImageSearchRequest {
	this := ImageSearchRequest{}
	this.Image64 = image64
	this.Country = country
	this.Currency = currency
	var locale string = "en_US"
	this.Locale = &locale
	var page int32 = 1
	this.Page = &page
	return &this
}

// NewImageSearchRequestWithDefaults instantiates a new ImageSearchRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewImageSearchRequestWithDefaults() *ImageSearchRequest {
	this := ImageSearchRequest{}
	var locale string = "en_US"
	this.Locale = &locale
	var page int32 = 1
	this.Page = &page
	return &this
}

// GetImage64 returns the Image64 field value
func (o *ImageSearchRequest) GetImage64() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Image64
}

// GetImage64Ok returns a tuple with the Image64 field value
// and a boolean to check if the value has been set.
func (o *ImageSearchRequest) GetImage64Ok() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Image64, true
}

// SetImage64 sets field value
func (o *ImageSearchRequest) SetImage64(v string) {
	o.Image64 = v
}

// GetCountry returns the Country field value
func (o *ImageSearchRequest) GetCountry() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Country
}

// GetCountryOk returns a tuple with the Country field value
// and a boolean to check if the value has been set.
func (o *ImageSearchRequest) GetCountryOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Country, true
}

// SetCountry sets field value
func (o *ImageSearchRequest) SetCountry(v string) {
	o.Country = v
}

// GetCurrency returns the Currency field value
func (o *ImageSearchRequest) GetCurrency() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value
// and a boolean to check if the value has been set.
func (o *ImageSearchRequest) GetCurrencyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Currency, true
}

// SetCurrency sets field value
func (o *ImageSearchRequest) SetCurrency(v string) {
	o.Currency = v
}

// GetLocale returns the Locale field value if set, zero value otherwise.
func (o *ImageSearchRequest) GetLocale() string {
	if o == nil || IsNil(o.Locale) {
		var ret string
		return ret
	}
	return *o.Locale
}

// GetLocaleOk returns a tuple with the Locale field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ImageSearchRequest) GetLocaleOk() (*string, bool) {
	if o == nil || IsNil(o.Locale) {
		return nil, false
	}
	return o.Locale, true
}

// HasLocale returns a boolean if a field has been set.
func (o *ImageSearchRequest) HasLocale() bool {
	if o != nil && !IsNil(o.Locale) {
		return true
	}

	return false
}

// SetLocale gets a reference to the given string and assigns it to the Locale field.
func (o *ImageSearchRequest) SetLocale(v string) {
	o.Locale = &v
}

// GetPage returns the Page field value if set, zero value otherwise.
func (o *ImageSearchRequest) GetPage() int32 {
	if o == nil || IsNil(o.Page) {
		var ret int32
		return ret
	}
	return *o.Page
}

// GetPageOk returns a tuple with the Page field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ImageSearchRequest) GetPageOk() (*int32, bool) {
	if o == nil || IsNil(o.Page) {
		return nil, false
	}
	return o.Page, true
}

// HasPage returns a boolean if a field has been set.
func (o *ImageSearchRequest) HasPage() bool {
	if o != nil && !IsNil(o.Page) {
		return true
	}

	return false
}

// SetPage gets a reference to the given int32 and assigns it to the Page field.
func (o *ImageSearchRequest) SetPage(v int32) {
	o.Page = &v
}

func (o ImageSearchRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ImageSearchRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["image64"] = o.Image64
	toSerialize["country"] = o.Country
	toSerialize["currency"] = o.Currency
	if !IsNil(o.Locale) {
		toSerialize["locale"] = o.Locale
	}
	if !IsNil(o.Page) {
		toSerialize["page"] = o.Page
	}
	return toSerialize, nil
}

func (o *ImageSearchRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"image64",
		"country",
		"currency",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varImageSearchRequest := _ImageSearchRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varImageSearchRequest)

	if err != nil {
		return err
	}

	*o = ImageSearchRequest(varImageSearchRequest)

	return err
}

type NullableImageSearchRequest struct {
	value *ImageSearchRequest
	isSet bool
}

func (v NullableImageSearchRequest) Get() *ImageSearchRequest {
	return v.value
}

func (v *NullableImageSearchRequest) Set(val *ImageSearchRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableImageSearchRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableImageSearchRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableImageSearchRequest(val *ImageSearchRequest) *NullableImageSearchRequest {
	return &NullableImageSearchRequest{value: val, isSet: true}
}

func (v NullableImageSearchRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableImageSearchRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


