/*
AliExpress Parser API

Real-time AliExpress data parser covering products, product reviews, sellers, store coupons, a seller's product catalog, and product search by text or image. Products: pricing, stock status, shipping options, seller information, product configurations (SKUs), and more - scoped to a specific country and currency. Reviews: customer ratings and feedback for a product. Sellers: full store profile with ratings, feedback, and categories. Coupons: active seller coupon codes with discounts, thresholds, budgets, and expiry. Seller products: a store's product catalog, paginated and best-selling first. Search: find products by keyword or by uploading an image, returning paginated product results with their categories. 

API version: 2.1.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aligate

import (
	"encoding/json"
)

// checks if the ReviewsParseResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ReviewsParseResponse{}

// ReviewsParseResponse Top-level response envelope returned by the gateway for review requests
type ReviewsParseResponse struct {
	Meta *ReviewsMeta `json:"meta,omitempty"`
	Settings *ReviewsSettings `json:"settings,omitempty"`
	Item *ReviewsResult `json:"item,omitempty"`
}

// NewReviewsParseResponse instantiates a new ReviewsParseResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewReviewsParseResponse() *ReviewsParseResponse {
	this := ReviewsParseResponse{}
	return &this
}

// NewReviewsParseResponseWithDefaults instantiates a new ReviewsParseResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewReviewsParseResponseWithDefaults() *ReviewsParseResponse {
	this := ReviewsParseResponse{}
	return &this
}

// GetMeta returns the Meta field value if set, zero value otherwise.
func (o *ReviewsParseResponse) GetMeta() ReviewsMeta {
	if o == nil || IsNil(o.Meta) {
		var ret ReviewsMeta
		return ret
	}
	return *o.Meta
}

// GetMetaOk returns a tuple with the Meta field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReviewsParseResponse) GetMetaOk() (*ReviewsMeta, bool) {
	if o == nil || IsNil(o.Meta) {
		return nil, false
	}
	return o.Meta, true
}

// HasMeta returns a boolean if a field has been set.
func (o *ReviewsParseResponse) HasMeta() bool {
	if o != nil && !IsNil(o.Meta) {
		return true
	}

	return false
}

// SetMeta gets a reference to the given ReviewsMeta and assigns it to the Meta field.
func (o *ReviewsParseResponse) SetMeta(v ReviewsMeta) {
	o.Meta = &v
}

// GetSettings returns the Settings field value if set, zero value otherwise.
func (o *ReviewsParseResponse) GetSettings() ReviewsSettings {
	if o == nil || IsNil(o.Settings) {
		var ret ReviewsSettings
		return ret
	}
	return *o.Settings
}

// GetSettingsOk returns a tuple with the Settings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReviewsParseResponse) GetSettingsOk() (*ReviewsSettings, bool) {
	if o == nil || IsNil(o.Settings) {
		return nil, false
	}
	return o.Settings, true
}

// HasSettings returns a boolean if a field has been set.
func (o *ReviewsParseResponse) HasSettings() bool {
	if o != nil && !IsNil(o.Settings) {
		return true
	}

	return false
}

// SetSettings gets a reference to the given ReviewsSettings and assigns it to the Settings field.
func (o *ReviewsParseResponse) SetSettings(v ReviewsSettings) {
	o.Settings = &v
}

// GetItem returns the Item field value if set, zero value otherwise.
func (o *ReviewsParseResponse) GetItem() ReviewsResult {
	if o == nil || IsNil(o.Item) {
		var ret ReviewsResult
		return ret
	}
	return *o.Item
}

// GetItemOk returns a tuple with the Item field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReviewsParseResponse) GetItemOk() (*ReviewsResult, bool) {
	if o == nil || IsNil(o.Item) {
		return nil, false
	}
	return o.Item, true
}

// HasItem returns a boolean if a field has been set.
func (o *ReviewsParseResponse) HasItem() bool {
	if o != nil && !IsNil(o.Item) {
		return true
	}

	return false
}

// SetItem gets a reference to the given ReviewsResult and assigns it to the Item field.
func (o *ReviewsParseResponse) SetItem(v ReviewsResult) {
	o.Item = &v
}

func (o ReviewsParseResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ReviewsParseResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Meta) {
		toSerialize["meta"] = o.Meta
	}
	if !IsNil(o.Settings) {
		toSerialize["settings"] = o.Settings
	}
	if !IsNil(o.Item) {
		toSerialize["item"] = o.Item
	}
	return toSerialize, nil
}

type NullableReviewsParseResponse struct {
	value *ReviewsParseResponse
	isSet bool
}

func (v NullableReviewsParseResponse) Get() *ReviewsParseResponse {
	return v.value
}

func (v *NullableReviewsParseResponse) Set(val *ReviewsParseResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableReviewsParseResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableReviewsParseResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableReviewsParseResponse(val *ReviewsParseResponse) *NullableReviewsParseResponse {
	return &NullableReviewsParseResponse{value: val, isSet: true}
}

func (v NullableReviewsParseResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableReviewsParseResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


