/*
AliExpress Parser API

Real-time AliExpress data parser covering products, product reviews, sellers, store coupons, a seller's product catalog, and product search by text or image. Products: pricing, stock status, shipping options, seller information, product configurations (SKUs), and more - scoped to a specific country and currency. Reviews: customer ratings and feedback for a product. Sellers: full store profile with ratings, feedback, and categories. Coupons: active seller coupon codes with discounts, thresholds, budgets, and expiry. Seller products: a store's product catalog, paginated and best-selling first. Search: find products by keyword or by uploading an image, returning paginated product results with their categories. 

API version: 2.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aligate

import (
	"encoding/json"
)

// checks if the RatingBreakdown type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RatingBreakdown{}

// RatingBreakdown Per-star and sentiment counts for the product
type RatingBreakdown struct {
	FiveStars *int32 `json:"five_stars,omitempty"`
	FourStars *int32 `json:"four_stars,omitempty"`
	ThreeStars *int32 `json:"three_stars,omitempty"`
	TwoStars *int32 `json:"two_stars,omitempty"`
	OneStar *int32 `json:"one_star,omitempty"`
	TotalPositive *int32 `json:"total_positive,omitempty"`
	TotalNegative *int32 `json:"total_negative,omitempty"`
	TotalNeutral *int32 `json:"total_neutral,omitempty"`
}

// NewRatingBreakdown instantiates a new RatingBreakdown object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRatingBreakdown() *RatingBreakdown {
	this := RatingBreakdown{}
	return &this
}

// NewRatingBreakdownWithDefaults instantiates a new RatingBreakdown object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRatingBreakdownWithDefaults() *RatingBreakdown {
	this := RatingBreakdown{}
	return &this
}

// GetFiveStars returns the FiveStars field value if set, zero value otherwise.
func (o *RatingBreakdown) GetFiveStars() int32 {
	if o == nil || IsNil(o.FiveStars) {
		var ret int32
		return ret
	}
	return *o.FiveStars
}

// GetFiveStarsOk returns a tuple with the FiveStars field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RatingBreakdown) GetFiveStarsOk() (*int32, bool) {
	if o == nil || IsNil(o.FiveStars) {
		return nil, false
	}
	return o.FiveStars, true
}

// HasFiveStars returns a boolean if a field has been set.
func (o *RatingBreakdown) HasFiveStars() bool {
	if o != nil && !IsNil(o.FiveStars) {
		return true
	}

	return false
}

// SetFiveStars gets a reference to the given int32 and assigns it to the FiveStars field.
func (o *RatingBreakdown) SetFiveStars(v int32) {
	o.FiveStars = &v
}

// GetFourStars returns the FourStars field value if set, zero value otherwise.
func (o *RatingBreakdown) GetFourStars() int32 {
	if o == nil || IsNil(o.FourStars) {
		var ret int32
		return ret
	}
	return *o.FourStars
}

// GetFourStarsOk returns a tuple with the FourStars field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RatingBreakdown) GetFourStarsOk() (*int32, bool) {
	if o == nil || IsNil(o.FourStars) {
		return nil, false
	}
	return o.FourStars, true
}

// HasFourStars returns a boolean if a field has been set.
func (o *RatingBreakdown) HasFourStars() bool {
	if o != nil && !IsNil(o.FourStars) {
		return true
	}

	return false
}

// SetFourStars gets a reference to the given int32 and assigns it to the FourStars field.
func (o *RatingBreakdown) SetFourStars(v int32) {
	o.FourStars = &v
}

// GetThreeStars returns the ThreeStars field value if set, zero value otherwise.
func (o *RatingBreakdown) GetThreeStars() int32 {
	if o == nil || IsNil(o.ThreeStars) {
		var ret int32
		return ret
	}
	return *o.ThreeStars
}

// GetThreeStarsOk returns a tuple with the ThreeStars field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RatingBreakdown) GetThreeStarsOk() (*int32, bool) {
	if o == nil || IsNil(o.ThreeStars) {
		return nil, false
	}
	return o.ThreeStars, true
}

// HasThreeStars returns a boolean if a field has been set.
func (o *RatingBreakdown) HasThreeStars() bool {
	if o != nil && !IsNil(o.ThreeStars) {
		return true
	}

	return false
}

// SetThreeStars gets a reference to the given int32 and assigns it to the ThreeStars field.
func (o *RatingBreakdown) SetThreeStars(v int32) {
	o.ThreeStars = &v
}

// GetTwoStars returns the TwoStars field value if set, zero value otherwise.
func (o *RatingBreakdown) GetTwoStars() int32 {
	if o == nil || IsNil(o.TwoStars) {
		var ret int32
		return ret
	}
	return *o.TwoStars
}

// GetTwoStarsOk returns a tuple with the TwoStars field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RatingBreakdown) GetTwoStarsOk() (*int32, bool) {
	if o == nil || IsNil(o.TwoStars) {
		return nil, false
	}
	return o.TwoStars, true
}

// HasTwoStars returns a boolean if a field has been set.
func (o *RatingBreakdown) HasTwoStars() bool {
	if o != nil && !IsNil(o.TwoStars) {
		return true
	}

	return false
}

// SetTwoStars gets a reference to the given int32 and assigns it to the TwoStars field.
func (o *RatingBreakdown) SetTwoStars(v int32) {
	o.TwoStars = &v
}

// GetOneStar returns the OneStar field value if set, zero value otherwise.
func (o *RatingBreakdown) GetOneStar() int32 {
	if o == nil || IsNil(o.OneStar) {
		var ret int32
		return ret
	}
	return *o.OneStar
}

// GetOneStarOk returns a tuple with the OneStar field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RatingBreakdown) GetOneStarOk() (*int32, bool) {
	if o == nil || IsNil(o.OneStar) {
		return nil, false
	}
	return o.OneStar, true
}

// HasOneStar returns a boolean if a field has been set.
func (o *RatingBreakdown) HasOneStar() bool {
	if o != nil && !IsNil(o.OneStar) {
		return true
	}

	return false
}

// SetOneStar gets a reference to the given int32 and assigns it to the OneStar field.
func (o *RatingBreakdown) SetOneStar(v int32) {
	o.OneStar = &v
}

// GetTotalPositive returns the TotalPositive field value if set, zero value otherwise.
func (o *RatingBreakdown) GetTotalPositive() int32 {
	if o == nil || IsNil(o.TotalPositive) {
		var ret int32
		return ret
	}
	return *o.TotalPositive
}

// GetTotalPositiveOk returns a tuple with the TotalPositive field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RatingBreakdown) GetTotalPositiveOk() (*int32, bool) {
	if o == nil || IsNil(o.TotalPositive) {
		return nil, false
	}
	return o.TotalPositive, true
}

// HasTotalPositive returns a boolean if a field has been set.
func (o *RatingBreakdown) HasTotalPositive() bool {
	if o != nil && !IsNil(o.TotalPositive) {
		return true
	}

	return false
}

// SetTotalPositive gets a reference to the given int32 and assigns it to the TotalPositive field.
func (o *RatingBreakdown) SetTotalPositive(v int32) {
	o.TotalPositive = &v
}

// GetTotalNegative returns the TotalNegative field value if set, zero value otherwise.
func (o *RatingBreakdown) GetTotalNegative() int32 {
	if o == nil || IsNil(o.TotalNegative) {
		var ret int32
		return ret
	}
	return *o.TotalNegative
}

// GetTotalNegativeOk returns a tuple with the TotalNegative field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RatingBreakdown) GetTotalNegativeOk() (*int32, bool) {
	if o == nil || IsNil(o.TotalNegative) {
		return nil, false
	}
	return o.TotalNegative, true
}

// HasTotalNegative returns a boolean if a field has been set.
func (o *RatingBreakdown) HasTotalNegative() bool {
	if o != nil && !IsNil(o.TotalNegative) {
		return true
	}

	return false
}

// SetTotalNegative gets a reference to the given int32 and assigns it to the TotalNegative field.
func (o *RatingBreakdown) SetTotalNegative(v int32) {
	o.TotalNegative = &v
}

// GetTotalNeutral returns the TotalNeutral field value if set, zero value otherwise.
func (o *RatingBreakdown) GetTotalNeutral() int32 {
	if o == nil || IsNil(o.TotalNeutral) {
		var ret int32
		return ret
	}
	return *o.TotalNeutral
}

// GetTotalNeutralOk returns a tuple with the TotalNeutral field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RatingBreakdown) GetTotalNeutralOk() (*int32, bool) {
	if o == nil || IsNil(o.TotalNeutral) {
		return nil, false
	}
	return o.TotalNeutral, true
}

// HasTotalNeutral returns a boolean if a field has been set.
func (o *RatingBreakdown) HasTotalNeutral() bool {
	if o != nil && !IsNil(o.TotalNeutral) {
		return true
	}

	return false
}

// SetTotalNeutral gets a reference to the given int32 and assigns it to the TotalNeutral field.
func (o *RatingBreakdown) SetTotalNeutral(v int32) {
	o.TotalNeutral = &v
}

func (o RatingBreakdown) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RatingBreakdown) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.FiveStars) {
		toSerialize["five_stars"] = o.FiveStars
	}
	if !IsNil(o.FourStars) {
		toSerialize["four_stars"] = o.FourStars
	}
	if !IsNil(o.ThreeStars) {
		toSerialize["three_stars"] = o.ThreeStars
	}
	if !IsNil(o.TwoStars) {
		toSerialize["two_stars"] = o.TwoStars
	}
	if !IsNil(o.OneStar) {
		toSerialize["one_star"] = o.OneStar
	}
	if !IsNil(o.TotalPositive) {
		toSerialize["total_positive"] = o.TotalPositive
	}
	if !IsNil(o.TotalNegative) {
		toSerialize["total_negative"] = o.TotalNegative
	}
	if !IsNil(o.TotalNeutral) {
		toSerialize["total_neutral"] = o.TotalNeutral
	}
	return toSerialize, nil
}

type NullableRatingBreakdown struct {
	value *RatingBreakdown
	isSet bool
}

func (v NullableRatingBreakdown) Get() *RatingBreakdown {
	return v.value
}

func (v *NullableRatingBreakdown) Set(val *RatingBreakdown) {
	v.value = val
	v.isSet = true
}

func (v NullableRatingBreakdown) IsSet() bool {
	return v.isSet
}

func (v *NullableRatingBreakdown) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRatingBreakdown(val *RatingBreakdown) *NullableRatingBreakdown {
	return &NullableRatingBreakdown{value: val, isSet: true}
}

func (v NullableRatingBreakdown) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRatingBreakdown) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


