/*
AliExpress Parser API

Real-time AliExpress data parser covering products, product reviews, sellers, store coupons, a seller's product catalog, and product search by text or image. Products: pricing, stock status, shipping options, seller information, product configurations (SKUs), and more - scoped to a specific country and currency. Reviews: customer ratings and feedback for a product. Sellers: full store profile with ratings, feedback, and categories. Coupons: active seller coupon codes with discounts, thresholds, budgets, and expiry. Seller products: a store's product catalog, paginated and best-selling first. Search: find products by keyword or by uploading an image, returning paginated product results with their categories. 

API version: 2.1.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aligate

import (
	"encoding/json"
)

// checks if the Review type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Review{}

// Review A single buyer review
type Review struct {
	ReviewId *int64 `json:"review_id,omitempty"`
	Buyer *ReviewBuyer `json:"buyer,omitempty"`
	Anonymous *bool `json:"anonymous,omitempty"`
	// Review rating on a 0-5 scale
	Rating *float64 `json:"rating,omitempty"`
	// Buyer country code
	Country *string `json:"country,omitempty"`
	// Number of helpful votes
	Upvotes *int32 `json:"upvotes,omitempty"`
	// Number of unhelpful votes
	Downvotes *int32 `json:"downvotes,omitempty"`
	// Review date as shown on AliExpress
	Date *string `json:"date,omitempty"`
	// Logistics/shipping method used for the order
	ShippingMethod *string `json:"shipping_method,omitempty"`
	// The purchased SKU/variant (e.g. color, size)
	Variant *string `json:"variant,omitempty"`
	Labels []ReviewLabel `json:"labels,omitempty"`
	Images []string `json:"images,omitempty"`
	Comment *ReviewContent `json:"comment,omitempty"`
	AdditionalComment *ReviewContent `json:"additional_comment,omitempty"`
	SellerReply *ReviewContent `json:"seller_reply,omitempty"`
	AdditionalSellerReply *ReviewContent `json:"additional_seller_reply,omitempty"`
}

// NewReview instantiates a new Review object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewReview() *Review {
	this := Review{}
	return &this
}

// NewReviewWithDefaults instantiates a new Review object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewReviewWithDefaults() *Review {
	this := Review{}
	return &this
}

// GetReviewId returns the ReviewId field value if set, zero value otherwise.
func (o *Review) GetReviewId() int64 {
	if o == nil || IsNil(o.ReviewId) {
		var ret int64
		return ret
	}
	return *o.ReviewId
}

// GetReviewIdOk returns a tuple with the ReviewId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Review) GetReviewIdOk() (*int64, bool) {
	if o == nil || IsNil(o.ReviewId) {
		return nil, false
	}
	return o.ReviewId, true
}

// HasReviewId returns a boolean if a field has been set.
func (o *Review) HasReviewId() bool {
	if o != nil && !IsNil(o.ReviewId) {
		return true
	}

	return false
}

// SetReviewId gets a reference to the given int64 and assigns it to the ReviewId field.
func (o *Review) SetReviewId(v int64) {
	o.ReviewId = &v
}

// GetBuyer returns the Buyer field value if set, zero value otherwise.
func (o *Review) GetBuyer() ReviewBuyer {
	if o == nil || IsNil(o.Buyer) {
		var ret ReviewBuyer
		return ret
	}
	return *o.Buyer
}

// GetBuyerOk returns a tuple with the Buyer field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Review) GetBuyerOk() (*ReviewBuyer, bool) {
	if o == nil || IsNil(o.Buyer) {
		return nil, false
	}
	return o.Buyer, true
}

// HasBuyer returns a boolean if a field has been set.
func (o *Review) HasBuyer() bool {
	if o != nil && !IsNil(o.Buyer) {
		return true
	}

	return false
}

// SetBuyer gets a reference to the given ReviewBuyer and assigns it to the Buyer field.
func (o *Review) SetBuyer(v ReviewBuyer) {
	o.Buyer = &v
}

// GetAnonymous returns the Anonymous field value if set, zero value otherwise.
func (o *Review) GetAnonymous() bool {
	if o == nil || IsNil(o.Anonymous) {
		var ret bool
		return ret
	}
	return *o.Anonymous
}

// GetAnonymousOk returns a tuple with the Anonymous field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Review) GetAnonymousOk() (*bool, bool) {
	if o == nil || IsNil(o.Anonymous) {
		return nil, false
	}
	return o.Anonymous, true
}

// HasAnonymous returns a boolean if a field has been set.
func (o *Review) HasAnonymous() bool {
	if o != nil && !IsNil(o.Anonymous) {
		return true
	}

	return false
}

// SetAnonymous gets a reference to the given bool and assigns it to the Anonymous field.
func (o *Review) SetAnonymous(v bool) {
	o.Anonymous = &v
}

// GetRating returns the Rating field value if set, zero value otherwise.
func (o *Review) GetRating() float64 {
	if o == nil || IsNil(o.Rating) {
		var ret float64
		return ret
	}
	return *o.Rating
}

// GetRatingOk returns a tuple with the Rating field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Review) GetRatingOk() (*float64, bool) {
	if o == nil || IsNil(o.Rating) {
		return nil, false
	}
	return o.Rating, true
}

// HasRating returns a boolean if a field has been set.
func (o *Review) HasRating() bool {
	if o != nil && !IsNil(o.Rating) {
		return true
	}

	return false
}

// SetRating gets a reference to the given float64 and assigns it to the Rating field.
func (o *Review) SetRating(v float64) {
	o.Rating = &v
}

// GetCountry returns the Country field value if set, zero value otherwise.
func (o *Review) GetCountry() string {
	if o == nil || IsNil(o.Country) {
		var ret string
		return ret
	}
	return *o.Country
}

// GetCountryOk returns a tuple with the Country field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Review) GetCountryOk() (*string, bool) {
	if o == nil || IsNil(o.Country) {
		return nil, false
	}
	return o.Country, true
}

// HasCountry returns a boolean if a field has been set.
func (o *Review) HasCountry() bool {
	if o != nil && !IsNil(o.Country) {
		return true
	}

	return false
}

// SetCountry gets a reference to the given string and assigns it to the Country field.
func (o *Review) SetCountry(v string) {
	o.Country = &v
}

// GetUpvotes returns the Upvotes field value if set, zero value otherwise.
func (o *Review) GetUpvotes() int32 {
	if o == nil || IsNil(o.Upvotes) {
		var ret int32
		return ret
	}
	return *o.Upvotes
}

// GetUpvotesOk returns a tuple with the Upvotes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Review) GetUpvotesOk() (*int32, bool) {
	if o == nil || IsNil(o.Upvotes) {
		return nil, false
	}
	return o.Upvotes, true
}

// HasUpvotes returns a boolean if a field has been set.
func (o *Review) HasUpvotes() bool {
	if o != nil && !IsNil(o.Upvotes) {
		return true
	}

	return false
}

// SetUpvotes gets a reference to the given int32 and assigns it to the Upvotes field.
func (o *Review) SetUpvotes(v int32) {
	o.Upvotes = &v
}

// GetDownvotes returns the Downvotes field value if set, zero value otherwise.
func (o *Review) GetDownvotes() int32 {
	if o == nil || IsNil(o.Downvotes) {
		var ret int32
		return ret
	}
	return *o.Downvotes
}

// GetDownvotesOk returns a tuple with the Downvotes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Review) GetDownvotesOk() (*int32, bool) {
	if o == nil || IsNil(o.Downvotes) {
		return nil, false
	}
	return o.Downvotes, true
}

// HasDownvotes returns a boolean if a field has been set.
func (o *Review) HasDownvotes() bool {
	if o != nil && !IsNil(o.Downvotes) {
		return true
	}

	return false
}

// SetDownvotes gets a reference to the given int32 and assigns it to the Downvotes field.
func (o *Review) SetDownvotes(v int32) {
	o.Downvotes = &v
}

// GetDate returns the Date field value if set, zero value otherwise.
func (o *Review) GetDate() string {
	if o == nil || IsNil(o.Date) {
		var ret string
		return ret
	}
	return *o.Date
}

// GetDateOk returns a tuple with the Date field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Review) GetDateOk() (*string, bool) {
	if o == nil || IsNil(o.Date) {
		return nil, false
	}
	return o.Date, true
}

// HasDate returns a boolean if a field has been set.
func (o *Review) HasDate() bool {
	if o != nil && !IsNil(o.Date) {
		return true
	}

	return false
}

// SetDate gets a reference to the given string and assigns it to the Date field.
func (o *Review) SetDate(v string) {
	o.Date = &v
}

// GetShippingMethod returns the ShippingMethod field value if set, zero value otherwise.
func (o *Review) GetShippingMethod() string {
	if o == nil || IsNil(o.ShippingMethod) {
		var ret string
		return ret
	}
	return *o.ShippingMethod
}

// GetShippingMethodOk returns a tuple with the ShippingMethod field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Review) GetShippingMethodOk() (*string, bool) {
	if o == nil || IsNil(o.ShippingMethod) {
		return nil, false
	}
	return o.ShippingMethod, true
}

// HasShippingMethod returns a boolean if a field has been set.
func (o *Review) HasShippingMethod() bool {
	if o != nil && !IsNil(o.ShippingMethod) {
		return true
	}

	return false
}

// SetShippingMethod gets a reference to the given string and assigns it to the ShippingMethod field.
func (o *Review) SetShippingMethod(v string) {
	o.ShippingMethod = &v
}

// GetVariant returns the Variant field value if set, zero value otherwise.
func (o *Review) GetVariant() string {
	if o == nil || IsNil(o.Variant) {
		var ret string
		return ret
	}
	return *o.Variant
}

// GetVariantOk returns a tuple with the Variant field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Review) GetVariantOk() (*string, bool) {
	if o == nil || IsNil(o.Variant) {
		return nil, false
	}
	return o.Variant, true
}

// HasVariant returns a boolean if a field has been set.
func (o *Review) HasVariant() bool {
	if o != nil && !IsNil(o.Variant) {
		return true
	}

	return false
}

// SetVariant gets a reference to the given string and assigns it to the Variant field.
func (o *Review) SetVariant(v string) {
	o.Variant = &v
}

// GetLabels returns the Labels field value if set, zero value otherwise.
func (o *Review) GetLabels() []ReviewLabel {
	if o == nil || IsNil(o.Labels) {
		var ret []ReviewLabel
		return ret
	}
	return o.Labels
}

// GetLabelsOk returns a tuple with the Labels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Review) GetLabelsOk() ([]ReviewLabel, bool) {
	if o == nil || IsNil(o.Labels) {
		return nil, false
	}
	return o.Labels, true
}

// HasLabels returns a boolean if a field has been set.
func (o *Review) HasLabels() bool {
	if o != nil && !IsNil(o.Labels) {
		return true
	}

	return false
}

// SetLabels gets a reference to the given []ReviewLabel and assigns it to the Labels field.
func (o *Review) SetLabels(v []ReviewLabel) {
	o.Labels = v
}

// GetImages returns the Images field value if set, zero value otherwise.
func (o *Review) GetImages() []string {
	if o == nil || IsNil(o.Images) {
		var ret []string
		return ret
	}
	return o.Images
}

// GetImagesOk returns a tuple with the Images field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Review) GetImagesOk() ([]string, bool) {
	if o == nil || IsNil(o.Images) {
		return nil, false
	}
	return o.Images, true
}

// HasImages returns a boolean if a field has been set.
func (o *Review) HasImages() bool {
	if o != nil && !IsNil(o.Images) {
		return true
	}

	return false
}

// SetImages gets a reference to the given []string and assigns it to the Images field.
func (o *Review) SetImages(v []string) {
	o.Images = v
}

// GetComment returns the Comment field value if set, zero value otherwise.
func (o *Review) GetComment() ReviewContent {
	if o == nil || IsNil(o.Comment) {
		var ret ReviewContent
		return ret
	}
	return *o.Comment
}

// GetCommentOk returns a tuple with the Comment field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Review) GetCommentOk() (*ReviewContent, bool) {
	if o == nil || IsNil(o.Comment) {
		return nil, false
	}
	return o.Comment, true
}

// HasComment returns a boolean if a field has been set.
func (o *Review) HasComment() bool {
	if o != nil && !IsNil(o.Comment) {
		return true
	}

	return false
}

// SetComment gets a reference to the given ReviewContent and assigns it to the Comment field.
func (o *Review) SetComment(v ReviewContent) {
	o.Comment = &v
}

// GetAdditionalComment returns the AdditionalComment field value if set, zero value otherwise.
func (o *Review) GetAdditionalComment() ReviewContent {
	if o == nil || IsNil(o.AdditionalComment) {
		var ret ReviewContent
		return ret
	}
	return *o.AdditionalComment
}

// GetAdditionalCommentOk returns a tuple with the AdditionalComment field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Review) GetAdditionalCommentOk() (*ReviewContent, bool) {
	if o == nil || IsNil(o.AdditionalComment) {
		return nil, false
	}
	return o.AdditionalComment, true
}

// HasAdditionalComment returns a boolean if a field has been set.
func (o *Review) HasAdditionalComment() bool {
	if o != nil && !IsNil(o.AdditionalComment) {
		return true
	}

	return false
}

// SetAdditionalComment gets a reference to the given ReviewContent and assigns it to the AdditionalComment field.
func (o *Review) SetAdditionalComment(v ReviewContent) {
	o.AdditionalComment = &v
}

// GetSellerReply returns the SellerReply field value if set, zero value otherwise.
func (o *Review) GetSellerReply() ReviewContent {
	if o == nil || IsNil(o.SellerReply) {
		var ret ReviewContent
		return ret
	}
	return *o.SellerReply
}

// GetSellerReplyOk returns a tuple with the SellerReply field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Review) GetSellerReplyOk() (*ReviewContent, bool) {
	if o == nil || IsNil(o.SellerReply) {
		return nil, false
	}
	return o.SellerReply, true
}

// HasSellerReply returns a boolean if a field has been set.
func (o *Review) HasSellerReply() bool {
	if o != nil && !IsNil(o.SellerReply) {
		return true
	}

	return false
}

// SetSellerReply gets a reference to the given ReviewContent and assigns it to the SellerReply field.
func (o *Review) SetSellerReply(v ReviewContent) {
	o.SellerReply = &v
}

// GetAdditionalSellerReply returns the AdditionalSellerReply field value if set, zero value otherwise.
func (o *Review) GetAdditionalSellerReply() ReviewContent {
	if o == nil || IsNil(o.AdditionalSellerReply) {
		var ret ReviewContent
		return ret
	}
	return *o.AdditionalSellerReply
}

// GetAdditionalSellerReplyOk returns a tuple with the AdditionalSellerReply field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Review) GetAdditionalSellerReplyOk() (*ReviewContent, bool) {
	if o == nil || IsNil(o.AdditionalSellerReply) {
		return nil, false
	}
	return o.AdditionalSellerReply, true
}

// HasAdditionalSellerReply returns a boolean if a field has been set.
func (o *Review) HasAdditionalSellerReply() bool {
	if o != nil && !IsNil(o.AdditionalSellerReply) {
		return true
	}

	return false
}

// SetAdditionalSellerReply gets a reference to the given ReviewContent and assigns it to the AdditionalSellerReply field.
func (o *Review) SetAdditionalSellerReply(v ReviewContent) {
	o.AdditionalSellerReply = &v
}

func (o Review) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Review) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ReviewId) {
		toSerialize["review_id"] = o.ReviewId
	}
	if !IsNil(o.Buyer) {
		toSerialize["buyer"] = o.Buyer
	}
	if !IsNil(o.Anonymous) {
		toSerialize["anonymous"] = o.Anonymous
	}
	if !IsNil(o.Rating) {
		toSerialize["rating"] = o.Rating
	}
	if !IsNil(o.Country) {
		toSerialize["country"] = o.Country
	}
	if !IsNil(o.Upvotes) {
		toSerialize["upvotes"] = o.Upvotes
	}
	if !IsNil(o.Downvotes) {
		toSerialize["downvotes"] = o.Downvotes
	}
	if !IsNil(o.Date) {
		toSerialize["date"] = o.Date
	}
	if !IsNil(o.ShippingMethod) {
		toSerialize["shipping_method"] = o.ShippingMethod
	}
	if !IsNil(o.Variant) {
		toSerialize["variant"] = o.Variant
	}
	if !IsNil(o.Labels) {
		toSerialize["labels"] = o.Labels
	}
	if !IsNil(o.Images) {
		toSerialize["images"] = o.Images
	}
	if !IsNil(o.Comment) {
		toSerialize["comment"] = o.Comment
	}
	if !IsNil(o.AdditionalComment) {
		toSerialize["additional_comment"] = o.AdditionalComment
	}
	if !IsNil(o.SellerReply) {
		toSerialize["seller_reply"] = o.SellerReply
	}
	if !IsNil(o.AdditionalSellerReply) {
		toSerialize["additional_seller_reply"] = o.AdditionalSellerReply
	}
	return toSerialize, nil
}

type NullableReview struct {
	value *Review
	isSet bool
}

func (v NullableReview) Get() *Review {
	return v.value
}

func (v *NullableReview) Set(val *Review) {
	v.value = val
	v.isSet = true
}

func (v NullableReview) IsSet() bool {
	return v.isSet
}

func (v *NullableReview) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableReview(val *Review) *NullableReview {
	return &NullableReview{value: val, isSet: true}
}

func (v NullableReview) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableReview) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


