/*
AliExpress Parser API

Real-time AliExpress data parser covering products, product reviews, sellers, store coupons, a seller's product catalog, and product search by text or image. Products: pricing, stock status, shipping options, seller information, product configurations (SKUs), and more - scoped to a specific country and currency. Reviews: customer ratings and feedback for a product. Sellers: full store profile with ratings, feedback, and categories. Coupons: active seller coupon codes with discounts, thresholds, budgets, and expiry. Seller products: a store's product catalog, paginated and best-selling first. Search: find products by keyword or by uploading an image, returning paginated product results with their categories. 

API version: 2.1.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aligate

import (
	"encoding/json"
	"time"
)

// checks if the Coupon type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Coupon{}

// Coupon A single active seller coupon campaign
type Coupon struct {
	// Coupon code to apply at checkout
	Code *string `json:"code,omitempty"`
	// Discount amount in the requested currency
	Discount *float64 `json:"discount,omitempty"`
	// Minimum order amount required to use the coupon
	OrdersOver *float64 `json:"orders_over,omitempty"`
	// Coupon expiration date (UTC)
	Expired *time.Time `json:"expired,omitempty"`
	// Required store membership level (empty when unrestricted)
	MemberLevel *string `json:"member_level,omitempty"`
	// Countries eligible for the coupon (empty when unrestricted)
	CountryList []string `json:"country_list,omitempty"`
	// True when the coupon applies only to selected products of the store (derived from the campaign range group); false when it applies storewide. 
	IsLimitedProducts *bool `json:"is_limited_products,omitempty"`
	// Total coupon budget issued
	Total *int32 `json:"total,omitempty"`
	// Coupons already claimed/used
	Consumed *int32 `json:"consumed,omitempty"`
	IsActive *bool `json:"is_active,omitempty"`
	// Parser version used
	Spider *string `json:"spider,omitempty"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
}

// NewCoupon instantiates a new Coupon object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCoupon() *Coupon {
	this := Coupon{}
	return &this
}

// NewCouponWithDefaults instantiates a new Coupon object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCouponWithDefaults() *Coupon {
	this := Coupon{}
	return &this
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *Coupon) GetCode() string {
	if o == nil || IsNil(o.Code) {
		var ret string
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Coupon) GetCodeOk() (*string, bool) {
	if o == nil || IsNil(o.Code) {
		return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *Coupon) HasCode() bool {
	if o != nil && !IsNil(o.Code) {
		return true
	}

	return false
}

// SetCode gets a reference to the given string and assigns it to the Code field.
func (o *Coupon) SetCode(v string) {
	o.Code = &v
}

// GetDiscount returns the Discount field value if set, zero value otherwise.
func (o *Coupon) GetDiscount() float64 {
	if o == nil || IsNil(o.Discount) {
		var ret float64
		return ret
	}
	return *o.Discount
}

// GetDiscountOk returns a tuple with the Discount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Coupon) GetDiscountOk() (*float64, bool) {
	if o == nil || IsNil(o.Discount) {
		return nil, false
	}
	return o.Discount, true
}

// HasDiscount returns a boolean if a field has been set.
func (o *Coupon) HasDiscount() bool {
	if o != nil && !IsNil(o.Discount) {
		return true
	}

	return false
}

// SetDiscount gets a reference to the given float64 and assigns it to the Discount field.
func (o *Coupon) SetDiscount(v float64) {
	o.Discount = &v
}

// GetOrdersOver returns the OrdersOver field value if set, zero value otherwise.
func (o *Coupon) GetOrdersOver() float64 {
	if o == nil || IsNil(o.OrdersOver) {
		var ret float64
		return ret
	}
	return *o.OrdersOver
}

// GetOrdersOverOk returns a tuple with the OrdersOver field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Coupon) GetOrdersOverOk() (*float64, bool) {
	if o == nil || IsNil(o.OrdersOver) {
		return nil, false
	}
	return o.OrdersOver, true
}

// HasOrdersOver returns a boolean if a field has been set.
func (o *Coupon) HasOrdersOver() bool {
	if o != nil && !IsNil(o.OrdersOver) {
		return true
	}

	return false
}

// SetOrdersOver gets a reference to the given float64 and assigns it to the OrdersOver field.
func (o *Coupon) SetOrdersOver(v float64) {
	o.OrdersOver = &v
}

// GetExpired returns the Expired field value if set, zero value otherwise.
func (o *Coupon) GetExpired() time.Time {
	if o == nil || IsNil(o.Expired) {
		var ret time.Time
		return ret
	}
	return *o.Expired
}

// GetExpiredOk returns a tuple with the Expired field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Coupon) GetExpiredOk() (*time.Time, bool) {
	if o == nil || IsNil(o.Expired) {
		return nil, false
	}
	return o.Expired, true
}

// HasExpired returns a boolean if a field has been set.
func (o *Coupon) HasExpired() bool {
	if o != nil && !IsNil(o.Expired) {
		return true
	}

	return false
}

// SetExpired gets a reference to the given time.Time and assigns it to the Expired field.
func (o *Coupon) SetExpired(v time.Time) {
	o.Expired = &v
}

// GetMemberLevel returns the MemberLevel field value if set, zero value otherwise.
func (o *Coupon) GetMemberLevel() string {
	if o == nil || IsNil(o.MemberLevel) {
		var ret string
		return ret
	}
	return *o.MemberLevel
}

// GetMemberLevelOk returns a tuple with the MemberLevel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Coupon) GetMemberLevelOk() (*string, bool) {
	if o == nil || IsNil(o.MemberLevel) {
		return nil, false
	}
	return o.MemberLevel, true
}

// HasMemberLevel returns a boolean if a field has been set.
func (o *Coupon) HasMemberLevel() bool {
	if o != nil && !IsNil(o.MemberLevel) {
		return true
	}

	return false
}

// SetMemberLevel gets a reference to the given string and assigns it to the MemberLevel field.
func (o *Coupon) SetMemberLevel(v string) {
	o.MemberLevel = &v
}

// GetCountryList returns the CountryList field value if set, zero value otherwise.
func (o *Coupon) GetCountryList() []string {
	if o == nil || IsNil(o.CountryList) {
		var ret []string
		return ret
	}
	return o.CountryList
}

// GetCountryListOk returns a tuple with the CountryList field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Coupon) GetCountryListOk() ([]string, bool) {
	if o == nil || IsNil(o.CountryList) {
		return nil, false
	}
	return o.CountryList, true
}

// HasCountryList returns a boolean if a field has been set.
func (o *Coupon) HasCountryList() bool {
	if o != nil && !IsNil(o.CountryList) {
		return true
	}

	return false
}

// SetCountryList gets a reference to the given []string and assigns it to the CountryList field.
func (o *Coupon) SetCountryList(v []string) {
	o.CountryList = v
}

// GetIsLimitedProducts returns the IsLimitedProducts field value if set, zero value otherwise.
func (o *Coupon) GetIsLimitedProducts() bool {
	if o == nil || IsNil(o.IsLimitedProducts) {
		var ret bool
		return ret
	}
	return *o.IsLimitedProducts
}

// GetIsLimitedProductsOk returns a tuple with the IsLimitedProducts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Coupon) GetIsLimitedProductsOk() (*bool, bool) {
	if o == nil || IsNil(o.IsLimitedProducts) {
		return nil, false
	}
	return o.IsLimitedProducts, true
}

// HasIsLimitedProducts returns a boolean if a field has been set.
func (o *Coupon) HasIsLimitedProducts() bool {
	if o != nil && !IsNil(o.IsLimitedProducts) {
		return true
	}

	return false
}

// SetIsLimitedProducts gets a reference to the given bool and assigns it to the IsLimitedProducts field.
func (o *Coupon) SetIsLimitedProducts(v bool) {
	o.IsLimitedProducts = &v
}

// GetTotal returns the Total field value if set, zero value otherwise.
func (o *Coupon) GetTotal() int32 {
	if o == nil || IsNil(o.Total) {
		var ret int32
		return ret
	}
	return *o.Total
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Coupon) GetTotalOk() (*int32, bool) {
	if o == nil || IsNil(o.Total) {
		return nil, false
	}
	return o.Total, true
}

// HasTotal returns a boolean if a field has been set.
func (o *Coupon) HasTotal() bool {
	if o != nil && !IsNil(o.Total) {
		return true
	}

	return false
}

// SetTotal gets a reference to the given int32 and assigns it to the Total field.
func (o *Coupon) SetTotal(v int32) {
	o.Total = &v
}

// GetConsumed returns the Consumed field value if set, zero value otherwise.
func (o *Coupon) GetConsumed() int32 {
	if o == nil || IsNil(o.Consumed) {
		var ret int32
		return ret
	}
	return *o.Consumed
}

// GetConsumedOk returns a tuple with the Consumed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Coupon) GetConsumedOk() (*int32, bool) {
	if o == nil || IsNil(o.Consumed) {
		return nil, false
	}
	return o.Consumed, true
}

// HasConsumed returns a boolean if a field has been set.
func (o *Coupon) HasConsumed() bool {
	if o != nil && !IsNil(o.Consumed) {
		return true
	}

	return false
}

// SetConsumed gets a reference to the given int32 and assigns it to the Consumed field.
func (o *Coupon) SetConsumed(v int32) {
	o.Consumed = &v
}

// GetIsActive returns the IsActive field value if set, zero value otherwise.
func (o *Coupon) GetIsActive() bool {
	if o == nil || IsNil(o.IsActive) {
		var ret bool
		return ret
	}
	return *o.IsActive
}

// GetIsActiveOk returns a tuple with the IsActive field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Coupon) GetIsActiveOk() (*bool, bool) {
	if o == nil || IsNil(o.IsActive) {
		return nil, false
	}
	return o.IsActive, true
}

// HasIsActive returns a boolean if a field has been set.
func (o *Coupon) HasIsActive() bool {
	if o != nil && !IsNil(o.IsActive) {
		return true
	}

	return false
}

// SetIsActive gets a reference to the given bool and assigns it to the IsActive field.
func (o *Coupon) SetIsActive(v bool) {
	o.IsActive = &v
}

// GetSpider returns the Spider field value if set, zero value otherwise.
func (o *Coupon) GetSpider() string {
	if o == nil || IsNil(o.Spider) {
		var ret string
		return ret
	}
	return *o.Spider
}

// GetSpiderOk returns a tuple with the Spider field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Coupon) GetSpiderOk() (*string, bool) {
	if o == nil || IsNil(o.Spider) {
		return nil, false
	}
	return o.Spider, true
}

// HasSpider returns a boolean if a field has been set.
func (o *Coupon) HasSpider() bool {
	if o != nil && !IsNil(o.Spider) {
		return true
	}

	return false
}

// SetSpider gets a reference to the given string and assigns it to the Spider field.
func (o *Coupon) SetSpider(v string) {
	o.Spider = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *Coupon) GetUpdatedAt() time.Time {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Coupon) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *Coupon) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given time.Time and assigns it to the UpdatedAt field.
func (o *Coupon) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = &v
}

func (o Coupon) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Coupon) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Code) {
		toSerialize["code"] = o.Code
	}
	if !IsNil(o.Discount) {
		toSerialize["discount"] = o.Discount
	}
	if !IsNil(o.OrdersOver) {
		toSerialize["orders_over"] = o.OrdersOver
	}
	if !IsNil(o.Expired) {
		toSerialize["expired"] = o.Expired
	}
	if !IsNil(o.MemberLevel) {
		toSerialize["member_level"] = o.MemberLevel
	}
	if !IsNil(o.CountryList) {
		toSerialize["country_list"] = o.CountryList
	}
	if !IsNil(o.IsLimitedProducts) {
		toSerialize["is_limited_products"] = o.IsLimitedProducts
	}
	if !IsNil(o.Total) {
		toSerialize["total"] = o.Total
	}
	if !IsNil(o.Consumed) {
		toSerialize["consumed"] = o.Consumed
	}
	if !IsNil(o.IsActive) {
		toSerialize["is_active"] = o.IsActive
	}
	if !IsNil(o.Spider) {
		toSerialize["spider"] = o.Spider
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updated_at"] = o.UpdatedAt
	}
	return toSerialize, nil
}

type NullableCoupon struct {
	value *Coupon
	isSet bool
}

func (v NullableCoupon) Get() *Coupon {
	return v.value
}

func (v *NullableCoupon) Set(val *Coupon) {
	v.value = val
	v.isSet = true
}

func (v NullableCoupon) IsSet() bool {
	return v.isSet
}

func (v *NullableCoupon) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCoupon(val *Coupon) *NullableCoupon {
	return &NullableCoupon{value: val, isSet: true}
}

func (v NullableCoupon) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCoupon) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


