/*
AliExpress Parser API

Real-time AliExpress data parser covering products, product reviews, sellers, store coupons, a seller's product catalog, and product search by text or image. Products: pricing, stock status, shipping options, seller information, product configurations (SKUs), and more - scoped to a specific country and currency. Reviews: customer ratings and feedback for a product. Sellers: full store profile with ratings, feedback, and categories. Coupons: active seller coupon codes with discounts, thresholds, budgets, and expiry. Seller products: a store's product catalog, paginated and best-selling first. Search: find products by keyword or by uploading an image, returning paginated product results with their categories. 

API version: 2.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aligate

import (
	"encoding/json"
)

// checks if the CouponsParseResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CouponsParseResponse{}

// CouponsParseResponse Top-level response envelope returned by the gateway for coupon requests
type CouponsParseResponse struct {
	Meta *CouponMeta `json:"meta,omitempty"`
	Settings *CouponSettings `json:"settings,omitempty"`
	// Active coupons of the store (empty when the seller has none)
	Items []Coupon `json:"items,omitempty"`
}

// NewCouponsParseResponse instantiates a new CouponsParseResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCouponsParseResponse() *CouponsParseResponse {
	this := CouponsParseResponse{}
	return &this
}

// NewCouponsParseResponseWithDefaults instantiates a new CouponsParseResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCouponsParseResponseWithDefaults() *CouponsParseResponse {
	this := CouponsParseResponse{}
	return &this
}

// GetMeta returns the Meta field value if set, zero value otherwise.
func (o *CouponsParseResponse) GetMeta() CouponMeta {
	if o == nil || IsNil(o.Meta) {
		var ret CouponMeta
		return ret
	}
	return *o.Meta
}

// GetMetaOk returns a tuple with the Meta field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CouponsParseResponse) GetMetaOk() (*CouponMeta, bool) {
	if o == nil || IsNil(o.Meta) {
		return nil, false
	}
	return o.Meta, true
}

// HasMeta returns a boolean if a field has been set.
func (o *CouponsParseResponse) HasMeta() bool {
	if o != nil && !IsNil(o.Meta) {
		return true
	}

	return false
}

// SetMeta gets a reference to the given CouponMeta and assigns it to the Meta field.
func (o *CouponsParseResponse) SetMeta(v CouponMeta) {
	o.Meta = &v
}

// GetSettings returns the Settings field value if set, zero value otherwise.
func (o *CouponsParseResponse) GetSettings() CouponSettings {
	if o == nil || IsNil(o.Settings) {
		var ret CouponSettings
		return ret
	}
	return *o.Settings
}

// GetSettingsOk returns a tuple with the Settings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CouponsParseResponse) GetSettingsOk() (*CouponSettings, bool) {
	if o == nil || IsNil(o.Settings) {
		return nil, false
	}
	return o.Settings, true
}

// HasSettings returns a boolean if a field has been set.
func (o *CouponsParseResponse) HasSettings() bool {
	if o != nil && !IsNil(o.Settings) {
		return true
	}

	return false
}

// SetSettings gets a reference to the given CouponSettings and assigns it to the Settings field.
func (o *CouponsParseResponse) SetSettings(v CouponSettings) {
	o.Settings = &v
}

// GetItems returns the Items field value if set, zero value otherwise.
func (o *CouponsParseResponse) GetItems() []Coupon {
	if o == nil || IsNil(o.Items) {
		var ret []Coupon
		return ret
	}
	return o.Items
}

// GetItemsOk returns a tuple with the Items field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CouponsParseResponse) GetItemsOk() ([]Coupon, bool) {
	if o == nil || IsNil(o.Items) {
		return nil, false
	}
	return o.Items, true
}

// HasItems returns a boolean if a field has been set.
func (o *CouponsParseResponse) HasItems() bool {
	if o != nil && !IsNil(o.Items) {
		return true
	}

	return false
}

// SetItems gets a reference to the given []Coupon and assigns it to the Items field.
func (o *CouponsParseResponse) SetItems(v []Coupon) {
	o.Items = v
}

func (o CouponsParseResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CouponsParseResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Meta) {
		toSerialize["meta"] = o.Meta
	}
	if !IsNil(o.Settings) {
		toSerialize["settings"] = o.Settings
	}
	if !IsNil(o.Items) {
		toSerialize["items"] = o.Items
	}
	return toSerialize, nil
}

type NullableCouponsParseResponse struct {
	value *CouponsParseResponse
	isSet bool
}

func (v NullableCouponsParseResponse) Get() *CouponsParseResponse {
	return v.value
}

func (v *NullableCouponsParseResponse) Set(val *CouponsParseResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCouponsParseResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCouponsParseResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCouponsParseResponse(val *CouponsParseResponse) *NullableCouponsParseResponse {
	return &NullableCouponsParseResponse{value: val, isSet: true}
}

func (v NullableCouponsParseResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCouponsParseResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


