/*
AliExpress Parser API

Real-time AliExpress data parser covering products, product reviews, sellers, store coupons, a seller's product catalog, and product search by text or image. Products: pricing, stock status, shipping options, seller information, product configurations (SKUs), and more - scoped to a specific country and currency. Reviews: customer ratings and feedback for a product. Sellers: full store profile with ratings, feedback, and categories. Coupons: active seller coupon codes with discounts, thresholds, budgets, and expiry. Seller products: a store's product catalog, paginated and best-selling first. Search: find products by keyword or by uploading an image, returning paginated product results with their categories. 

API version: 2.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aligate

import (
	"encoding/json"
	"time"
)

// checks if the SellerItem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SellerItem{}

// SellerItem Parsed AliExpress seller/store data
type SellerItem struct {
	Id *int32 `json:"id,omitempty"`
	StoreNum *int32 `json:"store_num,omitempty"`
	StoreName *string `json:"store_name,omitempty"`
	// Seller country code
	Country *string `json:"country,omitempty"`
	// URL of the store logo image
	StoreLogo *string `json:"store_logo,omitempty"`
	// Overall store rating score (0–5)
	StoreRating *float64 `json:"store_rating,omitempty"`
	// Date the store was established
	SinceFrom *time.Time `json:"since_from,omitempty"`
	// Count of positive feedback received
	PositiveFeedback *int32 `json:"positive_feedback,omitempty"`
	// Count of neutral feedback received
	NeutralFeedback *int32 `json:"neutral_feedback,omitempty"`
	// Count of negative feedback received
	NegativeFeedback *int32 `json:"negative_feedback,omitempty"`
	// Communication score (0–5)
	Communication *float64 `json:"communication,omitempty"`
	// Shipping speed score (0–5)
	ShippingSpeed *float64 `json:"shipping_speed,omitempty"`
	// Item as described score (0–5)
	Described *float64 `json:"described,omitempty"`
	// Positive review percentage (0–100)
	PositiveReviews *float64 `json:"positive_reviews,omitempty"`
	// Number of store followers
	Followers *float64 `json:"followers,omitempty"`
	// Units sold in the last 6 months
	SixMonthSales *float64 `json:"six_month_sales,omitempty"`
	// Number of repeat buyers
	RegularBuyers *float64 `json:"regular_buyers,omitempty"`
	// Store age in years
	StoreAge *float64 `json:"store_age,omitempty"`
	// True when the store is currently running a sale campaign
	IsOnSale *bool `json:"is_on_sale,omitempty"`
	// UTC timestamp when the current sale starts (omitted if not in sale)
	SaleStartsAt NullableTime `json:"sale_starts_at,omitempty"`
	// UTC timestamp when the current sale ends (omitted if not in sale)
	SaleEndsAt NullableTime `json:"sale_ends_at,omitempty"`
	// Link to the seller's AliExpress business license verification page
	BusinessLicenseUrl *string `json:"business_license_url,omitempty"`
	// Store's custom product category tree
	StoreCategories []StoreCategory `json:"store_categories,omitempty"`
	// Parser version used
	Spider *string `json:"spider,omitempty"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
}

// NewSellerItem instantiates a new SellerItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSellerItem() *SellerItem {
	this := SellerItem{}
	return &this
}

// NewSellerItemWithDefaults instantiates a new SellerItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSellerItemWithDefaults() *SellerItem {
	this := SellerItem{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *SellerItem) GetId() int32 {
	if o == nil || IsNil(o.Id) {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SellerItem) GetIdOk() (*int32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *SellerItem) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *SellerItem) SetId(v int32) {
	o.Id = &v
}

// GetStoreNum returns the StoreNum field value if set, zero value otherwise.
func (o *SellerItem) GetStoreNum() int32 {
	if o == nil || IsNil(o.StoreNum) {
		var ret int32
		return ret
	}
	return *o.StoreNum
}

// GetStoreNumOk returns a tuple with the StoreNum field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SellerItem) GetStoreNumOk() (*int32, bool) {
	if o == nil || IsNil(o.StoreNum) {
		return nil, false
	}
	return o.StoreNum, true
}

// HasStoreNum returns a boolean if a field has been set.
func (o *SellerItem) HasStoreNum() bool {
	if o != nil && !IsNil(o.StoreNum) {
		return true
	}

	return false
}

// SetStoreNum gets a reference to the given int32 and assigns it to the StoreNum field.
func (o *SellerItem) SetStoreNum(v int32) {
	o.StoreNum = &v
}

// GetStoreName returns the StoreName field value if set, zero value otherwise.
func (o *SellerItem) GetStoreName() string {
	if o == nil || IsNil(o.StoreName) {
		var ret string
		return ret
	}
	return *o.StoreName
}

// GetStoreNameOk returns a tuple with the StoreName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SellerItem) GetStoreNameOk() (*string, bool) {
	if o == nil || IsNil(o.StoreName) {
		return nil, false
	}
	return o.StoreName, true
}

// HasStoreName returns a boolean if a field has been set.
func (o *SellerItem) HasStoreName() bool {
	if o != nil && !IsNil(o.StoreName) {
		return true
	}

	return false
}

// SetStoreName gets a reference to the given string and assigns it to the StoreName field.
func (o *SellerItem) SetStoreName(v string) {
	o.StoreName = &v
}

// GetCountry returns the Country field value if set, zero value otherwise.
func (o *SellerItem) GetCountry() string {
	if o == nil || IsNil(o.Country) {
		var ret string
		return ret
	}
	return *o.Country
}

// GetCountryOk returns a tuple with the Country field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SellerItem) GetCountryOk() (*string, bool) {
	if o == nil || IsNil(o.Country) {
		return nil, false
	}
	return o.Country, true
}

// HasCountry returns a boolean if a field has been set.
func (o *SellerItem) HasCountry() bool {
	if o != nil && !IsNil(o.Country) {
		return true
	}

	return false
}

// SetCountry gets a reference to the given string and assigns it to the Country field.
func (o *SellerItem) SetCountry(v string) {
	o.Country = &v
}

// GetStoreLogo returns the StoreLogo field value if set, zero value otherwise.
func (o *SellerItem) GetStoreLogo() string {
	if o == nil || IsNil(o.StoreLogo) {
		var ret string
		return ret
	}
	return *o.StoreLogo
}

// GetStoreLogoOk returns a tuple with the StoreLogo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SellerItem) GetStoreLogoOk() (*string, bool) {
	if o == nil || IsNil(o.StoreLogo) {
		return nil, false
	}
	return o.StoreLogo, true
}

// HasStoreLogo returns a boolean if a field has been set.
func (o *SellerItem) HasStoreLogo() bool {
	if o != nil && !IsNil(o.StoreLogo) {
		return true
	}

	return false
}

// SetStoreLogo gets a reference to the given string and assigns it to the StoreLogo field.
func (o *SellerItem) SetStoreLogo(v string) {
	o.StoreLogo = &v
}

// GetStoreRating returns the StoreRating field value if set, zero value otherwise.
func (o *SellerItem) GetStoreRating() float64 {
	if o == nil || IsNil(o.StoreRating) {
		var ret float64
		return ret
	}
	return *o.StoreRating
}

// GetStoreRatingOk returns a tuple with the StoreRating field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SellerItem) GetStoreRatingOk() (*float64, bool) {
	if o == nil || IsNil(o.StoreRating) {
		return nil, false
	}
	return o.StoreRating, true
}

// HasStoreRating returns a boolean if a field has been set.
func (o *SellerItem) HasStoreRating() bool {
	if o != nil && !IsNil(o.StoreRating) {
		return true
	}

	return false
}

// SetStoreRating gets a reference to the given float64 and assigns it to the StoreRating field.
func (o *SellerItem) SetStoreRating(v float64) {
	o.StoreRating = &v
}

// GetSinceFrom returns the SinceFrom field value if set, zero value otherwise.
func (o *SellerItem) GetSinceFrom() time.Time {
	if o == nil || IsNil(o.SinceFrom) {
		var ret time.Time
		return ret
	}
	return *o.SinceFrom
}

// GetSinceFromOk returns a tuple with the SinceFrom field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SellerItem) GetSinceFromOk() (*time.Time, bool) {
	if o == nil || IsNil(o.SinceFrom) {
		return nil, false
	}
	return o.SinceFrom, true
}

// HasSinceFrom returns a boolean if a field has been set.
func (o *SellerItem) HasSinceFrom() bool {
	if o != nil && !IsNil(o.SinceFrom) {
		return true
	}

	return false
}

// SetSinceFrom gets a reference to the given time.Time and assigns it to the SinceFrom field.
func (o *SellerItem) SetSinceFrom(v time.Time) {
	o.SinceFrom = &v
}

// GetPositiveFeedback returns the PositiveFeedback field value if set, zero value otherwise.
func (o *SellerItem) GetPositiveFeedback() int32 {
	if o == nil || IsNil(o.PositiveFeedback) {
		var ret int32
		return ret
	}
	return *o.PositiveFeedback
}

// GetPositiveFeedbackOk returns a tuple with the PositiveFeedback field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SellerItem) GetPositiveFeedbackOk() (*int32, bool) {
	if o == nil || IsNil(o.PositiveFeedback) {
		return nil, false
	}
	return o.PositiveFeedback, true
}

// HasPositiveFeedback returns a boolean if a field has been set.
func (o *SellerItem) HasPositiveFeedback() bool {
	if o != nil && !IsNil(o.PositiveFeedback) {
		return true
	}

	return false
}

// SetPositiveFeedback gets a reference to the given int32 and assigns it to the PositiveFeedback field.
func (o *SellerItem) SetPositiveFeedback(v int32) {
	o.PositiveFeedback = &v
}

// GetNeutralFeedback returns the NeutralFeedback field value if set, zero value otherwise.
func (o *SellerItem) GetNeutralFeedback() int32 {
	if o == nil || IsNil(o.NeutralFeedback) {
		var ret int32
		return ret
	}
	return *o.NeutralFeedback
}

// GetNeutralFeedbackOk returns a tuple with the NeutralFeedback field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SellerItem) GetNeutralFeedbackOk() (*int32, bool) {
	if o == nil || IsNil(o.NeutralFeedback) {
		return nil, false
	}
	return o.NeutralFeedback, true
}

// HasNeutralFeedback returns a boolean if a field has been set.
func (o *SellerItem) HasNeutralFeedback() bool {
	if o != nil && !IsNil(o.NeutralFeedback) {
		return true
	}

	return false
}

// SetNeutralFeedback gets a reference to the given int32 and assigns it to the NeutralFeedback field.
func (o *SellerItem) SetNeutralFeedback(v int32) {
	o.NeutralFeedback = &v
}

// GetNegativeFeedback returns the NegativeFeedback field value if set, zero value otherwise.
func (o *SellerItem) GetNegativeFeedback() int32 {
	if o == nil || IsNil(o.NegativeFeedback) {
		var ret int32
		return ret
	}
	return *o.NegativeFeedback
}

// GetNegativeFeedbackOk returns a tuple with the NegativeFeedback field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SellerItem) GetNegativeFeedbackOk() (*int32, bool) {
	if o == nil || IsNil(o.NegativeFeedback) {
		return nil, false
	}
	return o.NegativeFeedback, true
}

// HasNegativeFeedback returns a boolean if a field has been set.
func (o *SellerItem) HasNegativeFeedback() bool {
	if o != nil && !IsNil(o.NegativeFeedback) {
		return true
	}

	return false
}

// SetNegativeFeedback gets a reference to the given int32 and assigns it to the NegativeFeedback field.
func (o *SellerItem) SetNegativeFeedback(v int32) {
	o.NegativeFeedback = &v
}

// GetCommunication returns the Communication field value if set, zero value otherwise.
func (o *SellerItem) GetCommunication() float64 {
	if o == nil || IsNil(o.Communication) {
		var ret float64
		return ret
	}
	return *o.Communication
}

// GetCommunicationOk returns a tuple with the Communication field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SellerItem) GetCommunicationOk() (*float64, bool) {
	if o == nil || IsNil(o.Communication) {
		return nil, false
	}
	return o.Communication, true
}

// HasCommunication returns a boolean if a field has been set.
func (o *SellerItem) HasCommunication() bool {
	if o != nil && !IsNil(o.Communication) {
		return true
	}

	return false
}

// SetCommunication gets a reference to the given float64 and assigns it to the Communication field.
func (o *SellerItem) SetCommunication(v float64) {
	o.Communication = &v
}

// GetShippingSpeed returns the ShippingSpeed field value if set, zero value otherwise.
func (o *SellerItem) GetShippingSpeed() float64 {
	if o == nil || IsNil(o.ShippingSpeed) {
		var ret float64
		return ret
	}
	return *o.ShippingSpeed
}

// GetShippingSpeedOk returns a tuple with the ShippingSpeed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SellerItem) GetShippingSpeedOk() (*float64, bool) {
	if o == nil || IsNil(o.ShippingSpeed) {
		return nil, false
	}
	return o.ShippingSpeed, true
}

// HasShippingSpeed returns a boolean if a field has been set.
func (o *SellerItem) HasShippingSpeed() bool {
	if o != nil && !IsNil(o.ShippingSpeed) {
		return true
	}

	return false
}

// SetShippingSpeed gets a reference to the given float64 and assigns it to the ShippingSpeed field.
func (o *SellerItem) SetShippingSpeed(v float64) {
	o.ShippingSpeed = &v
}

// GetDescribed returns the Described field value if set, zero value otherwise.
func (o *SellerItem) GetDescribed() float64 {
	if o == nil || IsNil(o.Described) {
		var ret float64
		return ret
	}
	return *o.Described
}

// GetDescribedOk returns a tuple with the Described field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SellerItem) GetDescribedOk() (*float64, bool) {
	if o == nil || IsNil(o.Described) {
		return nil, false
	}
	return o.Described, true
}

// HasDescribed returns a boolean if a field has been set.
func (o *SellerItem) HasDescribed() bool {
	if o != nil && !IsNil(o.Described) {
		return true
	}

	return false
}

// SetDescribed gets a reference to the given float64 and assigns it to the Described field.
func (o *SellerItem) SetDescribed(v float64) {
	o.Described = &v
}

// GetPositiveReviews returns the PositiveReviews field value if set, zero value otherwise.
func (o *SellerItem) GetPositiveReviews() float64 {
	if o == nil || IsNil(o.PositiveReviews) {
		var ret float64
		return ret
	}
	return *o.PositiveReviews
}

// GetPositiveReviewsOk returns a tuple with the PositiveReviews field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SellerItem) GetPositiveReviewsOk() (*float64, bool) {
	if o == nil || IsNil(o.PositiveReviews) {
		return nil, false
	}
	return o.PositiveReviews, true
}

// HasPositiveReviews returns a boolean if a field has been set.
func (o *SellerItem) HasPositiveReviews() bool {
	if o != nil && !IsNil(o.PositiveReviews) {
		return true
	}

	return false
}

// SetPositiveReviews gets a reference to the given float64 and assigns it to the PositiveReviews field.
func (o *SellerItem) SetPositiveReviews(v float64) {
	o.PositiveReviews = &v
}

// GetFollowers returns the Followers field value if set, zero value otherwise.
func (o *SellerItem) GetFollowers() float64 {
	if o == nil || IsNil(o.Followers) {
		var ret float64
		return ret
	}
	return *o.Followers
}

// GetFollowersOk returns a tuple with the Followers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SellerItem) GetFollowersOk() (*float64, bool) {
	if o == nil || IsNil(o.Followers) {
		return nil, false
	}
	return o.Followers, true
}

// HasFollowers returns a boolean if a field has been set.
func (o *SellerItem) HasFollowers() bool {
	if o != nil && !IsNil(o.Followers) {
		return true
	}

	return false
}

// SetFollowers gets a reference to the given float64 and assigns it to the Followers field.
func (o *SellerItem) SetFollowers(v float64) {
	o.Followers = &v
}

// GetSixMonthSales returns the SixMonthSales field value if set, zero value otherwise.
func (o *SellerItem) GetSixMonthSales() float64 {
	if o == nil || IsNil(o.SixMonthSales) {
		var ret float64
		return ret
	}
	return *o.SixMonthSales
}

// GetSixMonthSalesOk returns a tuple with the SixMonthSales field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SellerItem) GetSixMonthSalesOk() (*float64, bool) {
	if o == nil || IsNil(o.SixMonthSales) {
		return nil, false
	}
	return o.SixMonthSales, true
}

// HasSixMonthSales returns a boolean if a field has been set.
func (o *SellerItem) HasSixMonthSales() bool {
	if o != nil && !IsNil(o.SixMonthSales) {
		return true
	}

	return false
}

// SetSixMonthSales gets a reference to the given float64 and assigns it to the SixMonthSales field.
func (o *SellerItem) SetSixMonthSales(v float64) {
	o.SixMonthSales = &v
}

// GetRegularBuyers returns the RegularBuyers field value if set, zero value otherwise.
func (o *SellerItem) GetRegularBuyers() float64 {
	if o == nil || IsNil(o.RegularBuyers) {
		var ret float64
		return ret
	}
	return *o.RegularBuyers
}

// GetRegularBuyersOk returns a tuple with the RegularBuyers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SellerItem) GetRegularBuyersOk() (*float64, bool) {
	if o == nil || IsNil(o.RegularBuyers) {
		return nil, false
	}
	return o.RegularBuyers, true
}

// HasRegularBuyers returns a boolean if a field has been set.
func (o *SellerItem) HasRegularBuyers() bool {
	if o != nil && !IsNil(o.RegularBuyers) {
		return true
	}

	return false
}

// SetRegularBuyers gets a reference to the given float64 and assigns it to the RegularBuyers field.
func (o *SellerItem) SetRegularBuyers(v float64) {
	o.RegularBuyers = &v
}

// GetStoreAge returns the StoreAge field value if set, zero value otherwise.
func (o *SellerItem) GetStoreAge() float64 {
	if o == nil || IsNil(o.StoreAge) {
		var ret float64
		return ret
	}
	return *o.StoreAge
}

// GetStoreAgeOk returns a tuple with the StoreAge field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SellerItem) GetStoreAgeOk() (*float64, bool) {
	if o == nil || IsNil(o.StoreAge) {
		return nil, false
	}
	return o.StoreAge, true
}

// HasStoreAge returns a boolean if a field has been set.
func (o *SellerItem) HasStoreAge() bool {
	if o != nil && !IsNil(o.StoreAge) {
		return true
	}

	return false
}

// SetStoreAge gets a reference to the given float64 and assigns it to the StoreAge field.
func (o *SellerItem) SetStoreAge(v float64) {
	o.StoreAge = &v
}

// GetIsOnSale returns the IsOnSale field value if set, zero value otherwise.
func (o *SellerItem) GetIsOnSale() bool {
	if o == nil || IsNil(o.IsOnSale) {
		var ret bool
		return ret
	}
	return *o.IsOnSale
}

// GetIsOnSaleOk returns a tuple with the IsOnSale field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SellerItem) GetIsOnSaleOk() (*bool, bool) {
	if o == nil || IsNil(o.IsOnSale) {
		return nil, false
	}
	return o.IsOnSale, true
}

// HasIsOnSale returns a boolean if a field has been set.
func (o *SellerItem) HasIsOnSale() bool {
	if o != nil && !IsNil(o.IsOnSale) {
		return true
	}

	return false
}

// SetIsOnSale gets a reference to the given bool and assigns it to the IsOnSale field.
func (o *SellerItem) SetIsOnSale(v bool) {
	o.IsOnSale = &v
}

// GetSaleStartsAt returns the SaleStartsAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SellerItem) GetSaleStartsAt() time.Time {
	if o == nil || IsNil(o.SaleStartsAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.SaleStartsAt.Get()
}

// GetSaleStartsAtOk returns a tuple with the SaleStartsAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SellerItem) GetSaleStartsAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.SaleStartsAt.Get(), o.SaleStartsAt.IsSet()
}

// HasSaleStartsAt returns a boolean if a field has been set.
func (o *SellerItem) HasSaleStartsAt() bool {
	if o != nil && o.SaleStartsAt.IsSet() {
		return true
	}

	return false
}

// SetSaleStartsAt gets a reference to the given NullableTime and assigns it to the SaleStartsAt field.
func (o *SellerItem) SetSaleStartsAt(v time.Time) {
	o.SaleStartsAt.Set(&v)
}
// SetSaleStartsAtNil sets the value for SaleStartsAt to be an explicit nil
func (o *SellerItem) SetSaleStartsAtNil() {
	o.SaleStartsAt.Set(nil)
}

// UnsetSaleStartsAt ensures that no value is present for SaleStartsAt, not even an explicit nil
func (o *SellerItem) UnsetSaleStartsAt() {
	o.SaleStartsAt.Unset()
}

// GetSaleEndsAt returns the SaleEndsAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SellerItem) GetSaleEndsAt() time.Time {
	if o == nil || IsNil(o.SaleEndsAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.SaleEndsAt.Get()
}

// GetSaleEndsAtOk returns a tuple with the SaleEndsAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SellerItem) GetSaleEndsAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.SaleEndsAt.Get(), o.SaleEndsAt.IsSet()
}

// HasSaleEndsAt returns a boolean if a field has been set.
func (o *SellerItem) HasSaleEndsAt() bool {
	if o != nil && o.SaleEndsAt.IsSet() {
		return true
	}

	return false
}

// SetSaleEndsAt gets a reference to the given NullableTime and assigns it to the SaleEndsAt field.
func (o *SellerItem) SetSaleEndsAt(v time.Time) {
	o.SaleEndsAt.Set(&v)
}
// SetSaleEndsAtNil sets the value for SaleEndsAt to be an explicit nil
func (o *SellerItem) SetSaleEndsAtNil() {
	o.SaleEndsAt.Set(nil)
}

// UnsetSaleEndsAt ensures that no value is present for SaleEndsAt, not even an explicit nil
func (o *SellerItem) UnsetSaleEndsAt() {
	o.SaleEndsAt.Unset()
}

// GetBusinessLicenseUrl returns the BusinessLicenseUrl field value if set, zero value otherwise.
func (o *SellerItem) GetBusinessLicenseUrl() string {
	if o == nil || IsNil(o.BusinessLicenseUrl) {
		var ret string
		return ret
	}
	return *o.BusinessLicenseUrl
}

// GetBusinessLicenseUrlOk returns a tuple with the BusinessLicenseUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SellerItem) GetBusinessLicenseUrlOk() (*string, bool) {
	if o == nil || IsNil(o.BusinessLicenseUrl) {
		return nil, false
	}
	return o.BusinessLicenseUrl, true
}

// HasBusinessLicenseUrl returns a boolean if a field has been set.
func (o *SellerItem) HasBusinessLicenseUrl() bool {
	if o != nil && !IsNil(o.BusinessLicenseUrl) {
		return true
	}

	return false
}

// SetBusinessLicenseUrl gets a reference to the given string and assigns it to the BusinessLicenseUrl field.
func (o *SellerItem) SetBusinessLicenseUrl(v string) {
	o.BusinessLicenseUrl = &v
}

// GetStoreCategories returns the StoreCategories field value if set, zero value otherwise.
func (o *SellerItem) GetStoreCategories() []StoreCategory {
	if o == nil || IsNil(o.StoreCategories) {
		var ret []StoreCategory
		return ret
	}
	return o.StoreCategories
}

// GetStoreCategoriesOk returns a tuple with the StoreCategories field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SellerItem) GetStoreCategoriesOk() ([]StoreCategory, bool) {
	if o == nil || IsNil(o.StoreCategories) {
		return nil, false
	}
	return o.StoreCategories, true
}

// HasStoreCategories returns a boolean if a field has been set.
func (o *SellerItem) HasStoreCategories() bool {
	if o != nil && !IsNil(o.StoreCategories) {
		return true
	}

	return false
}

// SetStoreCategories gets a reference to the given []StoreCategory and assigns it to the StoreCategories field.
func (o *SellerItem) SetStoreCategories(v []StoreCategory) {
	o.StoreCategories = v
}

// GetSpider returns the Spider field value if set, zero value otherwise.
func (o *SellerItem) GetSpider() string {
	if o == nil || IsNil(o.Spider) {
		var ret string
		return ret
	}
	return *o.Spider
}

// GetSpiderOk returns a tuple with the Spider field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SellerItem) GetSpiderOk() (*string, bool) {
	if o == nil || IsNil(o.Spider) {
		return nil, false
	}
	return o.Spider, true
}

// HasSpider returns a boolean if a field has been set.
func (o *SellerItem) HasSpider() bool {
	if o != nil && !IsNil(o.Spider) {
		return true
	}

	return false
}

// SetSpider gets a reference to the given string and assigns it to the Spider field.
func (o *SellerItem) SetSpider(v string) {
	o.Spider = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *SellerItem) GetUpdatedAt() time.Time {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SellerItem) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *SellerItem) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given time.Time and assigns it to the UpdatedAt field.
func (o *SellerItem) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = &v
}

func (o SellerItem) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SellerItem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.StoreNum) {
		toSerialize["store_num"] = o.StoreNum
	}
	if !IsNil(o.StoreName) {
		toSerialize["store_name"] = o.StoreName
	}
	if !IsNil(o.Country) {
		toSerialize["country"] = o.Country
	}
	if !IsNil(o.StoreLogo) {
		toSerialize["store_logo"] = o.StoreLogo
	}
	if !IsNil(o.StoreRating) {
		toSerialize["store_rating"] = o.StoreRating
	}
	if !IsNil(o.SinceFrom) {
		toSerialize["since_from"] = o.SinceFrom
	}
	if !IsNil(o.PositiveFeedback) {
		toSerialize["positive_feedback"] = o.PositiveFeedback
	}
	if !IsNil(o.NeutralFeedback) {
		toSerialize["neutral_feedback"] = o.NeutralFeedback
	}
	if !IsNil(o.NegativeFeedback) {
		toSerialize["negative_feedback"] = o.NegativeFeedback
	}
	if !IsNil(o.Communication) {
		toSerialize["communication"] = o.Communication
	}
	if !IsNil(o.ShippingSpeed) {
		toSerialize["shipping_speed"] = o.ShippingSpeed
	}
	if !IsNil(o.Described) {
		toSerialize["described"] = o.Described
	}
	if !IsNil(o.PositiveReviews) {
		toSerialize["positive_reviews"] = o.PositiveReviews
	}
	if !IsNil(o.Followers) {
		toSerialize["followers"] = o.Followers
	}
	if !IsNil(o.SixMonthSales) {
		toSerialize["six_month_sales"] = o.SixMonthSales
	}
	if !IsNil(o.RegularBuyers) {
		toSerialize["regular_buyers"] = o.RegularBuyers
	}
	if !IsNil(o.StoreAge) {
		toSerialize["store_age"] = o.StoreAge
	}
	if !IsNil(o.IsOnSale) {
		toSerialize["is_on_sale"] = o.IsOnSale
	}
	if o.SaleStartsAt.IsSet() {
		toSerialize["sale_starts_at"] = o.SaleStartsAt.Get()
	}
	if o.SaleEndsAt.IsSet() {
		toSerialize["sale_ends_at"] = o.SaleEndsAt.Get()
	}
	if !IsNil(o.BusinessLicenseUrl) {
		toSerialize["business_license_url"] = o.BusinessLicenseUrl
	}
	if !IsNil(o.StoreCategories) {
		toSerialize["store_categories"] = o.StoreCategories
	}
	if !IsNil(o.Spider) {
		toSerialize["spider"] = o.Spider
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updated_at"] = o.UpdatedAt
	}
	return toSerialize, nil
}

type NullableSellerItem struct {
	value *SellerItem
	isSet bool
}

func (v NullableSellerItem) Get() *SellerItem {
	return v.value
}

func (v *NullableSellerItem) Set(val *SellerItem) {
	v.value = val
	v.isSet = true
}

func (v NullableSellerItem) IsSet() bool {
	return v.isSet
}

func (v *NullableSellerItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSellerItem(val *SellerItem) *NullableSellerItem {
	return &NullableSellerItem{value: val, isSet: true}
}

func (v NullableSellerItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSellerItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


