/*
AliExpress Parser API

Real-time AliExpress data parser covering products, product reviews, sellers, store coupons, a seller's product catalog, and product search by text or image. Products: pricing, stock status, shipping options, seller information, product configurations (SKUs), and more - scoped to a specific country and currency. Reviews: customer ratings and feedback for a product. Sellers: full store profile with ratings, feedback, and categories. Coupons: active seller coupon codes with discounts, thresholds, budgets, and expiry. Seller products: a store's product catalog, paginated and best-selling first. Search: find products by keyword or by uploading an image, returning paginated product results with their categories. 

API version: 2.1.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aligate

import (
	"encoding/json"
)

// checks if the ProductConfiguration type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProductConfiguration{}

// ProductConfiguration A single SKU variant (e.g. a specific color/size combination)
type ProductConfiguration struct {
	Id *int64 `json:"id,omitempty"`
	ProductId *int64 `json:"product_id,omitempty"`
	SkuId *string `json:"sku_id,omitempty"`
	SkuAttribute *string `json:"sku_attribute,omitempty"`
	Properties []ConfigurationProperty `json:"properties,omitempty"`
	Image *string `json:"image,omitempty"`
	Price *ConfigurationPrice `json:"price,omitempty"`
}

// NewProductConfiguration instantiates a new ProductConfiguration object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProductConfiguration() *ProductConfiguration {
	this := ProductConfiguration{}
	return &this
}

// NewProductConfigurationWithDefaults instantiates a new ProductConfiguration object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProductConfigurationWithDefaults() *ProductConfiguration {
	this := ProductConfiguration{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ProductConfiguration) GetId() int64 {
	if o == nil || IsNil(o.Id) {
		var ret int64
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductConfiguration) GetIdOk() (*int64, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ProductConfiguration) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int64 and assigns it to the Id field.
func (o *ProductConfiguration) SetId(v int64) {
	o.Id = &v
}

// GetProductId returns the ProductId field value if set, zero value otherwise.
func (o *ProductConfiguration) GetProductId() int64 {
	if o == nil || IsNil(o.ProductId) {
		var ret int64
		return ret
	}
	return *o.ProductId
}

// GetProductIdOk returns a tuple with the ProductId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductConfiguration) GetProductIdOk() (*int64, bool) {
	if o == nil || IsNil(o.ProductId) {
		return nil, false
	}
	return o.ProductId, true
}

// HasProductId returns a boolean if a field has been set.
func (o *ProductConfiguration) HasProductId() bool {
	if o != nil && !IsNil(o.ProductId) {
		return true
	}

	return false
}

// SetProductId gets a reference to the given int64 and assigns it to the ProductId field.
func (o *ProductConfiguration) SetProductId(v int64) {
	o.ProductId = &v
}

// GetSkuId returns the SkuId field value if set, zero value otherwise.
func (o *ProductConfiguration) GetSkuId() string {
	if o == nil || IsNil(o.SkuId) {
		var ret string
		return ret
	}
	return *o.SkuId
}

// GetSkuIdOk returns a tuple with the SkuId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductConfiguration) GetSkuIdOk() (*string, bool) {
	if o == nil || IsNil(o.SkuId) {
		return nil, false
	}
	return o.SkuId, true
}

// HasSkuId returns a boolean if a field has been set.
func (o *ProductConfiguration) HasSkuId() bool {
	if o != nil && !IsNil(o.SkuId) {
		return true
	}

	return false
}

// SetSkuId gets a reference to the given string and assigns it to the SkuId field.
func (o *ProductConfiguration) SetSkuId(v string) {
	o.SkuId = &v
}

// GetSkuAttribute returns the SkuAttribute field value if set, zero value otherwise.
func (o *ProductConfiguration) GetSkuAttribute() string {
	if o == nil || IsNil(o.SkuAttribute) {
		var ret string
		return ret
	}
	return *o.SkuAttribute
}

// GetSkuAttributeOk returns a tuple with the SkuAttribute field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductConfiguration) GetSkuAttributeOk() (*string, bool) {
	if o == nil || IsNil(o.SkuAttribute) {
		return nil, false
	}
	return o.SkuAttribute, true
}

// HasSkuAttribute returns a boolean if a field has been set.
func (o *ProductConfiguration) HasSkuAttribute() bool {
	if o != nil && !IsNil(o.SkuAttribute) {
		return true
	}

	return false
}

// SetSkuAttribute gets a reference to the given string and assigns it to the SkuAttribute field.
func (o *ProductConfiguration) SetSkuAttribute(v string) {
	o.SkuAttribute = &v
}

// GetProperties returns the Properties field value if set, zero value otherwise.
func (o *ProductConfiguration) GetProperties() []ConfigurationProperty {
	if o == nil || IsNil(o.Properties) {
		var ret []ConfigurationProperty
		return ret
	}
	return o.Properties
}

// GetPropertiesOk returns a tuple with the Properties field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductConfiguration) GetPropertiesOk() ([]ConfigurationProperty, bool) {
	if o == nil || IsNil(o.Properties) {
		return nil, false
	}
	return o.Properties, true
}

// HasProperties returns a boolean if a field has been set.
func (o *ProductConfiguration) HasProperties() bool {
	if o != nil && !IsNil(o.Properties) {
		return true
	}

	return false
}

// SetProperties gets a reference to the given []ConfigurationProperty and assigns it to the Properties field.
func (o *ProductConfiguration) SetProperties(v []ConfigurationProperty) {
	o.Properties = v
}

// GetImage returns the Image field value if set, zero value otherwise.
func (o *ProductConfiguration) GetImage() string {
	if o == nil || IsNil(o.Image) {
		var ret string
		return ret
	}
	return *o.Image
}

// GetImageOk returns a tuple with the Image field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductConfiguration) GetImageOk() (*string, bool) {
	if o == nil || IsNil(o.Image) {
		return nil, false
	}
	return o.Image, true
}

// HasImage returns a boolean if a field has been set.
func (o *ProductConfiguration) HasImage() bool {
	if o != nil && !IsNil(o.Image) {
		return true
	}

	return false
}

// SetImage gets a reference to the given string and assigns it to the Image field.
func (o *ProductConfiguration) SetImage(v string) {
	o.Image = &v
}

// GetPrice returns the Price field value if set, zero value otherwise.
func (o *ProductConfiguration) GetPrice() ConfigurationPrice {
	if o == nil || IsNil(o.Price) {
		var ret ConfigurationPrice
		return ret
	}
	return *o.Price
}

// GetPriceOk returns a tuple with the Price field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductConfiguration) GetPriceOk() (*ConfigurationPrice, bool) {
	if o == nil || IsNil(o.Price) {
		return nil, false
	}
	return o.Price, true
}

// HasPrice returns a boolean if a field has been set.
func (o *ProductConfiguration) HasPrice() bool {
	if o != nil && !IsNil(o.Price) {
		return true
	}

	return false
}

// SetPrice gets a reference to the given ConfigurationPrice and assigns it to the Price field.
func (o *ProductConfiguration) SetPrice(v ConfigurationPrice) {
	o.Price = &v
}

func (o ProductConfiguration) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProductConfiguration) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.ProductId) {
		toSerialize["product_id"] = o.ProductId
	}
	if !IsNil(o.SkuId) {
		toSerialize["sku_id"] = o.SkuId
	}
	if !IsNil(o.SkuAttribute) {
		toSerialize["sku_attribute"] = o.SkuAttribute
	}
	if !IsNil(o.Properties) {
		toSerialize["properties"] = o.Properties
	}
	if !IsNil(o.Image) {
		toSerialize["image"] = o.Image
	}
	if !IsNil(o.Price) {
		toSerialize["price"] = o.Price
	}
	return toSerialize, nil
}

type NullableProductConfiguration struct {
	value *ProductConfiguration
	isSet bool
}

func (v NullableProductConfiguration) Get() *ProductConfiguration {
	return v.value
}

func (v *NullableProductConfiguration) Set(val *ProductConfiguration) {
	v.value = val
	v.isSet = true
}

func (v NullableProductConfiguration) IsSet() bool {
	return v.isSet
}

func (v *NullableProductConfiguration) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProductConfiguration(val *ProductConfiguration) *NullableProductConfiguration {
	return &NullableProductConfiguration{value: val, isSet: true}
}

func (v NullableProductConfiguration) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProductConfiguration) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


