/*
AliExpress Parser API

Real-time AliExpress data parser covering products, product reviews, sellers, store coupons, a seller's product catalog, and product search by text or image. Products: pricing, stock status, shipping options, seller information, product configurations (SKUs), and more - scoped to a specific country and currency. Reviews: customer ratings and feedback for a product. Sellers: full store profile with ratings, feedback, and categories. Coupons: active seller coupon codes with discounts, thresholds, budgets, and expiry. Seller products: a store's product catalog, paginated and best-selling first. Search: find products by keyword or by uploading an image, returning paginated product results with their categories. 

API version: 2.1.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aligate

import (
	"encoding/json"
)

// checks if the ParseResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ParseResponse{}

// ParseResponse Top-level response envelope returned by the gateway
type ParseResponse struct {
	Meta *ParseMeta `json:"meta,omitempty"`
	Settings *ParseSettings `json:"settings,omitempty"`
	Item *Product `json:"item,omitempty"`
}

// NewParseResponse instantiates a new ParseResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewParseResponse() *ParseResponse {
	this := ParseResponse{}
	return &this
}

// NewParseResponseWithDefaults instantiates a new ParseResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewParseResponseWithDefaults() *ParseResponse {
	this := ParseResponse{}
	return &this
}

// GetMeta returns the Meta field value if set, zero value otherwise.
func (o *ParseResponse) GetMeta() ParseMeta {
	if o == nil || IsNil(o.Meta) {
		var ret ParseMeta
		return ret
	}
	return *o.Meta
}

// GetMetaOk returns a tuple with the Meta field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ParseResponse) GetMetaOk() (*ParseMeta, bool) {
	if o == nil || IsNil(o.Meta) {
		return nil, false
	}
	return o.Meta, true
}

// HasMeta returns a boolean if a field has been set.
func (o *ParseResponse) HasMeta() bool {
	if o != nil && !IsNil(o.Meta) {
		return true
	}

	return false
}

// SetMeta gets a reference to the given ParseMeta and assigns it to the Meta field.
func (o *ParseResponse) SetMeta(v ParseMeta) {
	o.Meta = &v
}

// GetSettings returns the Settings field value if set, zero value otherwise.
func (o *ParseResponse) GetSettings() ParseSettings {
	if o == nil || IsNil(o.Settings) {
		var ret ParseSettings
		return ret
	}
	return *o.Settings
}

// GetSettingsOk returns a tuple with the Settings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ParseResponse) GetSettingsOk() (*ParseSettings, bool) {
	if o == nil || IsNil(o.Settings) {
		return nil, false
	}
	return o.Settings, true
}

// HasSettings returns a boolean if a field has been set.
func (o *ParseResponse) HasSettings() bool {
	if o != nil && !IsNil(o.Settings) {
		return true
	}

	return false
}

// SetSettings gets a reference to the given ParseSettings and assigns it to the Settings field.
func (o *ParseResponse) SetSettings(v ParseSettings) {
	o.Settings = &v
}

// GetItem returns the Item field value if set, zero value otherwise.
func (o *ParseResponse) GetItem() Product {
	if o == nil || IsNil(o.Item) {
		var ret Product
		return ret
	}
	return *o.Item
}

// GetItemOk returns a tuple with the Item field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ParseResponse) GetItemOk() (*Product, bool) {
	if o == nil || IsNil(o.Item) {
		return nil, false
	}
	return o.Item, true
}

// HasItem returns a boolean if a field has been set.
func (o *ParseResponse) HasItem() bool {
	if o != nil && !IsNil(o.Item) {
		return true
	}

	return false
}

// SetItem gets a reference to the given Product and assigns it to the Item field.
func (o *ParseResponse) SetItem(v Product) {
	o.Item = &v
}

func (o ParseResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ParseResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Meta) {
		toSerialize["meta"] = o.Meta
	}
	if !IsNil(o.Settings) {
		toSerialize["settings"] = o.Settings
	}
	if !IsNil(o.Item) {
		toSerialize["item"] = o.Item
	}
	return toSerialize, nil
}

type NullableParseResponse struct {
	value *ParseResponse
	isSet bool
}

func (v NullableParseResponse) Get() *ParseResponse {
	return v.value
}

func (v *NullableParseResponse) Set(val *ParseResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableParseResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableParseResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableParseResponse(val *ParseResponse) *NullableParseResponse {
	return &NullableParseResponse{value: val, isSet: true}
}

func (v NullableParseResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableParseResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


