/*
AliExpress Parser API

Real-time AliExpress data parser covering products, product reviews, sellers, store coupons, a seller's product catalog, and product search by text or image. Products: pricing, stock status, shipping options, seller information, product configurations (SKUs), and more - scoped to a specific country and currency. Reviews: customer ratings and feedback for a product. Sellers: full store profile with ratings, feedback, and categories. Coupons: active seller coupon codes with discounts, thresholds, budgets, and expiry. Seller products: a store's product catalog, paginated and best-selling first. Search: find products by keyword or by uploading an image, returning paginated product results with their categories. 

API version: 2.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aligate

import (
	"encoding/json"
)

// checks if the ReviewBuyer type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ReviewBuyer{}

// ReviewBuyer The review author
type ReviewBuyer struct {
	Name *string `json:"name,omitempty"`
	Gender *string `json:"gender,omitempty"`
	ProfileImage *string `json:"profile_image,omitempty"`
	Country *string `json:"country,omitempty"`
}

// NewReviewBuyer instantiates a new ReviewBuyer object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewReviewBuyer() *ReviewBuyer {
	this := ReviewBuyer{}
	return &this
}

// NewReviewBuyerWithDefaults instantiates a new ReviewBuyer object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewReviewBuyerWithDefaults() *ReviewBuyer {
	this := ReviewBuyer{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ReviewBuyer) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReviewBuyer) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ReviewBuyer) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ReviewBuyer) SetName(v string) {
	o.Name = &v
}

// GetGender returns the Gender field value if set, zero value otherwise.
func (o *ReviewBuyer) GetGender() string {
	if o == nil || IsNil(o.Gender) {
		var ret string
		return ret
	}
	return *o.Gender
}

// GetGenderOk returns a tuple with the Gender field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReviewBuyer) GetGenderOk() (*string, bool) {
	if o == nil || IsNil(o.Gender) {
		return nil, false
	}
	return o.Gender, true
}

// HasGender returns a boolean if a field has been set.
func (o *ReviewBuyer) HasGender() bool {
	if o != nil && !IsNil(o.Gender) {
		return true
	}

	return false
}

// SetGender gets a reference to the given string and assigns it to the Gender field.
func (o *ReviewBuyer) SetGender(v string) {
	o.Gender = &v
}

// GetProfileImage returns the ProfileImage field value if set, zero value otherwise.
func (o *ReviewBuyer) GetProfileImage() string {
	if o == nil || IsNil(o.ProfileImage) {
		var ret string
		return ret
	}
	return *o.ProfileImage
}

// GetProfileImageOk returns a tuple with the ProfileImage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReviewBuyer) GetProfileImageOk() (*string, bool) {
	if o == nil || IsNil(o.ProfileImage) {
		return nil, false
	}
	return o.ProfileImage, true
}

// HasProfileImage returns a boolean if a field has been set.
func (o *ReviewBuyer) HasProfileImage() bool {
	if o != nil && !IsNil(o.ProfileImage) {
		return true
	}

	return false
}

// SetProfileImage gets a reference to the given string and assigns it to the ProfileImage field.
func (o *ReviewBuyer) SetProfileImage(v string) {
	o.ProfileImage = &v
}

// GetCountry returns the Country field value if set, zero value otherwise.
func (o *ReviewBuyer) GetCountry() string {
	if o == nil || IsNil(o.Country) {
		var ret string
		return ret
	}
	return *o.Country
}

// GetCountryOk returns a tuple with the Country field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReviewBuyer) GetCountryOk() (*string, bool) {
	if o == nil || IsNil(o.Country) {
		return nil, false
	}
	return o.Country, true
}

// HasCountry returns a boolean if a field has been set.
func (o *ReviewBuyer) HasCountry() bool {
	if o != nil && !IsNil(o.Country) {
		return true
	}

	return false
}

// SetCountry gets a reference to the given string and assigns it to the Country field.
func (o *ReviewBuyer) SetCountry(v string) {
	o.Country = &v
}

func (o ReviewBuyer) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ReviewBuyer) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Gender) {
		toSerialize["gender"] = o.Gender
	}
	if !IsNil(o.ProfileImage) {
		toSerialize["profile_image"] = o.ProfileImage
	}
	if !IsNil(o.Country) {
		toSerialize["country"] = o.Country
	}
	return toSerialize, nil
}

type NullableReviewBuyer struct {
	value *ReviewBuyer
	isSet bool
}

func (v NullableReviewBuyer) Get() *ReviewBuyer {
	return v.value
}

func (v *NullableReviewBuyer) Set(val *ReviewBuyer) {
	v.value = val
	v.isSet = true
}

func (v NullableReviewBuyer) IsSet() bool {
	return v.isSet
}

func (v *NullableReviewBuyer) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableReviewBuyer(val *ReviewBuyer) *NullableReviewBuyer {
	return &NullableReviewBuyer{value: val, isSet: true}
}

func (v NullableReviewBuyer) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableReviewBuyer) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


