/*
AliExpress Parser API

Real-time AliExpress data parser covering products, product reviews, sellers, store coupons, a seller's product catalog, and product search by text or image. Products: pricing, stock status, shipping options, seller information, product configurations (SKUs), and more - scoped to a specific country and currency. Reviews: customer ratings and feedback for a product. Sellers: full store profile with ratings, feedback, and categories. Coupons: active seller coupon codes with discounts, thresholds, budgets, and expiry. Seller products: a store's product catalog, paginated and best-selling first. Search: find products by keyword or by uploading an image, returning paginated product results with their categories. 

API version: 2.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aligate

import (
	"encoding/json"
)

// checks if the ImageSearchParseResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ImageSearchParseResponse{}

// ImageSearchParseResponse Top-level response envelope returned by the gateway for image-search requests
type ImageSearchParseResponse struct {
	Meta *ImageSearchMeta `json:"meta,omitempty"`
	Settings *ImageSearchSettings `json:"settings,omitempty"`
	Item *SearchResult `json:"item,omitempty"`
}

// NewImageSearchParseResponse instantiates a new ImageSearchParseResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewImageSearchParseResponse() *ImageSearchParseResponse {
	this := ImageSearchParseResponse{}
	return &this
}

// NewImageSearchParseResponseWithDefaults instantiates a new ImageSearchParseResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewImageSearchParseResponseWithDefaults() *ImageSearchParseResponse {
	this := ImageSearchParseResponse{}
	return &this
}

// GetMeta returns the Meta field value if set, zero value otherwise.
func (o *ImageSearchParseResponse) GetMeta() ImageSearchMeta {
	if o == nil || IsNil(o.Meta) {
		var ret ImageSearchMeta
		return ret
	}
	return *o.Meta
}

// GetMetaOk returns a tuple with the Meta field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ImageSearchParseResponse) GetMetaOk() (*ImageSearchMeta, bool) {
	if o == nil || IsNil(o.Meta) {
		return nil, false
	}
	return o.Meta, true
}

// HasMeta returns a boolean if a field has been set.
func (o *ImageSearchParseResponse) HasMeta() bool {
	if o != nil && !IsNil(o.Meta) {
		return true
	}

	return false
}

// SetMeta gets a reference to the given ImageSearchMeta and assigns it to the Meta field.
func (o *ImageSearchParseResponse) SetMeta(v ImageSearchMeta) {
	o.Meta = &v
}

// GetSettings returns the Settings field value if set, zero value otherwise.
func (o *ImageSearchParseResponse) GetSettings() ImageSearchSettings {
	if o == nil || IsNil(o.Settings) {
		var ret ImageSearchSettings
		return ret
	}
	return *o.Settings
}

// GetSettingsOk returns a tuple with the Settings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ImageSearchParseResponse) GetSettingsOk() (*ImageSearchSettings, bool) {
	if o == nil || IsNil(o.Settings) {
		return nil, false
	}
	return o.Settings, true
}

// HasSettings returns a boolean if a field has been set.
func (o *ImageSearchParseResponse) HasSettings() bool {
	if o != nil && !IsNil(o.Settings) {
		return true
	}

	return false
}

// SetSettings gets a reference to the given ImageSearchSettings and assigns it to the Settings field.
func (o *ImageSearchParseResponse) SetSettings(v ImageSearchSettings) {
	o.Settings = &v
}

// GetItem returns the Item field value if set, zero value otherwise.
func (o *ImageSearchParseResponse) GetItem() SearchResult {
	if o == nil || IsNil(o.Item) {
		var ret SearchResult
		return ret
	}
	return *o.Item
}

// GetItemOk returns a tuple with the Item field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ImageSearchParseResponse) GetItemOk() (*SearchResult, bool) {
	if o == nil || IsNil(o.Item) {
		return nil, false
	}
	return o.Item, true
}

// HasItem returns a boolean if a field has been set.
func (o *ImageSearchParseResponse) HasItem() bool {
	if o != nil && !IsNil(o.Item) {
		return true
	}

	return false
}

// SetItem gets a reference to the given SearchResult and assigns it to the Item field.
func (o *ImageSearchParseResponse) SetItem(v SearchResult) {
	o.Item = &v
}

func (o ImageSearchParseResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ImageSearchParseResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Meta) {
		toSerialize["meta"] = o.Meta
	}
	if !IsNil(o.Settings) {
		toSerialize["settings"] = o.Settings
	}
	if !IsNil(o.Item) {
		toSerialize["item"] = o.Item
	}
	return toSerialize, nil
}

type NullableImageSearchParseResponse struct {
	value *ImageSearchParseResponse
	isSet bool
}

func (v NullableImageSearchParseResponse) Get() *ImageSearchParseResponse {
	return v.value
}

func (v *NullableImageSearchParseResponse) Set(val *ImageSearchParseResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableImageSearchParseResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableImageSearchParseResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableImageSearchParseResponse(val *ImageSearchParseResponse) *NullableImageSearchParseResponse {
	return &NullableImageSearchParseResponse{value: val, isSet: true}
}

func (v NullableImageSearchParseResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableImageSearchParseResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


