/*
AliExpress Parser API

Real-time AliExpress data parser covering products, product reviews, sellers, store coupons, a seller's product catalog, and product search by text or image. Products: pricing, stock status, shipping options, seller information, product configurations (SKUs), and more - scoped to a specific country and currency. Reviews: customer ratings and feedback for a product. Sellers: full store profile with ratings, feedback, and categories. Coupons: active seller coupon codes with discounts, thresholds, budgets, and expiry. Seller products: a store's product catalog, paginated and best-selling first. Search: find products by keyword or by uploading an image, returning paginated product results with their categories. 

API version: 2.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aligate

import (
	"encoding/json"
)

// checks if the SellerParseResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SellerParseResponse{}

// SellerParseResponse Top-level response envelope returned by the gateway for seller requests
type SellerParseResponse struct {
	Meta *SellerMeta `json:"meta,omitempty"`
	Settings *SellerSettings `json:"settings,omitempty"`
	Item *SellerItem `json:"item,omitempty"`
}

// NewSellerParseResponse instantiates a new SellerParseResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSellerParseResponse() *SellerParseResponse {
	this := SellerParseResponse{}
	return &this
}

// NewSellerParseResponseWithDefaults instantiates a new SellerParseResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSellerParseResponseWithDefaults() *SellerParseResponse {
	this := SellerParseResponse{}
	return &this
}

// GetMeta returns the Meta field value if set, zero value otherwise.
func (o *SellerParseResponse) GetMeta() SellerMeta {
	if o == nil || IsNil(o.Meta) {
		var ret SellerMeta
		return ret
	}
	return *o.Meta
}

// GetMetaOk returns a tuple with the Meta field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SellerParseResponse) GetMetaOk() (*SellerMeta, bool) {
	if o == nil || IsNil(o.Meta) {
		return nil, false
	}
	return o.Meta, true
}

// HasMeta returns a boolean if a field has been set.
func (o *SellerParseResponse) HasMeta() bool {
	if o != nil && !IsNil(o.Meta) {
		return true
	}

	return false
}

// SetMeta gets a reference to the given SellerMeta and assigns it to the Meta field.
func (o *SellerParseResponse) SetMeta(v SellerMeta) {
	o.Meta = &v
}

// GetSettings returns the Settings field value if set, zero value otherwise.
func (o *SellerParseResponse) GetSettings() SellerSettings {
	if o == nil || IsNil(o.Settings) {
		var ret SellerSettings
		return ret
	}
	return *o.Settings
}

// GetSettingsOk returns a tuple with the Settings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SellerParseResponse) GetSettingsOk() (*SellerSettings, bool) {
	if o == nil || IsNil(o.Settings) {
		return nil, false
	}
	return o.Settings, true
}

// HasSettings returns a boolean if a field has been set.
func (o *SellerParseResponse) HasSettings() bool {
	if o != nil && !IsNil(o.Settings) {
		return true
	}

	return false
}

// SetSettings gets a reference to the given SellerSettings and assigns it to the Settings field.
func (o *SellerParseResponse) SetSettings(v SellerSettings) {
	o.Settings = &v
}

// GetItem returns the Item field value if set, zero value otherwise.
func (o *SellerParseResponse) GetItem() SellerItem {
	if o == nil || IsNil(o.Item) {
		var ret SellerItem
		return ret
	}
	return *o.Item
}

// GetItemOk returns a tuple with the Item field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SellerParseResponse) GetItemOk() (*SellerItem, bool) {
	if o == nil || IsNil(o.Item) {
		return nil, false
	}
	return o.Item, true
}

// HasItem returns a boolean if a field has been set.
func (o *SellerParseResponse) HasItem() bool {
	if o != nil && !IsNil(o.Item) {
		return true
	}

	return false
}

// SetItem gets a reference to the given SellerItem and assigns it to the Item field.
func (o *SellerParseResponse) SetItem(v SellerItem) {
	o.Item = &v
}

func (o SellerParseResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SellerParseResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Meta) {
		toSerialize["meta"] = o.Meta
	}
	if !IsNil(o.Settings) {
		toSerialize["settings"] = o.Settings
	}
	if !IsNil(o.Item) {
		toSerialize["item"] = o.Item
	}
	return toSerialize, nil
}

type NullableSellerParseResponse struct {
	value *SellerParseResponse
	isSet bool
}

func (v NullableSellerParseResponse) Get() *SellerParseResponse {
	return v.value
}

func (v *NullableSellerParseResponse) Set(val *SellerParseResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableSellerParseResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableSellerParseResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSellerParseResponse(val *SellerParseResponse) *NullableSellerParseResponse {
	return &NullableSellerParseResponse{value: val, isSet: true}
}

func (v NullableSellerParseResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSellerParseResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


