/*
AliExpress Parser API

Real-time AliExpress data parser covering products, product reviews, sellers, store coupons, a seller's product catalog, product shipping, product descriptions, and product search by text or image. Products: pricing, stock status, shipping options, seller information, product configurations (SKUs), and more - scoped to a specific country and currency. Reviews: customer ratings and feedback for a product. Sellers: full store profile with ratings, feedback, and categories. Coupons: active seller coupon codes with discounts, thresholds, budgets, and expiry. Seller products: a store's product catalog, paginated and best-selling first. Shipping: shipping methods for a product with cost, carrier, and delivery estimate. Description: a product's long-form description on its own - HTML, plain text, and the images extracted from the description gallery. Search: find products by keyword or by uploading an image, returning paginated product results with their categories. 

API version: 2.7.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aligate

import (
	"encoding/json"
)

// checks if the DescriptionParseResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DescriptionParseResponse{}

// DescriptionParseResponse Top-level response envelope returned by the gateway for description requests
type DescriptionParseResponse struct {
	Meta *ParseMeta `json:"meta,omitempty"`
	Settings *DescriptionSettings `json:"settings,omitempty"`
	Item *ProductDescription `json:"item,omitempty"`
}

// NewDescriptionParseResponse instantiates a new DescriptionParseResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDescriptionParseResponse() *DescriptionParseResponse {
	this := DescriptionParseResponse{}
	return &this
}

// NewDescriptionParseResponseWithDefaults instantiates a new DescriptionParseResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDescriptionParseResponseWithDefaults() *DescriptionParseResponse {
	this := DescriptionParseResponse{}
	return &this
}

// GetMeta returns the Meta field value if set, zero value otherwise.
func (o *DescriptionParseResponse) GetMeta() ParseMeta {
	if o == nil || IsNil(o.Meta) {
		var ret ParseMeta
		return ret
	}
	return *o.Meta
}

// GetMetaOk returns a tuple with the Meta field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DescriptionParseResponse) GetMetaOk() (*ParseMeta, bool) {
	if o == nil || IsNil(o.Meta) {
		return nil, false
	}
	return o.Meta, true
}

// HasMeta returns a boolean if a field has been set.
func (o *DescriptionParseResponse) HasMeta() bool {
	if o != nil && !IsNil(o.Meta) {
		return true
	}

	return false
}

// SetMeta gets a reference to the given ParseMeta and assigns it to the Meta field.
func (o *DescriptionParseResponse) SetMeta(v ParseMeta) {
	o.Meta = &v
}

// GetSettings returns the Settings field value if set, zero value otherwise.
func (o *DescriptionParseResponse) GetSettings() DescriptionSettings {
	if o == nil || IsNil(o.Settings) {
		var ret DescriptionSettings
		return ret
	}
	return *o.Settings
}

// GetSettingsOk returns a tuple with the Settings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DescriptionParseResponse) GetSettingsOk() (*DescriptionSettings, bool) {
	if o == nil || IsNil(o.Settings) {
		return nil, false
	}
	return o.Settings, true
}

// HasSettings returns a boolean if a field has been set.
func (o *DescriptionParseResponse) HasSettings() bool {
	if o != nil && !IsNil(o.Settings) {
		return true
	}

	return false
}

// SetSettings gets a reference to the given DescriptionSettings and assigns it to the Settings field.
func (o *DescriptionParseResponse) SetSettings(v DescriptionSettings) {
	o.Settings = &v
}

// GetItem returns the Item field value if set, zero value otherwise.
func (o *DescriptionParseResponse) GetItem() ProductDescription {
	if o == nil || IsNil(o.Item) {
		var ret ProductDescription
		return ret
	}
	return *o.Item
}

// GetItemOk returns a tuple with the Item field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DescriptionParseResponse) GetItemOk() (*ProductDescription, bool) {
	if o == nil || IsNil(o.Item) {
		return nil, false
	}
	return o.Item, true
}

// HasItem returns a boolean if a field has been set.
func (o *DescriptionParseResponse) HasItem() bool {
	if o != nil && !IsNil(o.Item) {
		return true
	}

	return false
}

// SetItem gets a reference to the given ProductDescription and assigns it to the Item field.
func (o *DescriptionParseResponse) SetItem(v ProductDescription) {
	o.Item = &v
}

func (o DescriptionParseResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DescriptionParseResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Meta) {
		toSerialize["meta"] = o.Meta
	}
	if !IsNil(o.Settings) {
		toSerialize["settings"] = o.Settings
	}
	if !IsNil(o.Item) {
		toSerialize["item"] = o.Item
	}
	return toSerialize, nil
}

type NullableDescriptionParseResponse struct {
	value *DescriptionParseResponse
	isSet bool
}

func (v NullableDescriptionParseResponse) Get() *DescriptionParseResponse {
	return v.value
}

func (v *NullableDescriptionParseResponse) Set(val *DescriptionParseResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableDescriptionParseResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableDescriptionParseResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDescriptionParseResponse(val *DescriptionParseResponse) *NullableDescriptionParseResponse {
	return &NullableDescriptionParseResponse{value: val, isSet: true}
}

func (v NullableDescriptionParseResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDescriptionParseResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


