/*
AliExpress Parser API

Real-time AliExpress data parser covering products, product reviews, sellers, store coupons, a seller's product catalog, and product search by text or image. Products: pricing, stock status, shipping options, seller information, product configurations (SKUs), and more - scoped to a specific country and currency. Reviews: customer ratings and feedback for a product. Sellers: full store profile with ratings, feedback, and categories. Coupons: active seller coupon codes with discounts, thresholds, budgets, and expiry. Seller products: a store's product catalog, paginated and best-selling first. Search: find products by keyword or by uploading an image, returning paginated product results with their categories. 

API version: 2.1.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aligate

import (
	"encoding/json"
)

// checks if the StoreCategory type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StoreCategory{}

// StoreCategory struct for StoreCategory
type StoreCategory struct {
	// Category display name
	Name *string `json:"name,omitempty"`
	// AliExpress category group identifier
	GroupId *string `json:"group_id,omitempty"`
	// Direct URL to this category page
	Url *string `json:"url,omitempty"`
	// Nested sub-categories (omitted if none)
	SubCategories []StoreCategory `json:"sub_categories,omitempty"`
}

// NewStoreCategory instantiates a new StoreCategory object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStoreCategory() *StoreCategory {
	this := StoreCategory{}
	return &this
}

// NewStoreCategoryWithDefaults instantiates a new StoreCategory object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStoreCategoryWithDefaults() *StoreCategory {
	this := StoreCategory{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *StoreCategory) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StoreCategory) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *StoreCategory) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *StoreCategory) SetName(v string) {
	o.Name = &v
}

// GetGroupId returns the GroupId field value if set, zero value otherwise.
func (o *StoreCategory) GetGroupId() string {
	if o == nil || IsNil(o.GroupId) {
		var ret string
		return ret
	}
	return *o.GroupId
}

// GetGroupIdOk returns a tuple with the GroupId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StoreCategory) GetGroupIdOk() (*string, bool) {
	if o == nil || IsNil(o.GroupId) {
		return nil, false
	}
	return o.GroupId, true
}

// HasGroupId returns a boolean if a field has been set.
func (o *StoreCategory) HasGroupId() bool {
	if o != nil && !IsNil(o.GroupId) {
		return true
	}

	return false
}

// SetGroupId gets a reference to the given string and assigns it to the GroupId field.
func (o *StoreCategory) SetGroupId(v string) {
	o.GroupId = &v
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *StoreCategory) GetUrl() string {
	if o == nil || IsNil(o.Url) {
		var ret string
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StoreCategory) GetUrlOk() (*string, bool) {
	if o == nil || IsNil(o.Url) {
		return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *StoreCategory) HasUrl() bool {
	if o != nil && !IsNil(o.Url) {
		return true
	}

	return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *StoreCategory) SetUrl(v string) {
	o.Url = &v
}

// GetSubCategories returns the SubCategories field value if set, zero value otherwise.
func (o *StoreCategory) GetSubCategories() []StoreCategory {
	if o == nil || IsNil(o.SubCategories) {
		var ret []StoreCategory
		return ret
	}
	return o.SubCategories
}

// GetSubCategoriesOk returns a tuple with the SubCategories field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StoreCategory) GetSubCategoriesOk() ([]StoreCategory, bool) {
	if o == nil || IsNil(o.SubCategories) {
		return nil, false
	}
	return o.SubCategories, true
}

// HasSubCategories returns a boolean if a field has been set.
func (o *StoreCategory) HasSubCategories() bool {
	if o != nil && !IsNil(o.SubCategories) {
		return true
	}

	return false
}

// SetSubCategories gets a reference to the given []StoreCategory and assigns it to the SubCategories field.
func (o *StoreCategory) SetSubCategories(v []StoreCategory) {
	o.SubCategories = v
}

func (o StoreCategory) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StoreCategory) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.GroupId) {
		toSerialize["group_id"] = o.GroupId
	}
	if !IsNil(o.Url) {
		toSerialize["url"] = o.Url
	}
	if !IsNil(o.SubCategories) {
		toSerialize["sub_categories"] = o.SubCategories
	}
	return toSerialize, nil
}

type NullableStoreCategory struct {
	value *StoreCategory
	isSet bool
}

func (v NullableStoreCategory) Get() *StoreCategory {
	return v.value
}

func (v *NullableStoreCategory) Set(val *StoreCategory) {
	v.value = val
	v.isSet = true
}

func (v NullableStoreCategory) IsSet() bool {
	return v.isSet
}

func (v *NullableStoreCategory) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStoreCategory(val *StoreCategory) *NullableStoreCategory {
	return &NullableStoreCategory{value: val, isSet: true}
}

func (v NullableStoreCategory) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStoreCategory) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


