/*
AliExpress Parser API

Real-time AliExpress data parser covering products, product reviews, sellers, store coupons, a seller's product catalog, and product search by text or image. Products: pricing, stock status, shipping options, seller information, product configurations (SKUs), and more - scoped to a specific country and currency. Reviews: customer ratings and feedback for a product. Sellers: full store profile with ratings, feedback, and categories. Coupons: active seller coupon codes with discounts, thresholds, budgets, and expiry. Seller products: a store's product catalog, paginated and best-selling first. Search: find products by keyword or by uploading an image, returning paginated product results with their categories. 

API version: 2.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aligate

import (
	"encoding/json"
)

// checks if the ShippingMethod type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ShippingMethod{}

// ShippingMethod struct for ShippingMethod
type ShippingMethod struct {
	ServiceCode *string `json:"service_code,omitempty"`
	// Shipping cost (0 for free shipping)
	Value *float64 `json:"value,omitempty"`
	Currency *string `json:"currency,omitempty"`
	// Carrier name
	Company *string `json:"company,omitempty"`
	MinDays *int32 `json:"min_days,omitempty"`
	MaxDays *int32 `json:"max_days,omitempty"`
	// Origin country code
	ShippingFrom *string `json:"shipping_from,omitempty"`
	DeliveryDate *string `json:"delivery_date,omitempty"`
	GuaranteedDeliveryTime *int32 `json:"guaranteed_delivery_time,omitempty"`
	FreeShipping *bool `json:"free_shipping,omitempty"`
	Tracking *bool `json:"tracking,omitempty"`
}

// NewShippingMethod instantiates a new ShippingMethod object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewShippingMethod() *ShippingMethod {
	this := ShippingMethod{}
	return &this
}

// NewShippingMethodWithDefaults instantiates a new ShippingMethod object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewShippingMethodWithDefaults() *ShippingMethod {
	this := ShippingMethod{}
	return &this
}

// GetServiceCode returns the ServiceCode field value if set, zero value otherwise.
func (o *ShippingMethod) GetServiceCode() string {
	if o == nil || IsNil(o.ServiceCode) {
		var ret string
		return ret
	}
	return *o.ServiceCode
}

// GetServiceCodeOk returns a tuple with the ServiceCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ShippingMethod) GetServiceCodeOk() (*string, bool) {
	if o == nil || IsNil(o.ServiceCode) {
		return nil, false
	}
	return o.ServiceCode, true
}

// HasServiceCode returns a boolean if a field has been set.
func (o *ShippingMethod) HasServiceCode() bool {
	if o != nil && !IsNil(o.ServiceCode) {
		return true
	}

	return false
}

// SetServiceCode gets a reference to the given string and assigns it to the ServiceCode field.
func (o *ShippingMethod) SetServiceCode(v string) {
	o.ServiceCode = &v
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *ShippingMethod) GetValue() float64 {
	if o == nil || IsNil(o.Value) {
		var ret float64
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ShippingMethod) GetValueOk() (*float64, bool) {
	if o == nil || IsNil(o.Value) {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *ShippingMethod) HasValue() bool {
	if o != nil && !IsNil(o.Value) {
		return true
	}

	return false
}

// SetValue gets a reference to the given float64 and assigns it to the Value field.
func (o *ShippingMethod) SetValue(v float64) {
	o.Value = &v
}

// GetCurrency returns the Currency field value if set, zero value otherwise.
func (o *ShippingMethod) GetCurrency() string {
	if o == nil || IsNil(o.Currency) {
		var ret string
		return ret
	}
	return *o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ShippingMethod) GetCurrencyOk() (*string, bool) {
	if o == nil || IsNil(o.Currency) {
		return nil, false
	}
	return o.Currency, true
}

// HasCurrency returns a boolean if a field has been set.
func (o *ShippingMethod) HasCurrency() bool {
	if o != nil && !IsNil(o.Currency) {
		return true
	}

	return false
}

// SetCurrency gets a reference to the given string and assigns it to the Currency field.
func (o *ShippingMethod) SetCurrency(v string) {
	o.Currency = &v
}

// GetCompany returns the Company field value if set, zero value otherwise.
func (o *ShippingMethod) GetCompany() string {
	if o == nil || IsNil(o.Company) {
		var ret string
		return ret
	}
	return *o.Company
}

// GetCompanyOk returns a tuple with the Company field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ShippingMethod) GetCompanyOk() (*string, bool) {
	if o == nil || IsNil(o.Company) {
		return nil, false
	}
	return o.Company, true
}

// HasCompany returns a boolean if a field has been set.
func (o *ShippingMethod) HasCompany() bool {
	if o != nil && !IsNil(o.Company) {
		return true
	}

	return false
}

// SetCompany gets a reference to the given string and assigns it to the Company field.
func (o *ShippingMethod) SetCompany(v string) {
	o.Company = &v
}

// GetMinDays returns the MinDays field value if set, zero value otherwise.
func (o *ShippingMethod) GetMinDays() int32 {
	if o == nil || IsNil(o.MinDays) {
		var ret int32
		return ret
	}
	return *o.MinDays
}

// GetMinDaysOk returns a tuple with the MinDays field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ShippingMethod) GetMinDaysOk() (*int32, bool) {
	if o == nil || IsNil(o.MinDays) {
		return nil, false
	}
	return o.MinDays, true
}

// HasMinDays returns a boolean if a field has been set.
func (o *ShippingMethod) HasMinDays() bool {
	if o != nil && !IsNil(o.MinDays) {
		return true
	}

	return false
}

// SetMinDays gets a reference to the given int32 and assigns it to the MinDays field.
func (o *ShippingMethod) SetMinDays(v int32) {
	o.MinDays = &v
}

// GetMaxDays returns the MaxDays field value if set, zero value otherwise.
func (o *ShippingMethod) GetMaxDays() int32 {
	if o == nil || IsNil(o.MaxDays) {
		var ret int32
		return ret
	}
	return *o.MaxDays
}

// GetMaxDaysOk returns a tuple with the MaxDays field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ShippingMethod) GetMaxDaysOk() (*int32, bool) {
	if o == nil || IsNil(o.MaxDays) {
		return nil, false
	}
	return o.MaxDays, true
}

// HasMaxDays returns a boolean if a field has been set.
func (o *ShippingMethod) HasMaxDays() bool {
	if o != nil && !IsNil(o.MaxDays) {
		return true
	}

	return false
}

// SetMaxDays gets a reference to the given int32 and assigns it to the MaxDays field.
func (o *ShippingMethod) SetMaxDays(v int32) {
	o.MaxDays = &v
}

// GetShippingFrom returns the ShippingFrom field value if set, zero value otherwise.
func (o *ShippingMethod) GetShippingFrom() string {
	if o == nil || IsNil(o.ShippingFrom) {
		var ret string
		return ret
	}
	return *o.ShippingFrom
}

// GetShippingFromOk returns a tuple with the ShippingFrom field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ShippingMethod) GetShippingFromOk() (*string, bool) {
	if o == nil || IsNil(o.ShippingFrom) {
		return nil, false
	}
	return o.ShippingFrom, true
}

// HasShippingFrom returns a boolean if a field has been set.
func (o *ShippingMethod) HasShippingFrom() bool {
	if o != nil && !IsNil(o.ShippingFrom) {
		return true
	}

	return false
}

// SetShippingFrom gets a reference to the given string and assigns it to the ShippingFrom field.
func (o *ShippingMethod) SetShippingFrom(v string) {
	o.ShippingFrom = &v
}

// GetDeliveryDate returns the DeliveryDate field value if set, zero value otherwise.
func (o *ShippingMethod) GetDeliveryDate() string {
	if o == nil || IsNil(o.DeliveryDate) {
		var ret string
		return ret
	}
	return *o.DeliveryDate
}

// GetDeliveryDateOk returns a tuple with the DeliveryDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ShippingMethod) GetDeliveryDateOk() (*string, bool) {
	if o == nil || IsNil(o.DeliveryDate) {
		return nil, false
	}
	return o.DeliveryDate, true
}

// HasDeliveryDate returns a boolean if a field has been set.
func (o *ShippingMethod) HasDeliveryDate() bool {
	if o != nil && !IsNil(o.DeliveryDate) {
		return true
	}

	return false
}

// SetDeliveryDate gets a reference to the given string and assigns it to the DeliveryDate field.
func (o *ShippingMethod) SetDeliveryDate(v string) {
	o.DeliveryDate = &v
}

// GetGuaranteedDeliveryTime returns the GuaranteedDeliveryTime field value if set, zero value otherwise.
func (o *ShippingMethod) GetGuaranteedDeliveryTime() int32 {
	if o == nil || IsNil(o.GuaranteedDeliveryTime) {
		var ret int32
		return ret
	}
	return *o.GuaranteedDeliveryTime
}

// GetGuaranteedDeliveryTimeOk returns a tuple with the GuaranteedDeliveryTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ShippingMethod) GetGuaranteedDeliveryTimeOk() (*int32, bool) {
	if o == nil || IsNil(o.GuaranteedDeliveryTime) {
		return nil, false
	}
	return o.GuaranteedDeliveryTime, true
}

// HasGuaranteedDeliveryTime returns a boolean if a field has been set.
func (o *ShippingMethod) HasGuaranteedDeliveryTime() bool {
	if o != nil && !IsNil(o.GuaranteedDeliveryTime) {
		return true
	}

	return false
}

// SetGuaranteedDeliveryTime gets a reference to the given int32 and assigns it to the GuaranteedDeliveryTime field.
func (o *ShippingMethod) SetGuaranteedDeliveryTime(v int32) {
	o.GuaranteedDeliveryTime = &v
}

// GetFreeShipping returns the FreeShipping field value if set, zero value otherwise.
func (o *ShippingMethod) GetFreeShipping() bool {
	if o == nil || IsNil(o.FreeShipping) {
		var ret bool
		return ret
	}
	return *o.FreeShipping
}

// GetFreeShippingOk returns a tuple with the FreeShipping field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ShippingMethod) GetFreeShippingOk() (*bool, bool) {
	if o == nil || IsNil(o.FreeShipping) {
		return nil, false
	}
	return o.FreeShipping, true
}

// HasFreeShipping returns a boolean if a field has been set.
func (o *ShippingMethod) HasFreeShipping() bool {
	if o != nil && !IsNil(o.FreeShipping) {
		return true
	}

	return false
}

// SetFreeShipping gets a reference to the given bool and assigns it to the FreeShipping field.
func (o *ShippingMethod) SetFreeShipping(v bool) {
	o.FreeShipping = &v
}

// GetTracking returns the Tracking field value if set, zero value otherwise.
func (o *ShippingMethod) GetTracking() bool {
	if o == nil || IsNil(o.Tracking) {
		var ret bool
		return ret
	}
	return *o.Tracking
}

// GetTrackingOk returns a tuple with the Tracking field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ShippingMethod) GetTrackingOk() (*bool, bool) {
	if o == nil || IsNil(o.Tracking) {
		return nil, false
	}
	return o.Tracking, true
}

// HasTracking returns a boolean if a field has been set.
func (o *ShippingMethod) HasTracking() bool {
	if o != nil && !IsNil(o.Tracking) {
		return true
	}

	return false
}

// SetTracking gets a reference to the given bool and assigns it to the Tracking field.
func (o *ShippingMethod) SetTracking(v bool) {
	o.Tracking = &v
}

func (o ShippingMethod) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ShippingMethod) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ServiceCode) {
		toSerialize["service_code"] = o.ServiceCode
	}
	if !IsNil(o.Value) {
		toSerialize["value"] = o.Value
	}
	if !IsNil(o.Currency) {
		toSerialize["currency"] = o.Currency
	}
	if !IsNil(o.Company) {
		toSerialize["company"] = o.Company
	}
	if !IsNil(o.MinDays) {
		toSerialize["min_days"] = o.MinDays
	}
	if !IsNil(o.MaxDays) {
		toSerialize["max_days"] = o.MaxDays
	}
	if !IsNil(o.ShippingFrom) {
		toSerialize["shipping_from"] = o.ShippingFrom
	}
	if !IsNil(o.DeliveryDate) {
		toSerialize["delivery_date"] = o.DeliveryDate
	}
	if !IsNil(o.GuaranteedDeliveryTime) {
		toSerialize["guaranteed_delivery_time"] = o.GuaranteedDeliveryTime
	}
	if !IsNil(o.FreeShipping) {
		toSerialize["free_shipping"] = o.FreeShipping
	}
	if !IsNil(o.Tracking) {
		toSerialize["tracking"] = o.Tracking
	}
	return toSerialize, nil
}

type NullableShippingMethod struct {
	value *ShippingMethod
	isSet bool
}

func (v NullableShippingMethod) Get() *ShippingMethod {
	return v.value
}

func (v *NullableShippingMethod) Set(val *ShippingMethod) {
	v.value = val
	v.isSet = true
}

func (v NullableShippingMethod) IsSet() bool {
	return v.isSet
}

func (v *NullableShippingMethod) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableShippingMethod(val *ShippingMethod) *NullableShippingMethod {
	return &NullableShippingMethod{value: val, isSet: true}
}

func (v NullableShippingMethod) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableShippingMethod) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


