/*
AliExpress Parser API

Real-time AliExpress data parser covering products, product reviews, sellers, store coupons, a seller's product catalog, and product search by text or image. Products: pricing, stock status, shipping options, seller information, product configurations (SKUs), and more - scoped to a specific country and currency. Reviews: customer ratings and feedback for a product. Sellers: full store profile with ratings, feedback, and categories. Coupons: active seller coupon codes with discounts, thresholds, budgets, and expiry. Seller products: a store's product catalog, paginated and best-selling first. Search: find products by keyword or by uploading an image, returning paginated product results with their categories. 

API version: 2.1.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aligate

import (
	"encoding/json"
)

// checks if the ProductDescription type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProductDescription{}

// ProductDescription Long-form product description. Returned only when with_description=true. Fetching it adds an extra request (~600-750 ms). 
type ProductDescription struct {
	// Sanitized description HTML (scripts and event-handler attributes removed; safe to render).
	Html *string `json:"html,omitempty"`
	// Plain-text version of the description (tags stripped).
	Text *string `json:"text,omitempty"`
	// Image URLs extracted from the description gallery.
	Images []string `json:"images,omitempty"`
}

// NewProductDescription instantiates a new ProductDescription object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProductDescription() *ProductDescription {
	this := ProductDescription{}
	return &this
}

// NewProductDescriptionWithDefaults instantiates a new ProductDescription object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProductDescriptionWithDefaults() *ProductDescription {
	this := ProductDescription{}
	return &this
}

// GetHtml returns the Html field value if set, zero value otherwise.
func (o *ProductDescription) GetHtml() string {
	if o == nil || IsNil(o.Html) {
		var ret string
		return ret
	}
	return *o.Html
}

// GetHtmlOk returns a tuple with the Html field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductDescription) GetHtmlOk() (*string, bool) {
	if o == nil || IsNil(o.Html) {
		return nil, false
	}
	return o.Html, true
}

// HasHtml returns a boolean if a field has been set.
func (o *ProductDescription) HasHtml() bool {
	if o != nil && !IsNil(o.Html) {
		return true
	}

	return false
}

// SetHtml gets a reference to the given string and assigns it to the Html field.
func (o *ProductDescription) SetHtml(v string) {
	o.Html = &v
}

// GetText returns the Text field value if set, zero value otherwise.
func (o *ProductDescription) GetText() string {
	if o == nil || IsNil(o.Text) {
		var ret string
		return ret
	}
	return *o.Text
}

// GetTextOk returns a tuple with the Text field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductDescription) GetTextOk() (*string, bool) {
	if o == nil || IsNil(o.Text) {
		return nil, false
	}
	return o.Text, true
}

// HasText returns a boolean if a field has been set.
func (o *ProductDescription) HasText() bool {
	if o != nil && !IsNil(o.Text) {
		return true
	}

	return false
}

// SetText gets a reference to the given string and assigns it to the Text field.
func (o *ProductDescription) SetText(v string) {
	o.Text = &v
}

// GetImages returns the Images field value if set, zero value otherwise.
func (o *ProductDescription) GetImages() []string {
	if o == nil || IsNil(o.Images) {
		var ret []string
		return ret
	}
	return o.Images
}

// GetImagesOk returns a tuple with the Images field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductDescription) GetImagesOk() ([]string, bool) {
	if o == nil || IsNil(o.Images) {
		return nil, false
	}
	return o.Images, true
}

// HasImages returns a boolean if a field has been set.
func (o *ProductDescription) HasImages() bool {
	if o != nil && !IsNil(o.Images) {
		return true
	}

	return false
}

// SetImages gets a reference to the given []string and assigns it to the Images field.
func (o *ProductDescription) SetImages(v []string) {
	o.Images = v
}

func (o ProductDescription) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProductDescription) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Html) {
		toSerialize["html"] = o.Html
	}
	if !IsNil(o.Text) {
		toSerialize["text"] = o.Text
	}
	if !IsNil(o.Images) {
		toSerialize["images"] = o.Images
	}
	return toSerialize, nil
}

type NullableProductDescription struct {
	value *ProductDescription
	isSet bool
}

func (v NullableProductDescription) Get() *ProductDescription {
	return v.value
}

func (v *NullableProductDescription) Set(val *ProductDescription) {
	v.value = val
	v.isSet = true
}

func (v NullableProductDescription) IsSet() bool {
	return v.isSet
}

func (v *NullableProductDescription) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProductDescription(val *ProductDescription) *NullableProductDescription {
	return &NullableProductDescription{value: val, isSet: true}
}

func (v NullableProductDescription) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProductDescription) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


