/*
AliExpress Parser API

Real-time AliExpress data parser covering products, product reviews, sellers, store coupons, a seller's product catalog, and product search by text or image. Products: pricing, stock status, shipping options, seller information, product configurations (SKUs), and more - scoped to a specific country and currency. Reviews: customer ratings and feedback for a product. Sellers: full store profile with ratings, feedback, and categories. Coupons: active seller coupon codes with discounts, thresholds, budgets, and expiry. Seller products: a store's product catalog, paginated and best-selling first. Search: find products by keyword or by uploading an image, returning paginated product results with their categories. 

API version: 2.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aligate

import (
	"encoding/json"
)

// checks if the ReviewContent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ReviewContent{}

// ReviewContent A piece of review text with an optional translation
type ReviewContent struct {
	// Original text
	Text *string `json:"text,omitempty"`
	// Translated text (when available)
	TranslatedText *string `json:"translated_text,omitempty"`
	Date *string `json:"date,omitempty"`
}

// NewReviewContent instantiates a new ReviewContent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewReviewContent() *ReviewContent {
	this := ReviewContent{}
	return &this
}

// NewReviewContentWithDefaults instantiates a new ReviewContent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewReviewContentWithDefaults() *ReviewContent {
	this := ReviewContent{}
	return &this
}

// GetText returns the Text field value if set, zero value otherwise.
func (o *ReviewContent) GetText() string {
	if o == nil || IsNil(o.Text) {
		var ret string
		return ret
	}
	return *o.Text
}

// GetTextOk returns a tuple with the Text field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReviewContent) GetTextOk() (*string, bool) {
	if o == nil || IsNil(o.Text) {
		return nil, false
	}
	return o.Text, true
}

// HasText returns a boolean if a field has been set.
func (o *ReviewContent) HasText() bool {
	if o != nil && !IsNil(o.Text) {
		return true
	}

	return false
}

// SetText gets a reference to the given string and assigns it to the Text field.
func (o *ReviewContent) SetText(v string) {
	o.Text = &v
}

// GetTranslatedText returns the TranslatedText field value if set, zero value otherwise.
func (o *ReviewContent) GetTranslatedText() string {
	if o == nil || IsNil(o.TranslatedText) {
		var ret string
		return ret
	}
	return *o.TranslatedText
}

// GetTranslatedTextOk returns a tuple with the TranslatedText field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReviewContent) GetTranslatedTextOk() (*string, bool) {
	if o == nil || IsNil(o.TranslatedText) {
		return nil, false
	}
	return o.TranslatedText, true
}

// HasTranslatedText returns a boolean if a field has been set.
func (o *ReviewContent) HasTranslatedText() bool {
	if o != nil && !IsNil(o.TranslatedText) {
		return true
	}

	return false
}

// SetTranslatedText gets a reference to the given string and assigns it to the TranslatedText field.
func (o *ReviewContent) SetTranslatedText(v string) {
	o.TranslatedText = &v
}

// GetDate returns the Date field value if set, zero value otherwise.
func (o *ReviewContent) GetDate() string {
	if o == nil || IsNil(o.Date) {
		var ret string
		return ret
	}
	return *o.Date
}

// GetDateOk returns a tuple with the Date field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReviewContent) GetDateOk() (*string, bool) {
	if o == nil || IsNil(o.Date) {
		return nil, false
	}
	return o.Date, true
}

// HasDate returns a boolean if a field has been set.
func (o *ReviewContent) HasDate() bool {
	if o != nil && !IsNil(o.Date) {
		return true
	}

	return false
}

// SetDate gets a reference to the given string and assigns it to the Date field.
func (o *ReviewContent) SetDate(v string) {
	o.Date = &v
}

func (o ReviewContent) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ReviewContent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Text) {
		toSerialize["text"] = o.Text
	}
	if !IsNil(o.TranslatedText) {
		toSerialize["translated_text"] = o.TranslatedText
	}
	if !IsNil(o.Date) {
		toSerialize["date"] = o.Date
	}
	return toSerialize, nil
}

type NullableReviewContent struct {
	value *ReviewContent
	isSet bool
}

func (v NullableReviewContent) Get() *ReviewContent {
	return v.value
}

func (v *NullableReviewContent) Set(val *ReviewContent) {
	v.value = val
	v.isSet = true
}

func (v NullableReviewContent) IsSet() bool {
	return v.isSet
}

func (v *NullableReviewContent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableReviewContent(val *ReviewContent) *NullableReviewContent {
	return &NullableReviewContent{value: val, isSet: true}
}

func (v NullableReviewContent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableReviewContent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


