/*
AliExpress Parser API

Real-time AliExpress data parser covering products, product reviews, sellers, store coupons, a seller's product catalog, and product search by text or image. Products: pricing, stock status, shipping options, seller information, product configurations (SKUs), and more - scoped to a specific country and currency. Reviews: customer ratings and feedback for a product. Sellers: full store profile with ratings, feedback, and categories. Coupons: active seller coupon codes with discounts, thresholds, budgets, and expiry. Seller products: a store's product catalog, paginated and best-selling first. Search: find products by keyword or by uploading an image, returning paginated product results with their categories. 

API version: 2.1.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aligate

import (
	"encoding/json"
)

// checks if the SellerSettings type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SellerSettings{}

// SellerSettings Echo of the request parameters
type SellerSettings struct {
	SellerId *int32 `json:"seller_id,omitempty"`
	StoreNum *int32 `json:"store_num,omitempty"`
}

// NewSellerSettings instantiates a new SellerSettings object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSellerSettings() *SellerSettings {
	this := SellerSettings{}
	return &this
}

// NewSellerSettingsWithDefaults instantiates a new SellerSettings object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSellerSettingsWithDefaults() *SellerSettings {
	this := SellerSettings{}
	return &this
}

// GetSellerId returns the SellerId field value if set, zero value otherwise.
func (o *SellerSettings) GetSellerId() int32 {
	if o == nil || IsNil(o.SellerId) {
		var ret int32
		return ret
	}
	return *o.SellerId
}

// GetSellerIdOk returns a tuple with the SellerId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SellerSettings) GetSellerIdOk() (*int32, bool) {
	if o == nil || IsNil(o.SellerId) {
		return nil, false
	}
	return o.SellerId, true
}

// HasSellerId returns a boolean if a field has been set.
func (o *SellerSettings) HasSellerId() bool {
	if o != nil && !IsNil(o.SellerId) {
		return true
	}

	return false
}

// SetSellerId gets a reference to the given int32 and assigns it to the SellerId field.
func (o *SellerSettings) SetSellerId(v int32) {
	o.SellerId = &v
}

// GetStoreNum returns the StoreNum field value if set, zero value otherwise.
func (o *SellerSettings) GetStoreNum() int32 {
	if o == nil || IsNil(o.StoreNum) {
		var ret int32
		return ret
	}
	return *o.StoreNum
}

// GetStoreNumOk returns a tuple with the StoreNum field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SellerSettings) GetStoreNumOk() (*int32, bool) {
	if o == nil || IsNil(o.StoreNum) {
		return nil, false
	}
	return o.StoreNum, true
}

// HasStoreNum returns a boolean if a field has been set.
func (o *SellerSettings) HasStoreNum() bool {
	if o != nil && !IsNil(o.StoreNum) {
		return true
	}

	return false
}

// SetStoreNum gets a reference to the given int32 and assigns it to the StoreNum field.
func (o *SellerSettings) SetStoreNum(v int32) {
	o.StoreNum = &v
}

func (o SellerSettings) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SellerSettings) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.SellerId) {
		toSerialize["seller_id"] = o.SellerId
	}
	if !IsNil(o.StoreNum) {
		toSerialize["store_num"] = o.StoreNum
	}
	return toSerialize, nil
}

type NullableSellerSettings struct {
	value *SellerSettings
	isSet bool
}

func (v NullableSellerSettings) Get() *SellerSettings {
	return v.value
}

func (v *NullableSellerSettings) Set(val *SellerSettings) {
	v.value = val
	v.isSet = true
}

func (v NullableSellerSettings) IsSet() bool {
	return v.isSet
}

func (v *NullableSellerSettings) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSellerSettings(val *SellerSettings) *NullableSellerSettings {
	return &NullableSellerSettings{value: val, isSet: true}
}

func (v NullableSellerSettings) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSellerSettings) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


