/*
AliExpress Parser API

Real-time AliExpress data parser covering products, product reviews, sellers, store coupons, a seller's product catalog, and product search by text or image. Products: pricing, stock status, shipping options, seller information, product configurations (SKUs), and more - scoped to a specific country and currency. Reviews: customer ratings and feedback for a product. Sellers: full store profile with ratings, feedback, and categories. Coupons: active seller coupon codes with discounts, thresholds, budgets, and expiry. Seller products: a store's product catalog, paginated and best-selling first. Search: find products by keyword or by uploading an image, returning paginated product results with their categories. 

API version: 2.1.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aligate

import (
	"encoding/json"
)

// checks if the ParseMeta type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ParseMeta{}

// ParseMeta Request metadata set by the gateway
type ParseMeta struct {
	Code *int32 `json:"code,omitempty"`
	// Which parser attempt won (1 = referral, 2-3 = normal)
	Attempt *int32 `json:"attempt,omitempty"`
	// Parser version string
	V *string `json:"v,omitempty"`
	// Parser path that produced the result
	Source *string `json:"source,omitempty"`
	// UTC timestamp when the request was received
	RequestTime *string `json:"request_time,omitempty"`
	// Total parse duration
	ExecutionTime *string `json:"execution_time,omitempty"`
	// Internal trace identifier
	TraceId *string `json:"trace_id,omitempty"`
	// Inferred geographic region used by the parser
	Pgeo *string `json:"pgeo,omitempty"`
	// True when the fallback request was fired before the primary responded
	HedgeFired *bool `json:"hedge_fired,omitempty"`
	// End-to-end gateway duration in milliseconds
	DurationMs *int64 `json:"duration_ms,omitempty"`
}

// NewParseMeta instantiates a new ParseMeta object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewParseMeta() *ParseMeta {
	this := ParseMeta{}
	return &this
}

// NewParseMetaWithDefaults instantiates a new ParseMeta object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewParseMetaWithDefaults() *ParseMeta {
	this := ParseMeta{}
	return &this
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *ParseMeta) GetCode() int32 {
	if o == nil || IsNil(o.Code) {
		var ret int32
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ParseMeta) GetCodeOk() (*int32, bool) {
	if o == nil || IsNil(o.Code) {
		return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *ParseMeta) HasCode() bool {
	if o != nil && !IsNil(o.Code) {
		return true
	}

	return false
}

// SetCode gets a reference to the given int32 and assigns it to the Code field.
func (o *ParseMeta) SetCode(v int32) {
	o.Code = &v
}

// GetAttempt returns the Attempt field value if set, zero value otherwise.
func (o *ParseMeta) GetAttempt() int32 {
	if o == nil || IsNil(o.Attempt) {
		var ret int32
		return ret
	}
	return *o.Attempt
}

// GetAttemptOk returns a tuple with the Attempt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ParseMeta) GetAttemptOk() (*int32, bool) {
	if o == nil || IsNil(o.Attempt) {
		return nil, false
	}
	return o.Attempt, true
}

// HasAttempt returns a boolean if a field has been set.
func (o *ParseMeta) HasAttempt() bool {
	if o != nil && !IsNil(o.Attempt) {
		return true
	}

	return false
}

// SetAttempt gets a reference to the given int32 and assigns it to the Attempt field.
func (o *ParseMeta) SetAttempt(v int32) {
	o.Attempt = &v
}

// GetV returns the V field value if set, zero value otherwise.
func (o *ParseMeta) GetV() string {
	if o == nil || IsNil(o.V) {
		var ret string
		return ret
	}
	return *o.V
}

// GetVOk returns a tuple with the V field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ParseMeta) GetVOk() (*string, bool) {
	if o == nil || IsNil(o.V) {
		return nil, false
	}
	return o.V, true
}

// HasV returns a boolean if a field has been set.
func (o *ParseMeta) HasV() bool {
	if o != nil && !IsNil(o.V) {
		return true
	}

	return false
}

// SetV gets a reference to the given string and assigns it to the V field.
func (o *ParseMeta) SetV(v string) {
	o.V = &v
}

// GetSource returns the Source field value if set, zero value otherwise.
func (o *ParseMeta) GetSource() string {
	if o == nil || IsNil(o.Source) {
		var ret string
		return ret
	}
	return *o.Source
}

// GetSourceOk returns a tuple with the Source field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ParseMeta) GetSourceOk() (*string, bool) {
	if o == nil || IsNil(o.Source) {
		return nil, false
	}
	return o.Source, true
}

// HasSource returns a boolean if a field has been set.
func (o *ParseMeta) HasSource() bool {
	if o != nil && !IsNil(o.Source) {
		return true
	}

	return false
}

// SetSource gets a reference to the given string and assigns it to the Source field.
func (o *ParseMeta) SetSource(v string) {
	o.Source = &v
}

// GetRequestTime returns the RequestTime field value if set, zero value otherwise.
func (o *ParseMeta) GetRequestTime() string {
	if o == nil || IsNil(o.RequestTime) {
		var ret string
		return ret
	}
	return *o.RequestTime
}

// GetRequestTimeOk returns a tuple with the RequestTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ParseMeta) GetRequestTimeOk() (*string, bool) {
	if o == nil || IsNil(o.RequestTime) {
		return nil, false
	}
	return o.RequestTime, true
}

// HasRequestTime returns a boolean if a field has been set.
func (o *ParseMeta) HasRequestTime() bool {
	if o != nil && !IsNil(o.RequestTime) {
		return true
	}

	return false
}

// SetRequestTime gets a reference to the given string and assigns it to the RequestTime field.
func (o *ParseMeta) SetRequestTime(v string) {
	o.RequestTime = &v
}

// GetExecutionTime returns the ExecutionTime field value if set, zero value otherwise.
func (o *ParseMeta) GetExecutionTime() string {
	if o == nil || IsNil(o.ExecutionTime) {
		var ret string
		return ret
	}
	return *o.ExecutionTime
}

// GetExecutionTimeOk returns a tuple with the ExecutionTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ParseMeta) GetExecutionTimeOk() (*string, bool) {
	if o == nil || IsNil(o.ExecutionTime) {
		return nil, false
	}
	return o.ExecutionTime, true
}

// HasExecutionTime returns a boolean if a field has been set.
func (o *ParseMeta) HasExecutionTime() bool {
	if o != nil && !IsNil(o.ExecutionTime) {
		return true
	}

	return false
}

// SetExecutionTime gets a reference to the given string and assigns it to the ExecutionTime field.
func (o *ParseMeta) SetExecutionTime(v string) {
	o.ExecutionTime = &v
}

// GetTraceId returns the TraceId field value if set, zero value otherwise.
func (o *ParseMeta) GetTraceId() string {
	if o == nil || IsNil(o.TraceId) {
		var ret string
		return ret
	}
	return *o.TraceId
}

// GetTraceIdOk returns a tuple with the TraceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ParseMeta) GetTraceIdOk() (*string, bool) {
	if o == nil || IsNil(o.TraceId) {
		return nil, false
	}
	return o.TraceId, true
}

// HasTraceId returns a boolean if a field has been set.
func (o *ParseMeta) HasTraceId() bool {
	if o != nil && !IsNil(o.TraceId) {
		return true
	}

	return false
}

// SetTraceId gets a reference to the given string and assigns it to the TraceId field.
func (o *ParseMeta) SetTraceId(v string) {
	o.TraceId = &v
}

// GetPgeo returns the Pgeo field value if set, zero value otherwise.
func (o *ParseMeta) GetPgeo() string {
	if o == nil || IsNil(o.Pgeo) {
		var ret string
		return ret
	}
	return *o.Pgeo
}

// GetPgeoOk returns a tuple with the Pgeo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ParseMeta) GetPgeoOk() (*string, bool) {
	if o == nil || IsNil(o.Pgeo) {
		return nil, false
	}
	return o.Pgeo, true
}

// HasPgeo returns a boolean if a field has been set.
func (o *ParseMeta) HasPgeo() bool {
	if o != nil && !IsNil(o.Pgeo) {
		return true
	}

	return false
}

// SetPgeo gets a reference to the given string and assigns it to the Pgeo field.
func (o *ParseMeta) SetPgeo(v string) {
	o.Pgeo = &v
}

// GetHedgeFired returns the HedgeFired field value if set, zero value otherwise.
func (o *ParseMeta) GetHedgeFired() bool {
	if o == nil || IsNil(o.HedgeFired) {
		var ret bool
		return ret
	}
	return *o.HedgeFired
}

// GetHedgeFiredOk returns a tuple with the HedgeFired field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ParseMeta) GetHedgeFiredOk() (*bool, bool) {
	if o == nil || IsNil(o.HedgeFired) {
		return nil, false
	}
	return o.HedgeFired, true
}

// HasHedgeFired returns a boolean if a field has been set.
func (o *ParseMeta) HasHedgeFired() bool {
	if o != nil && !IsNil(o.HedgeFired) {
		return true
	}

	return false
}

// SetHedgeFired gets a reference to the given bool and assigns it to the HedgeFired field.
func (o *ParseMeta) SetHedgeFired(v bool) {
	o.HedgeFired = &v
}

// GetDurationMs returns the DurationMs field value if set, zero value otherwise.
func (o *ParseMeta) GetDurationMs() int64 {
	if o == nil || IsNil(o.DurationMs) {
		var ret int64
		return ret
	}
	return *o.DurationMs
}

// GetDurationMsOk returns a tuple with the DurationMs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ParseMeta) GetDurationMsOk() (*int64, bool) {
	if o == nil || IsNil(o.DurationMs) {
		return nil, false
	}
	return o.DurationMs, true
}

// HasDurationMs returns a boolean if a field has been set.
func (o *ParseMeta) HasDurationMs() bool {
	if o != nil && !IsNil(o.DurationMs) {
		return true
	}

	return false
}

// SetDurationMs gets a reference to the given int64 and assigns it to the DurationMs field.
func (o *ParseMeta) SetDurationMs(v int64) {
	o.DurationMs = &v
}

func (o ParseMeta) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ParseMeta) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Code) {
		toSerialize["code"] = o.Code
	}
	if !IsNil(o.Attempt) {
		toSerialize["attempt"] = o.Attempt
	}
	if !IsNil(o.V) {
		toSerialize["v"] = o.V
	}
	if !IsNil(o.Source) {
		toSerialize["source"] = o.Source
	}
	if !IsNil(o.RequestTime) {
		toSerialize["request_time"] = o.RequestTime
	}
	if !IsNil(o.ExecutionTime) {
		toSerialize["execution_time"] = o.ExecutionTime
	}
	if !IsNil(o.TraceId) {
		toSerialize["trace_id"] = o.TraceId
	}
	if !IsNil(o.Pgeo) {
		toSerialize["pgeo"] = o.Pgeo
	}
	if !IsNil(o.HedgeFired) {
		toSerialize["hedge_fired"] = o.HedgeFired
	}
	if !IsNil(o.DurationMs) {
		toSerialize["duration_ms"] = o.DurationMs
	}
	return toSerialize, nil
}

type NullableParseMeta struct {
	value *ParseMeta
	isSet bool
}

func (v NullableParseMeta) Get() *ParseMeta {
	return v.value
}

func (v *NullableParseMeta) Set(val *ParseMeta) {
	v.value = val
	v.isSet = true
}

func (v NullableParseMeta) IsSet() bool {
	return v.isSet
}

func (v *NullableParseMeta) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableParseMeta(val *ParseMeta) *NullableParseMeta {
	return &NullableParseMeta{value: val, isSet: true}
}

func (v NullableParseMeta) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableParseMeta) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


