/*
AliExpress Parser API

Real-time AliExpress data parser covering products, product reviews, sellers, store coupons, a seller's product catalog, and product search by text or image. Products: pricing, stock status, shipping options, seller information, product configurations (SKUs), and more - scoped to a specific country and currency. Reviews: customer ratings and feedback for a product. Sellers: full store profile with ratings, feedback, and categories. Coupons: active seller coupon codes with discounts, thresholds, budgets, and expiry. Seller products: a store's product catalog, paginated and best-selling first. Search: find products by keyword or by uploading an image, returning paginated product results with their categories. 

API version: 2.1.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aligate

import (
	"encoding/json"
)

// checks if the ConfigurationPrice type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConfigurationPrice{}

// ConfigurationPrice Price for a specific SKU variant
type ConfigurationPrice struct {
	Value *float64 `json:"value,omitempty"`
	OriginalValue *float64 `json:"original_value,omitempty"`
	Currency *string `json:"currency,omitempty"`
	Country *string `json:"country,omitempty"`
}

// NewConfigurationPrice instantiates a new ConfigurationPrice object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConfigurationPrice() *ConfigurationPrice {
	this := ConfigurationPrice{}
	return &this
}

// NewConfigurationPriceWithDefaults instantiates a new ConfigurationPrice object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConfigurationPriceWithDefaults() *ConfigurationPrice {
	this := ConfigurationPrice{}
	return &this
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *ConfigurationPrice) GetValue() float64 {
	if o == nil || IsNil(o.Value) {
		var ret float64
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigurationPrice) GetValueOk() (*float64, bool) {
	if o == nil || IsNil(o.Value) {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *ConfigurationPrice) HasValue() bool {
	if o != nil && !IsNil(o.Value) {
		return true
	}

	return false
}

// SetValue gets a reference to the given float64 and assigns it to the Value field.
func (o *ConfigurationPrice) SetValue(v float64) {
	o.Value = &v
}

// GetOriginalValue returns the OriginalValue field value if set, zero value otherwise.
func (o *ConfigurationPrice) GetOriginalValue() float64 {
	if o == nil || IsNil(o.OriginalValue) {
		var ret float64
		return ret
	}
	return *o.OriginalValue
}

// GetOriginalValueOk returns a tuple with the OriginalValue field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigurationPrice) GetOriginalValueOk() (*float64, bool) {
	if o == nil || IsNil(o.OriginalValue) {
		return nil, false
	}
	return o.OriginalValue, true
}

// HasOriginalValue returns a boolean if a field has been set.
func (o *ConfigurationPrice) HasOriginalValue() bool {
	if o != nil && !IsNil(o.OriginalValue) {
		return true
	}

	return false
}

// SetOriginalValue gets a reference to the given float64 and assigns it to the OriginalValue field.
func (o *ConfigurationPrice) SetOriginalValue(v float64) {
	o.OriginalValue = &v
}

// GetCurrency returns the Currency field value if set, zero value otherwise.
func (o *ConfigurationPrice) GetCurrency() string {
	if o == nil || IsNil(o.Currency) {
		var ret string
		return ret
	}
	return *o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigurationPrice) GetCurrencyOk() (*string, bool) {
	if o == nil || IsNil(o.Currency) {
		return nil, false
	}
	return o.Currency, true
}

// HasCurrency returns a boolean if a field has been set.
func (o *ConfigurationPrice) HasCurrency() bool {
	if o != nil && !IsNil(o.Currency) {
		return true
	}

	return false
}

// SetCurrency gets a reference to the given string and assigns it to the Currency field.
func (o *ConfigurationPrice) SetCurrency(v string) {
	o.Currency = &v
}

// GetCountry returns the Country field value if set, zero value otherwise.
func (o *ConfigurationPrice) GetCountry() string {
	if o == nil || IsNil(o.Country) {
		var ret string
		return ret
	}
	return *o.Country
}

// GetCountryOk returns a tuple with the Country field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigurationPrice) GetCountryOk() (*string, bool) {
	if o == nil || IsNil(o.Country) {
		return nil, false
	}
	return o.Country, true
}

// HasCountry returns a boolean if a field has been set.
func (o *ConfigurationPrice) HasCountry() bool {
	if o != nil && !IsNil(o.Country) {
		return true
	}

	return false
}

// SetCountry gets a reference to the given string and assigns it to the Country field.
func (o *ConfigurationPrice) SetCountry(v string) {
	o.Country = &v
}

func (o ConfigurationPrice) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConfigurationPrice) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Value) {
		toSerialize["value"] = o.Value
	}
	if !IsNil(o.OriginalValue) {
		toSerialize["original_value"] = o.OriginalValue
	}
	if !IsNil(o.Currency) {
		toSerialize["currency"] = o.Currency
	}
	if !IsNil(o.Country) {
		toSerialize["country"] = o.Country
	}
	return toSerialize, nil
}

type NullableConfigurationPrice struct {
	value *ConfigurationPrice
	isSet bool
}

func (v NullableConfigurationPrice) Get() *ConfigurationPrice {
	return v.value
}

func (v *NullableConfigurationPrice) Set(val *ConfigurationPrice) {
	v.value = val
	v.isSet = true
}

func (v NullableConfigurationPrice) IsSet() bool {
	return v.isSet
}

func (v *NullableConfigurationPrice) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConfigurationPrice(val *ConfigurationPrice) *NullableConfigurationPrice {
	return &NullableConfigurationPrice{value: val, isSet: true}
}

func (v NullableConfigurationPrice) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConfigurationPrice) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


