/*
AliExpress Parser API

Real-time AliExpress data parser covering products, product reviews, sellers, store coupons, a seller's product catalog, and product search by text or image. Products: pricing, stock status, shipping options, seller information, product configurations (SKUs), and more - scoped to a specific country and currency. Reviews: customer ratings and feedback for a product. Sellers: full store profile with ratings, feedback, and categories. Coupons: active seller coupon codes with discounts, thresholds, budgets, and expiry. Seller products: a store's product catalog, paginated and best-selling first. Search: find products by keyword or by uploading an image, returning paginated product results with their categories. 

API version: 2.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aligate

import (
	"encoding/json"
)

// checks if the ReviewFilterStat type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ReviewFilterStat{}

// ReviewFilterStat Count of reviews available for a given filter
type ReviewFilterStat struct {
	// Filter code
	Name *string `json:"name,omitempty"`
	Amount *int32 `json:"amount,omitempty"`
}

// NewReviewFilterStat instantiates a new ReviewFilterStat object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewReviewFilterStat() *ReviewFilterStat {
	this := ReviewFilterStat{}
	return &this
}

// NewReviewFilterStatWithDefaults instantiates a new ReviewFilterStat object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewReviewFilterStatWithDefaults() *ReviewFilterStat {
	this := ReviewFilterStat{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ReviewFilterStat) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReviewFilterStat) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ReviewFilterStat) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ReviewFilterStat) SetName(v string) {
	o.Name = &v
}

// GetAmount returns the Amount field value if set, zero value otherwise.
func (o *ReviewFilterStat) GetAmount() int32 {
	if o == nil || IsNil(o.Amount) {
		var ret int32
		return ret
	}
	return *o.Amount
}

// GetAmountOk returns a tuple with the Amount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReviewFilterStat) GetAmountOk() (*int32, bool) {
	if o == nil || IsNil(o.Amount) {
		return nil, false
	}
	return o.Amount, true
}

// HasAmount returns a boolean if a field has been set.
func (o *ReviewFilterStat) HasAmount() bool {
	if o != nil && !IsNil(o.Amount) {
		return true
	}

	return false
}

// SetAmount gets a reference to the given int32 and assigns it to the Amount field.
func (o *ReviewFilterStat) SetAmount(v int32) {
	o.Amount = &v
}

func (o ReviewFilterStat) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ReviewFilterStat) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Amount) {
		toSerialize["amount"] = o.Amount
	}
	return toSerialize, nil
}

type NullableReviewFilterStat struct {
	value *ReviewFilterStat
	isSet bool
}

func (v NullableReviewFilterStat) Get() *ReviewFilterStat {
	return v.value
}

func (v *NullableReviewFilterStat) Set(val *ReviewFilterStat) {
	v.value = val
	v.isSet = true
}

func (v NullableReviewFilterStat) IsSet() bool {
	return v.isSet
}

func (v *NullableReviewFilterStat) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableReviewFilterStat(val *ReviewFilterStat) *NullableReviewFilterStat {
	return &NullableReviewFilterStat{value: val, isSet: true}
}

func (v NullableReviewFilterStat) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableReviewFilterStat) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


