/*
AliExpress Parser API

Real-time AliExpress data parser covering products, product reviews, sellers, store coupons, a seller's product catalog, product shipping, product descriptions, and product search by text or image. Products: pricing, stock status, shipping options, seller information, product configurations (SKUs), and more - scoped to a specific country and currency. Reviews: customer ratings and feedback for a product. Sellers: full store profile with ratings, feedback, and categories. Coupons: active seller coupon codes with discounts, thresholds, budgets, and expiry. Seller products: a store's product catalog, paginated and best-selling first. Shipping: shipping methods for a product with cost, carrier, and delivery estimate. Description: a product's long-form description on its own - HTML, plain text, and the images extracted from the description gallery. Search: find products by keyword or by uploading an image, returning paginated product results with their categories. 

API version: 2.6.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aligate

import (
	"encoding/json"
)

// checks if the DescriptionSettings type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DescriptionSettings{}

// DescriptionSettings Echo of the description request. product_id, country and currency are set when the description was resolved; locale, currency, country and item_id are set when the parse failed and no description is returned. 
type DescriptionSettings struct {
	ProductId *int64 `json:"product_id,omitempty"`
	Country *string `json:"country,omitempty"`
	Currency *string `json:"currency,omitempty"`
	Locale *string `json:"locale,omitempty"`
	ItemId *int64 `json:"item_id,omitempty"`
}

// NewDescriptionSettings instantiates a new DescriptionSettings object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDescriptionSettings() *DescriptionSettings {
	this := DescriptionSettings{}
	return &this
}

// NewDescriptionSettingsWithDefaults instantiates a new DescriptionSettings object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDescriptionSettingsWithDefaults() *DescriptionSettings {
	this := DescriptionSettings{}
	return &this
}

// GetProductId returns the ProductId field value if set, zero value otherwise.
func (o *DescriptionSettings) GetProductId() int64 {
	if o == nil || IsNil(o.ProductId) {
		var ret int64
		return ret
	}
	return *o.ProductId
}

// GetProductIdOk returns a tuple with the ProductId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DescriptionSettings) GetProductIdOk() (*int64, bool) {
	if o == nil || IsNil(o.ProductId) {
		return nil, false
	}
	return o.ProductId, true
}

// HasProductId returns a boolean if a field has been set.
func (o *DescriptionSettings) HasProductId() bool {
	if o != nil && !IsNil(o.ProductId) {
		return true
	}

	return false
}

// SetProductId gets a reference to the given int64 and assigns it to the ProductId field.
func (o *DescriptionSettings) SetProductId(v int64) {
	o.ProductId = &v
}

// GetCountry returns the Country field value if set, zero value otherwise.
func (o *DescriptionSettings) GetCountry() string {
	if o == nil || IsNil(o.Country) {
		var ret string
		return ret
	}
	return *o.Country
}

// GetCountryOk returns a tuple with the Country field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DescriptionSettings) GetCountryOk() (*string, bool) {
	if o == nil || IsNil(o.Country) {
		return nil, false
	}
	return o.Country, true
}

// HasCountry returns a boolean if a field has been set.
func (o *DescriptionSettings) HasCountry() bool {
	if o != nil && !IsNil(o.Country) {
		return true
	}

	return false
}

// SetCountry gets a reference to the given string and assigns it to the Country field.
func (o *DescriptionSettings) SetCountry(v string) {
	o.Country = &v
}

// GetCurrency returns the Currency field value if set, zero value otherwise.
func (o *DescriptionSettings) GetCurrency() string {
	if o == nil || IsNil(o.Currency) {
		var ret string
		return ret
	}
	return *o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DescriptionSettings) GetCurrencyOk() (*string, bool) {
	if o == nil || IsNil(o.Currency) {
		return nil, false
	}
	return o.Currency, true
}

// HasCurrency returns a boolean if a field has been set.
func (o *DescriptionSettings) HasCurrency() bool {
	if o != nil && !IsNil(o.Currency) {
		return true
	}

	return false
}

// SetCurrency gets a reference to the given string and assigns it to the Currency field.
func (o *DescriptionSettings) SetCurrency(v string) {
	o.Currency = &v
}

// GetLocale returns the Locale field value if set, zero value otherwise.
func (o *DescriptionSettings) GetLocale() string {
	if o == nil || IsNil(o.Locale) {
		var ret string
		return ret
	}
	return *o.Locale
}

// GetLocaleOk returns a tuple with the Locale field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DescriptionSettings) GetLocaleOk() (*string, bool) {
	if o == nil || IsNil(o.Locale) {
		return nil, false
	}
	return o.Locale, true
}

// HasLocale returns a boolean if a field has been set.
func (o *DescriptionSettings) HasLocale() bool {
	if o != nil && !IsNil(o.Locale) {
		return true
	}

	return false
}

// SetLocale gets a reference to the given string and assigns it to the Locale field.
func (o *DescriptionSettings) SetLocale(v string) {
	o.Locale = &v
}

// GetItemId returns the ItemId field value if set, zero value otherwise.
func (o *DescriptionSettings) GetItemId() int64 {
	if o == nil || IsNil(o.ItemId) {
		var ret int64
		return ret
	}
	return *o.ItemId
}

// GetItemIdOk returns a tuple with the ItemId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DescriptionSettings) GetItemIdOk() (*int64, bool) {
	if o == nil || IsNil(o.ItemId) {
		return nil, false
	}
	return o.ItemId, true
}

// HasItemId returns a boolean if a field has been set.
func (o *DescriptionSettings) HasItemId() bool {
	if o != nil && !IsNil(o.ItemId) {
		return true
	}

	return false
}

// SetItemId gets a reference to the given int64 and assigns it to the ItemId field.
func (o *DescriptionSettings) SetItemId(v int64) {
	o.ItemId = &v
}

func (o DescriptionSettings) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DescriptionSettings) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ProductId) {
		toSerialize["product_id"] = o.ProductId
	}
	if !IsNil(o.Country) {
		toSerialize["country"] = o.Country
	}
	if !IsNil(o.Currency) {
		toSerialize["currency"] = o.Currency
	}
	if !IsNil(o.Locale) {
		toSerialize["locale"] = o.Locale
	}
	if !IsNil(o.ItemId) {
		toSerialize["item_id"] = o.ItemId
	}
	return toSerialize, nil
}

type NullableDescriptionSettings struct {
	value *DescriptionSettings
	isSet bool
}

func (v NullableDescriptionSettings) Get() *DescriptionSettings {
	return v.value
}

func (v *NullableDescriptionSettings) Set(val *DescriptionSettings) {
	v.value = val
	v.isSet = true
}

func (v NullableDescriptionSettings) IsSet() bool {
	return v.isSet
}

func (v *NullableDescriptionSettings) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDescriptionSettings(val *DescriptionSettings) *NullableDescriptionSettings {
	return &NullableDescriptionSettings{value: val, isSet: true}
}

func (v NullableDescriptionSettings) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDescriptionSettings) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


