/*
AliExpress Parser API

Real-time AliExpress data parser covering products, product reviews, sellers, store coupons, a seller's product catalog, and product search by text or image. Products: pricing, stock status, shipping options, seller information, product configurations (SKUs), and more - scoped to a specific country and currency. Reviews: customer ratings and feedback for a product. Sellers: full store profile with ratings, feedback, and categories. Coupons: active seller coupon codes with discounts, thresholds, budgets, and expiry. Seller products: a store's product catalog, paginated and best-selling first. Search: find products by keyword or by uploading an image, returning paginated product results with their categories. 

API version: 2.1.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aligate

import (
	"encoding/json"
)

// checks if the ImageSearchSettings type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ImageSearchSettings{}

// ImageSearchSettings Echo of the request parameters (the query image is not echoed)
type ImageSearchSettings struct {
	Country *string `json:"country,omitempty"`
	Currency *string `json:"currency,omitempty"`
	Locale *string `json:"locale,omitempty"`
	Page *int32 `json:"page,omitempty"`
}

// NewImageSearchSettings instantiates a new ImageSearchSettings object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewImageSearchSettings() *ImageSearchSettings {
	this := ImageSearchSettings{}
	return &this
}

// NewImageSearchSettingsWithDefaults instantiates a new ImageSearchSettings object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewImageSearchSettingsWithDefaults() *ImageSearchSettings {
	this := ImageSearchSettings{}
	return &this
}

// GetCountry returns the Country field value if set, zero value otherwise.
func (o *ImageSearchSettings) GetCountry() string {
	if o == nil || IsNil(o.Country) {
		var ret string
		return ret
	}
	return *o.Country
}

// GetCountryOk returns a tuple with the Country field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ImageSearchSettings) GetCountryOk() (*string, bool) {
	if o == nil || IsNil(o.Country) {
		return nil, false
	}
	return o.Country, true
}

// HasCountry returns a boolean if a field has been set.
func (o *ImageSearchSettings) HasCountry() bool {
	if o != nil && !IsNil(o.Country) {
		return true
	}

	return false
}

// SetCountry gets a reference to the given string and assigns it to the Country field.
func (o *ImageSearchSettings) SetCountry(v string) {
	o.Country = &v
}

// GetCurrency returns the Currency field value if set, zero value otherwise.
func (o *ImageSearchSettings) GetCurrency() string {
	if o == nil || IsNil(o.Currency) {
		var ret string
		return ret
	}
	return *o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ImageSearchSettings) GetCurrencyOk() (*string, bool) {
	if o == nil || IsNil(o.Currency) {
		return nil, false
	}
	return o.Currency, true
}

// HasCurrency returns a boolean if a field has been set.
func (o *ImageSearchSettings) HasCurrency() bool {
	if o != nil && !IsNil(o.Currency) {
		return true
	}

	return false
}

// SetCurrency gets a reference to the given string and assigns it to the Currency field.
func (o *ImageSearchSettings) SetCurrency(v string) {
	o.Currency = &v
}

// GetLocale returns the Locale field value if set, zero value otherwise.
func (o *ImageSearchSettings) GetLocale() string {
	if o == nil || IsNil(o.Locale) {
		var ret string
		return ret
	}
	return *o.Locale
}

// GetLocaleOk returns a tuple with the Locale field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ImageSearchSettings) GetLocaleOk() (*string, bool) {
	if o == nil || IsNil(o.Locale) {
		return nil, false
	}
	return o.Locale, true
}

// HasLocale returns a boolean if a field has been set.
func (o *ImageSearchSettings) HasLocale() bool {
	if o != nil && !IsNil(o.Locale) {
		return true
	}

	return false
}

// SetLocale gets a reference to the given string and assigns it to the Locale field.
func (o *ImageSearchSettings) SetLocale(v string) {
	o.Locale = &v
}

// GetPage returns the Page field value if set, zero value otherwise.
func (o *ImageSearchSettings) GetPage() int32 {
	if o == nil || IsNil(o.Page) {
		var ret int32
		return ret
	}
	return *o.Page
}

// GetPageOk returns a tuple with the Page field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ImageSearchSettings) GetPageOk() (*int32, bool) {
	if o == nil || IsNil(o.Page) {
		return nil, false
	}
	return o.Page, true
}

// HasPage returns a boolean if a field has been set.
func (o *ImageSearchSettings) HasPage() bool {
	if o != nil && !IsNil(o.Page) {
		return true
	}

	return false
}

// SetPage gets a reference to the given int32 and assigns it to the Page field.
func (o *ImageSearchSettings) SetPage(v int32) {
	o.Page = &v
}

func (o ImageSearchSettings) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ImageSearchSettings) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Country) {
		toSerialize["country"] = o.Country
	}
	if !IsNil(o.Currency) {
		toSerialize["currency"] = o.Currency
	}
	if !IsNil(o.Locale) {
		toSerialize["locale"] = o.Locale
	}
	if !IsNil(o.Page) {
		toSerialize["page"] = o.Page
	}
	return toSerialize, nil
}

type NullableImageSearchSettings struct {
	value *ImageSearchSettings
	isSet bool
}

func (v NullableImageSearchSettings) Get() *ImageSearchSettings {
	return v.value
}

func (v *NullableImageSearchSettings) Set(val *ImageSearchSettings) {
	v.value = val
	v.isSet = true
}

func (v NullableImageSearchSettings) IsSet() bool {
	return v.isSet
}

func (v *NullableImageSearchSettings) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableImageSearchSettings(val *ImageSearchSettings) *NullableImageSearchSettings {
	return &NullableImageSearchSettings{value: val, isSet: true}
}

func (v NullableImageSearchSettings) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableImageSearchSettings) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


