/*
AliExpress Parser API

Real-time AliExpress data parser covering products, product reviews, sellers, store coupons, a seller's product catalog, and product search by text or image. Products: pricing, stock status, shipping options, seller information, product configurations (SKUs), and more - scoped to a specific country and currency. Reviews: customer ratings and feedback for a product. Sellers: full store profile with ratings, feedback, and categories. Coupons: active seller coupon codes with discounts, thresholds, budgets, and expiry. Seller products: a store's product catalog, paginated and best-selling first. Search: find products by keyword or by uploading an image, returning paginated product results with their categories. 

API version: 2.1.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aligate

import (
	"encoding/json"
)

// checks if the ProductSeller type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProductSeller{}

// ProductSeller struct for ProductSeller
type ProductSeller struct {
	SellerAdminSeq *int32 `json:"seller_admin_seq,omitempty"`
	StoreNum *int32 `json:"store_num,omitempty"`
	StoreName *string `json:"store_name,omitempty"`
	StoreUrl *string `json:"store_url,omitempty"`
	// Seller positive feedback percentage
	PositiveRate *string `json:"positive_rate,omitempty"`
	Score *int32 `json:"score,omitempty"`
}

// NewProductSeller instantiates a new ProductSeller object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProductSeller() *ProductSeller {
	this := ProductSeller{}
	return &this
}

// NewProductSellerWithDefaults instantiates a new ProductSeller object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProductSellerWithDefaults() *ProductSeller {
	this := ProductSeller{}
	return &this
}

// GetSellerAdminSeq returns the SellerAdminSeq field value if set, zero value otherwise.
func (o *ProductSeller) GetSellerAdminSeq() int32 {
	if o == nil || IsNil(o.SellerAdminSeq) {
		var ret int32
		return ret
	}
	return *o.SellerAdminSeq
}

// GetSellerAdminSeqOk returns a tuple with the SellerAdminSeq field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductSeller) GetSellerAdminSeqOk() (*int32, bool) {
	if o == nil || IsNil(o.SellerAdminSeq) {
		return nil, false
	}
	return o.SellerAdminSeq, true
}

// HasSellerAdminSeq returns a boolean if a field has been set.
func (o *ProductSeller) HasSellerAdminSeq() bool {
	if o != nil && !IsNil(o.SellerAdminSeq) {
		return true
	}

	return false
}

// SetSellerAdminSeq gets a reference to the given int32 and assigns it to the SellerAdminSeq field.
func (o *ProductSeller) SetSellerAdminSeq(v int32) {
	o.SellerAdminSeq = &v
}

// GetStoreNum returns the StoreNum field value if set, zero value otherwise.
func (o *ProductSeller) GetStoreNum() int32 {
	if o == nil || IsNil(o.StoreNum) {
		var ret int32
		return ret
	}
	return *o.StoreNum
}

// GetStoreNumOk returns a tuple with the StoreNum field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductSeller) GetStoreNumOk() (*int32, bool) {
	if o == nil || IsNil(o.StoreNum) {
		return nil, false
	}
	return o.StoreNum, true
}

// HasStoreNum returns a boolean if a field has been set.
func (o *ProductSeller) HasStoreNum() bool {
	if o != nil && !IsNil(o.StoreNum) {
		return true
	}

	return false
}

// SetStoreNum gets a reference to the given int32 and assigns it to the StoreNum field.
func (o *ProductSeller) SetStoreNum(v int32) {
	o.StoreNum = &v
}

// GetStoreName returns the StoreName field value if set, zero value otherwise.
func (o *ProductSeller) GetStoreName() string {
	if o == nil || IsNil(o.StoreName) {
		var ret string
		return ret
	}
	return *o.StoreName
}

// GetStoreNameOk returns a tuple with the StoreName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductSeller) GetStoreNameOk() (*string, bool) {
	if o == nil || IsNil(o.StoreName) {
		return nil, false
	}
	return o.StoreName, true
}

// HasStoreName returns a boolean if a field has been set.
func (o *ProductSeller) HasStoreName() bool {
	if o != nil && !IsNil(o.StoreName) {
		return true
	}

	return false
}

// SetStoreName gets a reference to the given string and assigns it to the StoreName field.
func (o *ProductSeller) SetStoreName(v string) {
	o.StoreName = &v
}

// GetStoreUrl returns the StoreUrl field value if set, zero value otherwise.
func (o *ProductSeller) GetStoreUrl() string {
	if o == nil || IsNil(o.StoreUrl) {
		var ret string
		return ret
	}
	return *o.StoreUrl
}

// GetStoreUrlOk returns a tuple with the StoreUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductSeller) GetStoreUrlOk() (*string, bool) {
	if o == nil || IsNil(o.StoreUrl) {
		return nil, false
	}
	return o.StoreUrl, true
}

// HasStoreUrl returns a boolean if a field has been set.
func (o *ProductSeller) HasStoreUrl() bool {
	if o != nil && !IsNil(o.StoreUrl) {
		return true
	}

	return false
}

// SetStoreUrl gets a reference to the given string and assigns it to the StoreUrl field.
func (o *ProductSeller) SetStoreUrl(v string) {
	o.StoreUrl = &v
}

// GetPositiveRate returns the PositiveRate field value if set, zero value otherwise.
func (o *ProductSeller) GetPositiveRate() string {
	if o == nil || IsNil(o.PositiveRate) {
		var ret string
		return ret
	}
	return *o.PositiveRate
}

// GetPositiveRateOk returns a tuple with the PositiveRate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductSeller) GetPositiveRateOk() (*string, bool) {
	if o == nil || IsNil(o.PositiveRate) {
		return nil, false
	}
	return o.PositiveRate, true
}

// HasPositiveRate returns a boolean if a field has been set.
func (o *ProductSeller) HasPositiveRate() bool {
	if o != nil && !IsNil(o.PositiveRate) {
		return true
	}

	return false
}

// SetPositiveRate gets a reference to the given string and assigns it to the PositiveRate field.
func (o *ProductSeller) SetPositiveRate(v string) {
	o.PositiveRate = &v
}

// GetScore returns the Score field value if set, zero value otherwise.
func (o *ProductSeller) GetScore() int32 {
	if o == nil || IsNil(o.Score) {
		var ret int32
		return ret
	}
	return *o.Score
}

// GetScoreOk returns a tuple with the Score field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductSeller) GetScoreOk() (*int32, bool) {
	if o == nil || IsNil(o.Score) {
		return nil, false
	}
	return o.Score, true
}

// HasScore returns a boolean if a field has been set.
func (o *ProductSeller) HasScore() bool {
	if o != nil && !IsNil(o.Score) {
		return true
	}

	return false
}

// SetScore gets a reference to the given int32 and assigns it to the Score field.
func (o *ProductSeller) SetScore(v int32) {
	o.Score = &v
}

func (o ProductSeller) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProductSeller) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.SellerAdminSeq) {
		toSerialize["seller_admin_seq"] = o.SellerAdminSeq
	}
	if !IsNil(o.StoreNum) {
		toSerialize["store_num"] = o.StoreNum
	}
	if !IsNil(o.StoreName) {
		toSerialize["store_name"] = o.StoreName
	}
	if !IsNil(o.StoreUrl) {
		toSerialize["store_url"] = o.StoreUrl
	}
	if !IsNil(o.PositiveRate) {
		toSerialize["positive_rate"] = o.PositiveRate
	}
	if !IsNil(o.Score) {
		toSerialize["score"] = o.Score
	}
	return toSerialize, nil
}

type NullableProductSeller struct {
	value *ProductSeller
	isSet bool
}

func (v NullableProductSeller) Get() *ProductSeller {
	return v.value
}

func (v *NullableProductSeller) Set(val *ProductSeller) {
	v.value = val
	v.isSet = true
}

func (v NullableProductSeller) IsSet() bool {
	return v.isSet
}

func (v *NullableProductSeller) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProductSeller(val *ProductSeller) *NullableProductSeller {
	return &NullableProductSeller{value: val, isSet: true}
}

func (v NullableProductSeller) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProductSeller) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


