/*
AliExpress Parser API

Real-time AliExpress data parser covering products, product reviews, sellers, store coupons, a seller's product catalog, and product search by text or image. Products: pricing, stock status, shipping options, seller information, product configurations (SKUs), and more - scoped to a specific country and currency. Reviews: customer ratings and feedback for a product. Sellers: full store profile with ratings, feedback, and categories. Coupons: active seller coupon codes with discounts, thresholds, budgets, and expiry. Seller products: a store's product catalog, paginated and best-selling first. Search: find products by keyword or by uploading an image, returning paginated product results with their categories. 

API version: 2.1.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aligate

import (
	"encoding/json"
)

// checks if the SellerProductsMeta type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SellerProductsMeta{}

// SellerProductsMeta Request metadata set by the seller-products parser
type SellerProductsMeta struct {
	Code *int32 `json:"code,omitempty"`
	// Parser spider version
	V *string `json:"v,omitempty"`
	// UTC timestamp when the request was received
	RequestTime *string `json:"request_time,omitempty"`
	// Total parse duration
	ExecutionTime *string `json:"execution_time,omitempty"`
}

// NewSellerProductsMeta instantiates a new SellerProductsMeta object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSellerProductsMeta() *SellerProductsMeta {
	this := SellerProductsMeta{}
	return &this
}

// NewSellerProductsMetaWithDefaults instantiates a new SellerProductsMeta object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSellerProductsMetaWithDefaults() *SellerProductsMeta {
	this := SellerProductsMeta{}
	return &this
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *SellerProductsMeta) GetCode() int32 {
	if o == nil || IsNil(o.Code) {
		var ret int32
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SellerProductsMeta) GetCodeOk() (*int32, bool) {
	if o == nil || IsNil(o.Code) {
		return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *SellerProductsMeta) HasCode() bool {
	if o != nil && !IsNil(o.Code) {
		return true
	}

	return false
}

// SetCode gets a reference to the given int32 and assigns it to the Code field.
func (o *SellerProductsMeta) SetCode(v int32) {
	o.Code = &v
}

// GetV returns the V field value if set, zero value otherwise.
func (o *SellerProductsMeta) GetV() string {
	if o == nil || IsNil(o.V) {
		var ret string
		return ret
	}
	return *o.V
}

// GetVOk returns a tuple with the V field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SellerProductsMeta) GetVOk() (*string, bool) {
	if o == nil || IsNil(o.V) {
		return nil, false
	}
	return o.V, true
}

// HasV returns a boolean if a field has been set.
func (o *SellerProductsMeta) HasV() bool {
	if o != nil && !IsNil(o.V) {
		return true
	}

	return false
}

// SetV gets a reference to the given string and assigns it to the V field.
func (o *SellerProductsMeta) SetV(v string) {
	o.V = &v
}

// GetRequestTime returns the RequestTime field value if set, zero value otherwise.
func (o *SellerProductsMeta) GetRequestTime() string {
	if o == nil || IsNil(o.RequestTime) {
		var ret string
		return ret
	}
	return *o.RequestTime
}

// GetRequestTimeOk returns a tuple with the RequestTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SellerProductsMeta) GetRequestTimeOk() (*string, bool) {
	if o == nil || IsNil(o.RequestTime) {
		return nil, false
	}
	return o.RequestTime, true
}

// HasRequestTime returns a boolean if a field has been set.
func (o *SellerProductsMeta) HasRequestTime() bool {
	if o != nil && !IsNil(o.RequestTime) {
		return true
	}

	return false
}

// SetRequestTime gets a reference to the given string and assigns it to the RequestTime field.
func (o *SellerProductsMeta) SetRequestTime(v string) {
	o.RequestTime = &v
}

// GetExecutionTime returns the ExecutionTime field value if set, zero value otherwise.
func (o *SellerProductsMeta) GetExecutionTime() string {
	if o == nil || IsNil(o.ExecutionTime) {
		var ret string
		return ret
	}
	return *o.ExecutionTime
}

// GetExecutionTimeOk returns a tuple with the ExecutionTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SellerProductsMeta) GetExecutionTimeOk() (*string, bool) {
	if o == nil || IsNil(o.ExecutionTime) {
		return nil, false
	}
	return o.ExecutionTime, true
}

// HasExecutionTime returns a boolean if a field has been set.
func (o *SellerProductsMeta) HasExecutionTime() bool {
	if o != nil && !IsNil(o.ExecutionTime) {
		return true
	}

	return false
}

// SetExecutionTime gets a reference to the given string and assigns it to the ExecutionTime field.
func (o *SellerProductsMeta) SetExecutionTime(v string) {
	o.ExecutionTime = &v
}

func (o SellerProductsMeta) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SellerProductsMeta) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Code) {
		toSerialize["code"] = o.Code
	}
	if !IsNil(o.V) {
		toSerialize["v"] = o.V
	}
	if !IsNil(o.RequestTime) {
		toSerialize["request_time"] = o.RequestTime
	}
	if !IsNil(o.ExecutionTime) {
		toSerialize["execution_time"] = o.ExecutionTime
	}
	return toSerialize, nil
}

type NullableSellerProductsMeta struct {
	value *SellerProductsMeta
	isSet bool
}

func (v NullableSellerProductsMeta) Get() *SellerProductsMeta {
	return v.value
}

func (v *NullableSellerProductsMeta) Set(val *SellerProductsMeta) {
	v.value = val
	v.isSet = true
}

func (v NullableSellerProductsMeta) IsSet() bool {
	return v.isSet
}

func (v *NullableSellerProductsMeta) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSellerProductsMeta(val *SellerProductsMeta) *NullableSellerProductsMeta {
	return &NullableSellerProductsMeta{value: val, isSet: true}
}

func (v NullableSellerProductsMeta) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSellerProductsMeta) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


