/*
AliExpress Parser API

Real-time AliExpress data parser covering products, product reviews, sellers, store coupons, a seller's product catalog, and product search by text or image. Products: pricing, stock status, shipping options, seller information, product configurations (SKUs), and more - scoped to a specific country and currency. Reviews: customer ratings and feedback for a product. Sellers: full store profile with ratings, feedback, and categories. Coupons: active seller coupon codes with discounts, thresholds, budgets, and expiry. Seller products: a store's product catalog, paginated and best-selling first. Search: find products by keyword or by uploading an image, returning paginated product results with their categories. 

API version: 2.1.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aligate

import (
	"encoding/json"
)

// checks if the ProductVideo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProductVideo{}

// ProductVideo struct for ProductVideo
type ProductVideo struct {
	Id *int64 `json:"id,omitempty"`
	Url *string `json:"url,omitempty"`
	Thumbnail *string `json:"thumbnail,omitempty"`
}

// NewProductVideo instantiates a new ProductVideo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProductVideo() *ProductVideo {
	this := ProductVideo{}
	return &this
}

// NewProductVideoWithDefaults instantiates a new ProductVideo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProductVideoWithDefaults() *ProductVideo {
	this := ProductVideo{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ProductVideo) GetId() int64 {
	if o == nil || IsNil(o.Id) {
		var ret int64
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductVideo) GetIdOk() (*int64, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ProductVideo) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int64 and assigns it to the Id field.
func (o *ProductVideo) SetId(v int64) {
	o.Id = &v
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *ProductVideo) GetUrl() string {
	if o == nil || IsNil(o.Url) {
		var ret string
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductVideo) GetUrlOk() (*string, bool) {
	if o == nil || IsNil(o.Url) {
		return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *ProductVideo) HasUrl() bool {
	if o != nil && !IsNil(o.Url) {
		return true
	}

	return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *ProductVideo) SetUrl(v string) {
	o.Url = &v
}

// GetThumbnail returns the Thumbnail field value if set, zero value otherwise.
func (o *ProductVideo) GetThumbnail() string {
	if o == nil || IsNil(o.Thumbnail) {
		var ret string
		return ret
	}
	return *o.Thumbnail
}

// GetThumbnailOk returns a tuple with the Thumbnail field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductVideo) GetThumbnailOk() (*string, bool) {
	if o == nil || IsNil(o.Thumbnail) {
		return nil, false
	}
	return o.Thumbnail, true
}

// HasThumbnail returns a boolean if a field has been set.
func (o *ProductVideo) HasThumbnail() bool {
	if o != nil && !IsNil(o.Thumbnail) {
		return true
	}

	return false
}

// SetThumbnail gets a reference to the given string and assigns it to the Thumbnail field.
func (o *ProductVideo) SetThumbnail(v string) {
	o.Thumbnail = &v
}

func (o ProductVideo) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProductVideo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Url) {
		toSerialize["url"] = o.Url
	}
	if !IsNil(o.Thumbnail) {
		toSerialize["thumbnail"] = o.Thumbnail
	}
	return toSerialize, nil
}

type NullableProductVideo struct {
	value *ProductVideo
	isSet bool
}

func (v NullableProductVideo) Get() *ProductVideo {
	return v.value
}

func (v *NullableProductVideo) Set(val *ProductVideo) {
	v.value = val
	v.isSet = true
}

func (v NullableProductVideo) IsSet() bool {
	return v.isSet
}

func (v *NullableProductVideo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProductVideo(val *ProductVideo) *NullableProductVideo {
	return &NullableProductVideo{value: val, isSet: true}
}

func (v NullableProductVideo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProductVideo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


